import React, {useState} from 'react';
import Screenshot from '../ScreenShots';

function Narrows(){
    const [screens,setScreens] = useState('');

    const turnGreen = (div) => {
        div.style.fill="rgba(0, 255, 0, 0.5)";
    }
    const returnColor = (div) => {
        div.style.fill="rgba(0, 0, 0, 0)";
    }
    const textGreen = (textP) => {
        textP.style.color="rgba(0, 255, 0, 1)"
    }
    const returnTextColor = (textP) => {
        textP.style.color="white";
    }
    return(
        <div className="narrowsFullGrid">
            <h1 className="mapTitleNarrows">Narrows</h1>
            <div className="calloutsList" id="narrowsCallouts">   
                <p onMouseOver={() => {setScreens('Afro'); turnGreen(document.getElementById('afroNarrows')); textGreen(document.getElementById('afroNarrowsText')); turnGreen(document.getElementById('afroNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('afroNarrows')); returnTextColor(document.getElementById('afroNarrowsText')); returnColor(document.getElementById('afroNarrows2'))}} id="afroNarrowsText">Afro</p>
                <p onMouseOver={() => {setScreens('Back Cannon'); turnGreen(document.getElementById('backCannonNarrows')); textGreen(document.getElementById('backCannonNarrowsText')); turnGreen(document.getElementById('backCannonNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('backCannonNarrows')); returnTextColor(document.getElementById('backCannonNarrowsText')); returnColor(document.getElementById('backCannonNarrows2'))}} id="backCannonNarrowsText">Back Cannon</p>
                <p onMouseOver={() => {setScreens('Back Flag'); turnGreen(document.getElementById('backFlagNarrows')); textGreen(document.getElementById('backFlagNarrowsText')); turnGreen(document.getElementById('backFlagNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('backFlagNarrows')); returnTextColor(document.getElementById('backFlagNarrowsText')); returnColor(document.getElementById('backFlagNarrows2'))}} id="backFlagNarrowsText">Back Flag</p>
                <p onMouseOver={() => {setScreens('Cannon'); turnGreen(document.getElementById('cannonNarrows')); textGreen(document.getElementById('cannonNarrowsText')); turnGreen(document.getElementById('cannonNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonNarrows')); returnTextColor(document.getElementById('cannonNarrowsText')); returnColor(document.getElementById('cannonNarrows2'))}} id="cannonNarrowsText">Cannon</p>
                <p onMouseOver={() => {setScreens('Cannon Door'); turnGreen(document.getElementById('cannonDoorNarrows')); textGreen(document.getElementById('cannonDoorNarrowsText')); turnGreen(document.getElementById('cannonDoorNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonDoorNarrows')); returnTextColor(document.getElementById('cannonDoorNarrowsText')); returnColor(document.getElementById('cannonDoorNarrows2'))}} id="cannonDoorNarrowsText">Cannon Door</p>
                <p onMouseOver={() => {setScreens('Cannon Lobby'); turnGreen(document.getElementById('cannonLobbyNarrows')); textGreen(document.getElementById('cannonLobbyNarrowsText')); turnGreen(document.getElementById('cannonLobbyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonLobbyNarrows')); returnTextColor(document.getElementById('cannonLobbyNarrowsText')); returnColor(document.getElementById('cannonLobbyNarrows2'))}} id="cannonLobbyNarrowsText">Cannon Lobby</p>
                <p onMouseOver={() => {setScreens('Cannon Power Up'); turnGreen(document.getElementById('cannonPowerUpNarrows')); textGreen(document.getElementById('cannonPowerUpNarrowsText')); turnGreen(document.getElementById('cannonPowerUpNarrows2')); turnGreen(document.getElementById('cannonPowerUpNarrows3')); turnGreen(document.getElementById('cannonPowerUpNarrows4'));}} onMouseOut={() => {returnColor(document.getElementById('cannonPowerUpNarrows')); returnTextColor(document.getElementById('cannonPowerUpNarrowsText')); returnColor(document.getElementById('cannonPowerUpNarrows2')); returnColor(document.getElementById('cannonPowerUpNarrows3')); returnColor(document.getElementById('cannonPowerUpNarrows4'))}} id="cannonPowerUpNarrowsText">Cannon Power Up</p>
                <p onMouseOver={() => {setScreens('Cannon Shockwave'); turnGreen(document.getElementById('cannonShockwaveNarrows')); textGreen(document.getElementById('cannonShockwaveNarrowsText')); turnGreen(document.getElementById('cannonShockwaveNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonShockwaveNarrows')); returnTextColor(document.getElementById('cannonShockwaveNarrowsText')); returnColor(document.getElementById('cannonShockwaveNarrows2'))}} id="cannonShockwaveNarrowsText">Cannon Shockwave</p>
                <p onMouseOver={() => {setScreens('Cannon Sneaky'); turnGreen(document.getElementById('cannonSneakyNarrows')); textGreen(document.getElementById('cannonSneakyNarrowsText')); turnGreen(document.getElementById('cannonSneakyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonSneakyNarrows')); returnTextColor(document.getElementById('cannonSneakyNarrowsText')); returnColor(document.getElementById('cannonSneakyNarrows2'))}} id="cannonSneakyNarrowsText">Cannon Sneaky</p>
                <p onMouseOver={() => {setScreens('Cannon Spawn'); turnGreen(document.getElementById('cannonSpawnNarrows')); textGreen(document.getElementById('cannonSpawnNarrowsText')); turnGreen(document.getElementById('cannonSpawnNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonSpawnNarrows')); returnTextColor(document.getElementById('cannonSpawnNarrowsText')); returnColor(document.getElementById('cannonSpawnNarrows2'))}} id="cannonSpawnNarrowsText">Cannon Spawn</p>
                <p onMouseOver={() => {setScreens('Flag'); turnGreen(document.getElementById('flagNarrows')); textGreen(document.getElementById('flagNarrowsText')); turnGreen(document.getElementById('flagNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagNarrows')); returnTextColor(document.getElementById('flagNarrowsText')); returnColor(document.getElementById('flagNarrows2'))}} id="flagNarrowsText">Flag</p>
                <p onMouseOver={() => {setScreens('Flag Box'); turnGreen(document.getElementById('flagBoxNarrows')); textGreen(document.getElementById('flagBoxNarrowsText')); turnGreen(document.getElementById('flagBoxNarrows2')); turnGreen(document.getElementById('flagBoxNarrows3')); turnGreen(document.getElementById('flagBoxNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('flagBoxNarrows')); returnTextColor(document.getElementById('flagBoxNarrowsText')); returnColor(document.getElementById('flagBoxNarrows2')); returnColor(document.getElementById('flagBoxNarrows3')); returnColor(document.getElementById('flagBoxNarrows4'))}} id="flagBoxNarrowsText">Flag Box</p>
                <p onMouseOver={() => {setScreens('Flag Door'); turnGreen(document.getElementById('flagDoorNarrows')); textGreen(document.getElementById('flagDoorNarrowsText')); turnGreen(document.getElementById('flagDoorNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagDoorNarrows')); returnTextColor(document.getElementById('flagDoorNarrowsText')); returnColor(document.getElementById('flagDoorNarrows2'))}} id="flagDoorNarrowsText">flagDoorNarrows</p>
                <p onMouseOver={() => {setScreens('Flag Lobby'); turnGreen(document.getElementById('flagLobbyNarrows')); textGreen(document.getElementById('flagLobbyNarrowsText')); turnGreen(document.getElementById('flagLobbyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagLobbyNarrows')); returnTextColor(document.getElementById('flagLobbyNarrowsText')); returnColor(document.getElementById('flagLobbyNarrows2'))}} id="flagLobbyNarrowsText">flagLobbyNarrows</p>
                <p onMouseOver={() => {setScreens('Flag Power Up'); turnGreen(document.getElementById('flagPowerUpNarrows')); textGreen(document.getElementById('flagPowerUpNarrowsText')); turnGreen(document.getElementById('flagPowerUpNarrows2')); turnGreen(document.getElementById('flagPowerUpNarrows3')); turnGreen(document.getElementById('flagPowerUpNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('flagPowerUpNarrows')); returnTextColor(document.getElementById('flagPowerUpNarrowsText')); returnColor(document.getElementById('flagPowerUpNarrows2')); returnColor(document.getElementById('flagPowerUpNarrows3')); returnColor(document.getElementById('flagPowerUpNarrows4'))}} id="flagPowerUpNarrowsText">Flag Power Up</p>
                <p onMouseOver={() => {setScreens('Flag Shockwave'); turnGreen(document.getElementById('flagShockwaveNarrows')); textGreen(document.getElementById('flagShockwaveNarrowsText')); turnGreen(document.getElementById('flagShockwaveNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagShockwaveNarrows')); returnTextColor(document.getElementById('flagShockwaveNarrowsText')); returnColor(document.getElementById('flagShockwaveNarrows2'))}} id="flagShockwaveNarrowsText">Flag Shockwave</p>
                <p onMouseOver={() => {setScreens('Flag Sneaky'); turnGreen(document.getElementById('flagSneakyNarrows')); textGreen(document.getElementById('flagSneakyNarrowsText')); turnGreen(document.getElementById('flagSneakyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagSneakyNarrows')); returnTextColor(document.getElementById('flagSneakyNarrowsText')); returnColor(document.getElementById('flagSneakyNarrows2'))}} id="flagSneakyNarrowsText">Flag Sneaky</p>
                <p onMouseOver={() => {setScreens('L0'); turnGreen(document.getElementById('l0Narrows')); textGreen(document.getElementById('l0NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('l0Narrows')); returnTextColor(document.getElementById('l0NarrowsText'))}} id="l0NarrowsText">l0Narrows</p>
                <p onMouseOver={() => {setScreens('L1'); turnGreen(document.getElementById('l1Narrows')); textGreen(document.getElementById('l1NarrowsText')); turnGreen(document.getElementById('l1Narrows2'))}} onMouseOut={() => {returnColor(document.getElementById('l1Narrows')); returnTextColor(document.getElementById('l1NarrowsText')); returnColor(document.getElementById('l1Narrows2'))}} id="l1NarrowsText">L1</p>
                <p onMouseOver={() => {setScreens('L2'); turnGreen(document.getElementById('l2Narrows')); textGreen(document.getElementById('l2NarrowsText')); turnGreen(document.getElementById('l2Narrows2'))}} onMouseOut={() => {returnColor(document.getElementById('l2Narrows')); returnTextColor(document.getElementById('l2NarrowsText')); returnColor(document.getElementById('l2Narrows2'))}} id="l2NarrowsText">L2</p>
                <p onMouseOver={() => {setScreens('L3'); turnGreen(document.getElementById('l3Narrows')); textGreen(document.getElementById('l3NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('l3Narrows')); returnTextColor(document.getElementById('l3NarrowsText'))}} id="l3NarrowsText">L3</p>
                <p onMouseOver={() => {setScreens('L4'); turnGreen(document.getElementById('l4Narrows')); textGreen(document.getElementById('l4NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('l4Narrows')); returnTextColor(document.getElementById('l4NarrowsText'))}} id="l4NarrowsText">L4</p>
                <p onMouseOver={() => {setScreens('Left Attic'); turnGreen(document.getElementById('leftAtticNarrows')); textGreen(document.getElementById('leftAtticNarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('leftAtticNarrows')); returnTextColor(document.getElementById('leftAtticNarrowsText'))}} id="leftAtticNarrowsText">Left Attic</p>
                <p onMouseOver={() => {setScreens('Left Box'); turnGreen(document.getElementById('leftBoxNarrows')); textGreen(document.getElementById('leftBoxNarrowsText')); turnGreen(document.getElementById('leftBoxNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('leftBoxNarrows')); returnTextColor(document.getElementById('leftBoxNarrowsText')); returnColor(document.getElementById('leftBoxNarrows2'))}} id="leftBoxNarrowsText">Left Box</p>
                <p onMouseOver={() => {setScreens('Left Shoulder'); turnGreen(document.getElementById('leftShoulderNarrows')); textGreen(document.getElementById('leftShoulderNarrowsText')); turnGreen(document.getElementById('leftShoulderNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('leftShoulderNarrows')); returnTextColor(document.getElementById('leftShoulderNarrowsText')); returnColor(document.getElementById('leftShoulderNarrows2'))}} id="leftShoulderNarrowsText">Left Shoulder</p>
                <p onMouseOver={() => {setScreens('Lobby'); turnGreen(document.getElementById('lobbyNarrows')); textGreen(document.getElementById('lobbyNarrowsText')); turnGreen(document.getElementById('lobbyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('lobbyNarrows')); returnTextColor(document.getElementById('lobbyNarrowsText')); returnColor(document.getElementById('lobbyNarrows2'))}} id="lobbyNarrowsText">Lobby</p>
                <p onMouseOver={() => {setScreens('Main Cannon'); turnGreen(document.getElementById('mainCannonNarrows')); textGreen(document.getElementById('mainCannonNarrowsText')); turnGreen(document.getElementById('mainCannonNarrows2')); turnGreen(document.getElementById('mainCannonNarrows3')); turnGreen(document.getElementById('mainCannonNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('mainCannonNarrows')); returnTextColor(document.getElementById('mainCannonNarrowsText')); returnColor(document.getElementById('mainCannonNarrows2')); returnColor(document.getElementById('mainCannonNarrows3')); returnColor(document.getElementById('mainCannonNarrows4'))}} id="mainCannonNarrowsText">Main Cannon</p>
                <p onMouseOver={() => {setScreens('Mauler'); turnGreen(document.getElementById('mauler50Narrows')); textGreen(document.getElementById('mauler50NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('mauler50Narrows')); returnTextColor(document.getElementById('mauler50NarrowsText'))}} id="mauler50NarrowsText">Mauler/50</p>
                <p onMouseOver={() => {setScreens('Mini Mohawk'); turnGreen(document.getElementById('miniMohawkNarrows')); textGreen(document.getElementById('miniMohawkNarrowsText')); turnGreen(document.getElementById('miniMohawkNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('miniMohawkNarrows')); returnTextColor(document.getElementById('miniMohawkNarrowsText')); returnColor(document.getElementById('miniMohawkNarrows2'))}} id="miniMohawkNarrowsText">Mini Mohawk</p>
                <p onMouseOver={() => {setScreens('Mohawk'); turnGreen(document.getElementById('mohawkNarrows')); textGreen(document.getElementById('mohawkNarrowsText')); turnGreen(document.getElementById('mohawkNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('mohawkNarrows')); returnTextColor(document.getElementById('mohawkNarrowsText')); returnColor(document.getElementById('mohawkNarrows2'))}} id="mohawkNarrowsText">Mohawk</p>
                <p onMouseOver={() => {setScreens('Power Up'); turnGreen(document.getElementById('powerUpNarrows')); textGreen(document.getElementById('powerUpNarrowsText')); turnGreen(document.getElementById('powerUpNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('powerUpNarrows')); returnTextColor(document.getElementById('powerUpNarrowsText')); returnColor(document.getElementById('powerUpNarrows2'))}} id="powerUpNarrowsText">Power Up</p>
                <p onMouseOver={() => {setScreens('R0'); turnGreen(document.getElementById('r0Narrows')); textGreen(document.getElementById('r0NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('r0Narrows')); returnTextColor(document.getElementById('r0NarrowsText'))}} id="r0NarrowsText">R0</p>
                <p onMouseOver={() => {setScreens('R1'); turnGreen(document.getElementById('r1Narrows')); textGreen(document.getElementById('r1NarrowsText')); turnGreen(document.getElementById('r1Narrows2'))}} onMouseOut={() => {returnColor(document.getElementById('r1Narrows')); returnTextColor(document.getElementById('r1NarrowsText')); returnColor(document.getElementById('r1Narrows2'))}} id="r1NarrowsText">R1</p>
                <p onMouseOver={() => {setScreens('R2'); turnGreen(document.getElementById('r2Narrows')); textGreen(document.getElementById('r2NarrowsText')); turnGreen(document.getElementById('r2Narrows2'))}} onMouseOut={() => {returnColor(document.getElementById('r2Narrows')); returnTextColor(document.getElementById('r2NarrowsText')); returnColor(document.getElementById('r2Narrows2'))}} id="r2NarrowsText">R2</p>
                <p onMouseOver={() => {setScreens('R3'); turnGreen(document.getElementById('r3Narrows')); textGreen(document.getElementById('r3NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('r3Narrows')); returnTextColor(document.getElementById('r3NarrowsText'))}} id="r3NarrowsText">R3</p>
                <p onMouseOver={() => {setScreens('R4'); turnGreen(document.getElementById('r4Narrows')); textGreen(document.getElementById('r4NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('r4Narrows')); returnTextColor(document.getElementById('r4NarrowsText'))}} id="r4NarrowsText">R4</p>
                <p onMouseOver={() => {setScreens('Right Attic'); turnGreen(document.getElementById('rightAtticNarrows')); textGreen(document.getElementById('rightAtticNarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('rightAtticNarrows')); returnTextColor(document.getElementById('rightAtticNarrowsText'))}} id="rightAtticNarrowsText">Right Attic</p>
                <p onMouseOver={() => {setScreens('Right Box'); turnGreen(document.getElementById('rightBoxNarrows')); textGreen(document.getElementById('rightBoxNarrowsText')); turnGreen(document.getElementById('rightBoxNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('rightBoxNarrows')); returnTextColor(document.getElementById('rightBoxNarrowsText')); returnColor(document.getElementById('rightBoxNarrows2'))}} id="rightBoxNarrowsText">Right Box</p>
                <p onMouseOver={() => {setScreens('Right Shoulder'); turnGreen(document.getElementById('rightShoulderNarrows')); textGreen(document.getElementById('rightShoulderNarrowsText')); turnGreen(document.getElementById('rightShoulderNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('rightShoulderNarrows')); returnTextColor(document.getElementById('rightShoulderNarrowsText')); returnColor(document.getElementById('rightShoulderNarrows2'))}} id="rightShoulderNarrowsText">Right Shoulder</p>
                <p onMouseOver={() => {setScreens('Rockets'); turnGreen(document.getElementById('rocketsNarrows')); textGreen(document.getElementById('rocketsNarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('rocketsNarrows')); returnTextColor(document.getElementById('rocketsNarrowsText'))}} id="rocketsNarrowsText">Rockets</p>
                <p onMouseOver={() => {setScreens('Stage'); turnGreen(document.getElementById('stageNarrows')); textGreen(document.getElementById('stageNarrowsText')); turnGreen(document.getElementById('stageNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('stageNarrows')); returnTextColor(document.getElementById('stageNarrowsText')); returnColor(document.getElementById('stageNarrows2'))}} id="stageNarrowsText">Stage</p>
            </div>
            <svg id="narrowsMap" width="750px" height="625px">
                <polygon onMouseOver={() => {setScreens('Afro'); turnGreen(document.getElementById('afroNarrows')); textGreen(document.getElementById('afroNarrowsText')); turnGreen(document.getElementById('afroNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('afroNarrows')); returnTextColor(document.getElementById('afroNarrowsText')); returnColor(document.getElementById('afroNarrows2'))}}  id="afroNarrows" points="207,143 199,143 199,153 197,153 197,158 199,158 199,161 197,161 197,167 199,167 199,177 207,177 207,167 209,167 209,161 207,161 207,158 209,158 209,153 207,153"/>
                <polygon onMouseOver={() => {setScreens('Afro'); turnGreen(document.getElementById('afroNarrows')); textGreen(document.getElementById('afroNarrowsText')); turnGreen(document.getElementById('afroNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('afroNarrows')); returnTextColor(document.getElementById('afroNarrowsText')); returnColor(document.getElementById('afroNarrows2'))}}  id="afroNarrows2" points="531,143 539,143 539,153 541,153 541,158 539,158 539,161 541,161 541,167 539,167 539,177 531,177 531,167 529,167 529,161 531,161 531,158 529,158 529,153 531,153"/>
                <polygon onMouseOver={() => {setScreens('Back Cannon'); turnGreen(document.getElementById('backCannonNarrows')); textGreen(document.getElementById('backCannonNarrowsText')); turnGreen(document.getElementById('backCannonNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('backCannonNarrows')); returnTextColor(document.getElementById('backCannonNarrowsText')); returnColor(document.getElementById('backCannonNarrows2'))}}  id="backCannonNarrows" points="63,221 25,221 25,252 63,252"/>
                <polygon onMouseOver={() => {setScreens('Back Cannon'); turnGreen(document.getElementById('backCannonNarrows')); textGreen(document.getElementById('backCannonNarrowsText')); turnGreen(document.getElementById('backCannonNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('backCannonNarrows')); returnTextColor(document.getElementById('backCannonNarrowsText')); returnColor(document.getElementById('backCannonNarrows2'))}}  id="backCannonNarrows2" points="722,221 684,221 684,252 722,252"/>
                <polygon onMouseOver={() => {setScreens('Back Flag'); turnGreen(document.getElementById('backFlagNarrows')); textGreen(document.getElementById('backFlagNarrowsText')); turnGreen(document.getElementById('backFlagNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('backFlagNarrows')); returnTextColor(document.getElementById('backFlagNarrowsText')); returnColor(document.getElementById('backFlagNarrows2'))}}  id="backFlagNarrows" points="80,57 63,57 63,98 80,98"/>
                <polygon onMouseOver={() => {setScreens('Back Flag'); turnGreen(document.getElementById('backFlagNarrows')); textGreen(document.getElementById('backFlagNarrowsText')); turnGreen(document.getElementById('backFlagNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('backFlagNarrows')); returnTextColor(document.getElementById('backFlagNarrowsText')); returnColor(document.getElementById('backFlagNarrows2'))}}  id="backFlagNarrows2" points="684,57 667,57 667,98 684,98"/>
                <polygon onMouseOver={() => {setScreens('Cannon'); turnGreen(document.getElementById('cannonNarrows')); textGreen(document.getElementById('cannonNarrowsText')); turnGreen(document.getElementById('cannonNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonNarrows')); returnTextColor(document.getElementById('cannonNarrowsText')); returnColor(document.getElementById('cannonNarrows2'))}}  id="cannonNarrows" points="163,221 163,278 64,278 64,221"/>
                <polygon onMouseOver={() => {setScreens('Cannon'); turnGreen(document.getElementById('cannonNarrows')); textGreen(document.getElementById('cannonNarrowsText')); turnGreen(document.getElementById('cannonNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonNarrows')); returnTextColor(document.getElementById('cannonNarrowsText')); returnColor(document.getElementById('cannonNarrows2'))}}  id="cannonNarrows2" points="585,221 683,221 683,278 585,278"/>
                <polygon onMouseOver={() => {setScreens('Cannon Door'); turnGreen(document.getElementById('cannonDoorNarrows')); textGreen(document.getElementById('cannonDoorNarrowsText')); turnGreen(document.getElementById('cannonDoorNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonDoorNarrows')); returnTextColor(document.getElementById('cannonDoorNarrowsText')); returnColor(document.getElementById('cannonDoorNarrows2'))}}  id="cannonDoorNarrows" points="206,480 206,492 211,492 211,496 206,496 206,509 190,509 190,500 194,500 194,487 190,487 190,480"/>
                <polygon onMouseOver={() => {setScreens('Cannon Door'); turnGreen(document.getElementById('cannonDoorNarrows')); textGreen(document.getElementById('cannonDoorNarrowsText')); turnGreen(document.getElementById('cannonDoorNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonDoorNarrows')); returnTextColor(document.getElementById('cannonDoorNarrowsText')); returnColor(document.getElementById('cannonDoorNarrows2'))}}  id="cannonDoorNarrows2" points="557,480 541,480 541,492 536,492 536,496 541,496 541,509 557,509 557,500 553,500 553,487 557,487"/>
                <polygon onMouseOver={() => {setScreens('Cannon Lobby'); turnGreen(document.getElementById('cannonLobbyNarrows')); textGreen(document.getElementById('cannonLobbyNarrowsText')); turnGreen(document.getElementById('cannonLobbyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonLobbyNarrows')); returnTextColor(document.getElementById('cannonLobbyNarrowsText')); returnColor(document.getElementById('cannonLobbyNarrows2'))}}  id="cannonLobbyNarrows" points="99,195 81,195 81,214 99,214"/>
                <polygon onMouseOver={() => {setScreens('Cannon Lobby'); turnGreen(document.getElementById('cannonLobbyNarrows')); textGreen(document.getElementById('cannonLobbyNarrowsText')); turnGreen(document.getElementById('cannonLobbyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonLobbyNarrows')); returnTextColor(document.getElementById('cannonLobbyNarrowsText')); returnColor(document.getElementById('cannonLobbyNarrows2'))}}  id="cannonLobbyNarrows2" points="648,213 665,213 665,195 648,195"/>
                <polygon onMouseOver={() => {setScreens('Cannon Power Up'); turnGreen(document.getElementById('cannonPowerUpNarrows')); textGreen(document.getElementById('cannonPowerUpNarrowsText')); turnGreen(document.getElementById('cannonPowerUpNarrows2')); turnGreen(document.getElementById('cannonPowerUpNarrows3')); turnGreen(document.getElementById('cannonPowerUpNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('cannonPowerUpNarrows')); returnTextColor(document.getElementById('cannonPowerUpNarrowsText')); returnColor(document.getElementById('cannonPowerUpNarrows2')); returnColor(document.getElementById('cannonPowerUpNarrows3')); returnColor(document.getElementById('cannonPowerUpNarrows4'))}}  id="cannonPowerUpNarrows" points="265,209 235,209 234,229 223,242 201,242 201,245 203,245 203,248 201,248 201,251 204,251 204,253 205,253 205,256 201,256 201,263 200,263 200,279 239,279 265,250"/>
                <polygon onMouseOver={() => {setScreens('Cannon Power Up'); turnGreen(document.getElementById('cannonPowerUpNarrows')); textGreen(document.getElementById('cannonPowerUpNarrowsText')); turnGreen(document.getElementById('cannonPowerUpNarrows2')); turnGreen(document.getElementById('cannonPowerUpNarrows3')); turnGreen(document.getElementById('cannonPowerUpNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('cannonPowerUpNarrows')); returnTextColor(document.getElementById('cannonPowerUpNarrowsText')); returnColor(document.getElementById('cannonPowerUpNarrows2')); returnColor(document.getElementById('cannonPowerUpNarrows3')); returnColor(document.getElementById('cannonPowerUpNarrows4'))}}  id="cannonPowerUpNarrows2" points="248,498 248,538 221,569 182,569 182,552 184,552 184,545 188,545 188,542 187,542 187,540 184,540 184,537 186,537 186,534 184,534 184,531 206,531 217,518 217,510 218,510 218,498"/>
                <polygon onMouseOver={() => {setScreens('Cannon Power Up'); turnGreen(document.getElementById('cannonPowerUpNarrows')); textGreen(document.getElementById('cannonPowerUpNarrowsText')); turnGreen(document.getElementById('cannonPowerUpNarrows2')); turnGreen(document.getElementById('cannonPowerUpNarrows3')); turnGreen(document.getElementById('cannonPowerUpNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('cannonPowerUpNarrows')); returnTextColor(document.getElementById('cannonPowerUpNarrowsText')); returnColor(document.getElementById('cannonPowerUpNarrows2')); returnColor(document.getElementById('cannonPowerUpNarrows3')); returnColor(document.getElementById('cannonPowerUpNarrows4'))}}  id="cannonPowerUpNarrows3" points="546,242 546,245 544,245 544,248 546,248 546,251 543,251 543,253 542,253 542,256 546,256 546,263 547,263 547,279 508,279 482,250 482,209 512,209 512,221 513,221 513,229 524,242"/>
                <polygon onMouseOver={() => {setScreens('Cannon Power Up'); turnGreen(document.getElementById('cannonPowerUpNarrows')); textGreen(document.getElementById('cannonPowerUpNarrowsText')); turnGreen(document.getElementById('cannonPowerUpNarrows2')); turnGreen(document.getElementById('cannonPowerUpNarrows3')); turnGreen(document.getElementById('cannonPowerUpNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('cannonPowerUpNarrows')); returnTextColor(document.getElementById('cannonPowerUpNarrowsText')); returnColor(document.getElementById('cannonPowerUpNarrows2')); returnColor(document.getElementById('cannonPowerUpNarrows3')); returnColor(document.getElementById('cannonPowerUpNarrows4'))}}  id="cannonPowerUpNarrows4" points="499,498 529,498 529,510 531,510 531,519 541,531 563,531 563,534 561,534 561,537 563,537 563,540 560,540 560,542 559,543 559,545 563,545 563,552 564,552 564,569 526,569 499,538"/>
                <polygon onMouseOver={() => {setScreens('Cannon Shockwave'); turnGreen(document.getElementById('cannonShockwaveNarrows')); textGreen(document.getElementById('cannonShockwaveNarrowsText')); turnGreen(document.getElementById('cannonShockwaveNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonShockwaveNarrows')); returnTextColor(document.getElementById('cannonShockwaveNarrowsText')); returnColor(document.getElementById('cannonShockwaveNarrows2'))}}  id="cannonShockwaveNarrows" points="304,204 304,209 248,209 248,204"/>
                <polygon onMouseOver={() => {setScreens('Cannon Shockwave'); turnGreen(document.getElementById('cannonShockwaveNarrows')); textGreen(document.getElementById('cannonShockwaveNarrowsText')); turnGreen(document.getElementById('cannonShockwaveNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonShockwaveNarrows')); returnTextColor(document.getElementById('cannonShockwaveNarrowsText')); returnColor(document.getElementById('cannonShockwaveNarrows2'))}}  id="cannonShockwaveNarrows2" points="440,204 496,204 496,209 440,209"/>
                <polygon onMouseOver={() => {setScreens('Cannon Sneaky'); turnGreen(document.getElementById('cannonSneakyNarrows')); textGreen(document.getElementById('cannonSneakyNarrowsText')); turnGreen(document.getElementById('cannonSneakyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonSneakyNarrows')); returnTextColor(document.getElementById('cannonSneakyNarrowsText')); returnColor(document.getElementById('cannonSneakyNarrows2'))}}  id="cannonSneakyNarrows" points="200,215 200,220 163,220 163,215"/>
                <polygon onMouseOver={() => {setScreens('Cannon Sneaky'); turnGreen(document.getElementById('cannonSneakyNarrows')); textGreen(document.getElementById('cannonSneakyNarrowsText')); turnGreen(document.getElementById('cannonSneakyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonSneakyNarrows')); returnTextColor(document.getElementById('cannonSneakyNarrowsText')); returnColor(document.getElementById('cannonSneakyNarrows2'))}}  id="cannonSneakyNarrows2" points="547,215 584,215 584,220 547,220"/>
                <polygon onMouseOver={() => {setScreens('Cannon Spawn'); turnGreen(document.getElementById('cannonSpawnNarrows')); textGreen(document.getElementById('cannonSpawnNarrowsText')); turnGreen(document.getElementById('cannonSpawnNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonSpawnNarrows')); returnTextColor(document.getElementById('cannonSpawnNarrowsText')); returnColor(document.getElementById('cannonSpawnNarrows2'))}}  id="cannonSpawnNarrows" points="87,221 64,221 64,252 87,252"/>
                <polygon onMouseOver={() => {setScreens('Cannon Spawn'); turnGreen(document.getElementById('cannonSpawnNarrows')); textGreen(document.getElementById('cannonSpawnNarrowsText')); turnGreen(document.getElementById('cannonSpawnNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('cannonSpawnNarrows')); returnTextColor(document.getElementById('cannonSpawnNarrowsText')); returnColor(document.getElementById('cannonSpawnNarrows2'))}}  id="cannonSpawnNarrows2" points="665,251 665,221 683,221 683,251"/>
                <polygon onMouseOver={() => {setScreens('Flag'); turnGreen(document.getElementById('flagNarrows')); textGreen(document.getElementById('flagNarrowsText')); turnGreen(document.getElementById('flagNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagNarrows')); returnTextColor(document.getElementById('flagNarrowsText')); returnColor(document.getElementById('flagNarrows2'))}}  id="flagNarrows" points="168,57 81,57 81,98 168,98"/>
                <polygon onMouseOver={() => {setScreens('Flag'); turnGreen(document.getElementById('flagNarrows')); textGreen(document.getElementById('flagNarrowsText')); turnGreen(document.getElementById('flagNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagNarrows')); returnTextColor(document.getElementById('flagNarrowsText')); returnColor(document.getElementById('flagNarrows2'))}}  id="flagNarrows2" points="684,57 580,57 580,98 684,98"/>
                <polygon onMouseOver={() => {setScreens('Flag Power Up'); turnGreen(document.getElementById('flagPowerUpNarrows')); textGreen(document.getElementById('flagPowerUpNarrowsText')); turnGreen(document.getElementById('flagPowerUpNarrows2')); turnGreen(document.getElementById('flagPowerUpNarrows3')); turnGreen(document.getElementById('flagPowerUpNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('flagPowerUpNarrows')); returnTextColor(document.getElementById('flagPowerUpNarrowsText')); returnColor(document.getElementById('flagPowerUpNarrows2')); returnColor(document.getElementById('flagPowerUpNarrows3')); returnColor(document.getElementById('flagPowerUpNarrows4'))}}  id="flagPowerUpNarrows" points="217,48 239,48 265,75 265,110 235,110 234,109 234,89 224,77 217,77"/>
                <polygon onMouseOver={() => {setScreens('Flag Power Up'); turnGreen(document.getElementById('flagPowerUpNarrows')); textGreen(document.getElementById('flagPowerUpNarrowsText')); turnGreen(document.getElementById('flagPowerUpNarrows2')); turnGreen(document.getElementById('flagPowerUpNarrows3')); turnGreen(document.getElementById('flagPowerUpNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('flagPowerUpNarrows')); returnTextColor(document.getElementById('flagPowerUpNarrowsText')); returnColor(document.getElementById('flagPowerUpNarrows2')); returnColor(document.getElementById('flagPowerUpNarrows3')); returnColor(document.getElementById('flagPowerUpNarrows4'))}}  id="flagPowerUpNarrows2" points="248,400 248,364 221,337 199,337 199,365 205,365 216,378 216,388 218,388 218,400"/>
                <polygon onMouseOver={() => {setScreens('Flag Power Up'); turnGreen(document.getElementById('flagPowerUpNarrows')); textGreen(document.getElementById('flagPowerUpNarrowsText')); turnGreen(document.getElementById('flagPowerUpNarrows2')); turnGreen(document.getElementById('flagPowerUpNarrows3')); turnGreen(document.getElementById('flagPowerUpNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('flagPowerUpNarrows')); returnTextColor(document.getElementById('flagPowerUpNarrowsText')); returnColor(document.getElementById('flagPowerUpNarrows2')); returnColor(document.getElementById('flagPowerUpNarrows3')); returnColor(document.getElementById('flagPowerUpNarrows4'))}}  id="flagPowerUpNarrows3" points="530,48 508,48 482,74 482,110 513,110 513,89 523,77 530,77"/>
                <polygon onMouseOver={() => {setScreens('Flag Power Up'); turnGreen(document.getElementById('flagPowerUpNarrows')); textGreen(document.getElementById('flagPowerUpNarrowsText')); turnGreen(document.getElementById('flagPowerUpNarrows2')); turnGreen(document.getElementById('flagPowerUpNarrows3')); turnGreen(document.getElementById('flagPowerUpNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('flagPowerUpNarrows')); returnTextColor(document.getElementById('flagPowerUpNarrowsText')); returnColor(document.getElementById('flagPowerUpNarrows2')); returnColor(document.getElementById('flagPowerUpNarrows3')); returnColor(document.getElementById('flagPowerUpNarrows4'))}}  id="flagPowerUpNarrows4" points="549,337 526,337 499,364 499,412 529,412 529,407 526,407 526,400 529,400 529,388 531,388 531,378 542,365 549,365"/>
                <polygon onMouseOver={() => {setScreens('Flag Door'); turnGreen(document.getElementById('flagDoorNarrows')); textGreen(document.getElementById('flagDoorNarrowsText')); turnGreen(document.getElementById('flagDoorNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagDoorNarrows')); returnTextColor(document.getElementById('flagDoorNarrowsText')); returnColor(document.getElementById('flagDoorNarrows2'))}}  id="flagDoorNarrows" points="190,389 206,389 206,401 211,401 211,406 206,406 206,418 190,418 190,409 193,409 193,397 190,397"/>
                <polygon onMouseOver={() => {setScreens('Flag Door'); turnGreen(document.getElementById('flagDoorNarrows')); textGreen(document.getElementById('flagDoorNarrowsText')); turnGreen(document.getElementById('flagDoorNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagDoorNarrows')); returnTextColor(document.getElementById('flagDoorNarrowsText')); returnColor(document.getElementById('flagDoorNarrows2'))}}  id="flagDoorNarrows2" points="557,389 557,397 553,397 553,409 557,409 557,418 541,418 541,406 536,406 536,401 541,401 541,389"/>
                <polygon onMouseOver={() => {setScreens('Flag Lobby'); turnGreen(document.getElementById('flagLobbyNarrows')); textGreen(document.getElementById('flagLobbyNarrowsText')); turnGreen(document.getElementById('flagLobbyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagLobbyNarrows')); returnTextColor(document.getElementById('flagLobbyNarrowsText')); returnColor(document.getElementById('flagLobbyNarrows2'))}}  id="flagLobbyNarrows" points="81,103 99,103 99,125 81,125"/>
                <polygon onMouseOver={() => {setScreens('Flag Lobby'); turnGreen(document.getElementById('flagLobbyNarrows')); textGreen(document.getElementById('flagLobbyNarrowsText')); turnGreen(document.getElementById('flagLobbyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagLobbyNarrows')); returnTextColor(document.getElementById('flagLobbyNarrowsText')); returnColor(document.getElementById('flagLobbyNarrows2'))}}  id="flagLobbyNarrows2" points="665,103 648,103 648,125 665,125"/>
                <polygon onMouseOver={() => {setScreens('Flag Box'); turnGreen(document.getElementById('flagBoxNarrows')); textGreen(document.getElementById('flagBoxNarrowsText')); turnGreen(document.getElementById('flagBoxNarrows2')); turnGreen(document.getElementById('flagBoxNarrows3')); turnGreen(document.getElementById('flagBoxNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('flagBoxNarrows')); returnTextColor(document.getElementById('flagBoxNarrowsText')); returnColor(document.getElementById('flagBoxNarrows2')); returnColor(document.getElementById('flagBoxNarrows3')); returnColor(document.getElementById('flagBoxNarrows4'))}}  id="flagBoxNarrows" points="203,55 167,55 167,79 203,79"/>
                <polygon onMouseOver={() => {setScreens('Flag Box'); turnGreen(document.getElementById('flagBoxNarrows')); textGreen(document.getElementById('flagBoxNarrowsText')); turnGreen(document.getElementById('flagBoxNarrows2')); turnGreen(document.getElementById('flagBoxNarrows3')); turnGreen(document.getElementById('flagBoxNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('flagBoxNarrows')); returnTextColor(document.getElementById('flagBoxNarrowsText')); returnColor(document.getElementById('flagBoxNarrows2')); returnColor(document.getElementById('flagBoxNarrows3')); returnColor(document.getElementById('flagBoxNarrows4'))}}  id="flagBoxNarrows2" points="147,345 183,345 183,369 147,369"/>
                <polygon onMouseOver={() => {setScreens('Flag Box'); turnGreen(document.getElementById('flagBoxNarrows')); textGreen(document.getElementById('flagBoxNarrowsText')); turnGreen(document.getElementById('flagBoxNarrows2')); turnGreen(document.getElementById('flagBoxNarrows3')); turnGreen(document.getElementById('flagBoxNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('flagBoxNarrows')); returnTextColor(document.getElementById('flagBoxNarrowsText')); returnColor(document.getElementById('flagBoxNarrows2')); returnColor(document.getElementById('flagBoxNarrows3')); returnColor(document.getElementById('flagBoxNarrows4'))}}  id="flagBoxNarrows3" points="546,56 582,56 582,80 546,80"/>
                <polygon onMouseOver={() => {setScreens('Flag Box'); turnGreen(document.getElementById('flagBoxNarrows')); textGreen(document.getElementById('flagBoxNarrowsText')); turnGreen(document.getElementById('flagBoxNarrows2')); turnGreen(document.getElementById('flagBoxNarrows3')); turnGreen(document.getElementById('flagBoxNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('flagBoxNarrows')); returnTextColor(document.getElementById('flagBoxNarrowsText')); returnColor(document.getElementById('flagBoxNarrows2')); returnColor(document.getElementById('flagBoxNarrows3')); returnColor(document.getElementById('flagBoxNarrows4'))}}  id="flagBoxNarrows4" points="599,345 563,345 563,369 599,369"/>
                <polygon onMouseOver={() => {setScreens('Flag Shockwave'); turnGreen(document.getElementById('flagShockwaveNarrows')); textGreen(document.getElementById('flagShockwaveNarrowsText')); turnGreen(document.getElementById('flagShockwaveNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagShockwaveNarrows')); returnTextColor(document.getElementById('flagShockwaveNarrowsText')); returnColor(document.getElementById('flagShockwaveNarrows2'))}}  id="flagShockwaveNarrows" points="304,110 250,110 250,115 304,115"/>
                <polygon onMouseOver={() => {setScreens('Flag Shockwave'); turnGreen(document.getElementById('flagShockwaveNarrows')); textGreen(document.getElementById('flagShockwaveNarrowsText')); turnGreen(document.getElementById('flagShockwaveNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagShockwaveNarrows')); returnTextColor(document.getElementById('flagShockwaveNarrowsText')); returnColor(document.getElementById('flagShockwaveNarrows2'))}}  id="flagShockwaveNarrows2" points="442,110 496,110 496,115 442,115"/>
                <polygon onMouseOver={() => {setScreens('Flag Sneaky'); turnGreen(document.getElementById('flagSneakyNarrows')); textGreen(document.getElementById('flagSneakyNarrowsText')); turnGreen(document.getElementById('flagSneakyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagSneakyNarrows')); returnTextColor(document.getElementById('flagSneakyNarrowsText')); returnColor(document.getElementById('flagSneakyNarrows2'))}}  id="flagSneakyNarrows" points="200,99 166,99 166,104 200,104"/>
                <polygon onMouseOver={() => {setScreens('Flag Sneaky'); turnGreen(document.getElementById('flagSneakyNarrows')); textGreen(document.getElementById('flagSneakyNarrowsText')); turnGreen(document.getElementById('flagSneakyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('flagSneakyNarrows')); returnTextColor(document.getElementById('flagSneakyNarrowsText')); returnColor(document.getElementById('flagSneakyNarrows2'))}}  id="flagSneakyNarrows2" points="547,104 547,99 581,99 581,104"/>
                <polygon onMouseOver={() => {setScreens('L0'); turnGreen(document.getElementById('l0Narrows')); textGreen(document.getElementById('l0NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('l0Narrows')); returnTextColor(document.getElementById('l0NarrowsText'))}}  id="l0Narrows" points="526,187 503,187 499,191 499,203 511,203 511,199 526,199"/>
                <polygon onMouseOver={() => {setScreens('L1'); turnGreen(document.getElementById('l1Narrows')); textGreen(document.getElementById('l1NarrowsText')); turnGreen(document.getElementById('l1Narrows2'))}} onMouseOut={() => {returnColor(document.getElementById('l1Narrows')); returnTextColor(document.getElementById('l1NarrowsText')); returnColor(document.getElementById('l1Narrows2'))}}  id="l1Narrows" points="481,189 480,188 393,188 393,203 480,203 481,202"/>
                <polygon onMouseOver={() => {setScreens('L1'); turnGreen(document.getElementById('l1Narrows')); textGreen(document.getElementById('l1NarrowsText')); turnGreen(document.getElementById('l1Narrows2'))}} onMouseOut={() => {returnColor(document.getElementById('l1Narrows')); returnTextColor(document.getElementById('l1NarrowsText')); returnColor(document.getElementById('l1Narrows2'))}}  id="l1Narrows2" points="412,485 412,498 482,498 482,485"/>
                <polygon onMouseOver={() => {setScreens('L2'); turnGreen(document.getElementById('l2Narrows')); textGreen(document.getElementById('l2NarrowsText')); turnGreen(document.getElementById('l2Narrows2'))}} onMouseOut={() => {returnColor(document.getElementById('l2Narrows')); returnTextColor(document.getElementById('l2NarrowsText')); returnColor(document.getElementById('l2Narrows2'))}}  id="l2Narrows" points="266,189 267,188 352,188 352,190 353,190 353,202 352,203 266,203"/>
                <polygon onMouseOver={() => {setScreens('L2'); turnGreen(document.getElementById('l2Narrows')); textGreen(document.getElementById('l2NarrowsText')); turnGreen(document.getElementById('l2Narrows2'))}} onMouseOut={() => {returnColor(document.getElementById('l2Narrows')); returnTextColor(document.getElementById('l2NarrowsText')); returnColor(document.getElementById('l2Narrows2'))}}  id="l2Narrows2" points="334,485 265,485 265,498 334,498"/>
                <polygon onMouseOver={() => {setScreens('L3'); turnGreen(document.getElementById('l3Narrows')); textGreen(document.getElementById('l3NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('l3Narrows')); returnTextColor(document.getElementById('l3NarrowsText'))}}  id="l3Narrows" points="220,187 243,187 247,191 247,203 235,203 235,199 220,199"/>
                <polygon onMouseOver={() => {setScreens('L4'); turnGreen(document.getElementById('l4Narrows')); textGreen(document.getElementById('l4NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('l4Narrows')); returnTextColor(document.getElementById('l4NarrowsText'))}}  id="l4Narrows" points="163,194 163,198 124,198 124,194"/>
                <polygon onMouseOver={() => {setScreens('Left Attic'); turnGreen(document.getElementById('leftAtticNarrows')); textGreen(document.getElementById('leftAtticNarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('leftAtticNarrows')); returnTextColor(document.getElementById('leftAtticNarrowsText'))}}  id="leftAtticNarrows" points="623,194 623,198 584,198 584,194"/>
                <polygon onMouseOver={() => {setScreens('Left Box'); turnGreen(document.getElementById('leftBoxNarrows')); textGreen(document.getElementById('leftBoxNarrowsText')); turnGreen(document.getElementById('leftBoxNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('leftBoxNarrows')); returnTextColor(document.getElementById('leftBoxNarrowsText')); returnColor(document.getElementById('leftBoxNarrows2'))}}  id="leftBoxNarrows" points="169,187 188,187 188,199 169,199"/>
                <polygon onMouseOver={() => {setScreens('Left Box'); turnGreen(document.getElementById('leftBoxNarrows')); textGreen(document.getElementById('leftBoxNarrowsText')); turnGreen(document.getElementById('leftBoxNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('leftBoxNarrows')); returnTextColor(document.getElementById('leftBoxNarrowsText'));  returnColor(document.getElementById('leftBoxNarrows2'))}}  id="leftBoxNarrows2" points="577,187 558,187 558,199 577,199"/>
                <polygon onMouseOver={() => {setScreens('Left Shoulder'); turnGreen(document.getElementById('leftShoulderNarrows')); textGreen(document.getElementById('leftShoulderNarrowsText')); turnGreen(document.getElementById('leftShoulderNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('leftShoulderNarrows')); returnTextColor(document.getElementById('leftShoulderNarrowsText')); returnColor(document.getElementById('leftShoulderNarrows2'))}}  id="leftShoulderNarrows" points="286,467 274,467 274,479 286,479"/>
                <polygon onMouseOver={() => {setScreens('Left Shoulder'); turnGreen(document.getElementById('leftShoulderNarrows')); textGreen(document.getElementById('leftShoulderNarrowsText')); turnGreen(document.getElementById('leftShoulderNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('leftShoulderNarrows')); returnTextColor(document.getElementById('leftShoulderNarrowsText')); returnColor(document.getElementById('leftShoulderNarrows2'))}}  id="leftShoulderNarrows2" points="473,467 461,467 461,479 473,479"/>
                <polygon onMouseOver={() => {setScreens('Lobby'); turnGreen(document.getElementById('lobbyNarrows')); textGreen(document.getElementById('lobbyNarrowsText')); turnGreen(document.getElementById('lobbyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('lobbyNarrows')); returnTextColor(document.getElementById('lobbyNarrowsText')); returnColor(document.getElementById('lobbyNarrows2'))}}  id="lobbyNarrows" points="99,126 64,126 64,135 63,135 63,139 59,143 59,145 55,145 55,175 58,175 63,180 63,194 99,194"/>
                <polygon onMouseOver={() => {setScreens('Lobby'); turnGreen(document.getElementById('lobbyNarrows')); textGreen(document.getElementById('lobbyNarrowsText')); turnGreen(document.getElementById('lobbyNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('lobbyNarrows')); returnTextColor(document.getElementById('lobbyNarrowsText')); returnColor(document.getElementById('lobbyNarrows2'))}}  id="lobbyNarrows2" points="648,126 683,126 683,138 689,145 692,145 692,175 690,175 683,182 683,194 648,194"/>
                <polygon onMouseOver={() => {setScreens('Main Cannon'); turnGreen(document.getElementById('mainCannonNarrows')); textGreen(document.getElementById('mainCannonNarrowsText')); turnGreen(document.getElementById('mainCannonNarrows2')); turnGreen(document.getElementById('mainCannonNarrows3')); turnGreen(document.getElementById('mainCannonNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('mainCannonNarrows')); returnTextColor(document.getElementById('mainCannonNarrowsText')); returnColor(document.getElementById('mainCannonNarrows2')); returnColor(document.getElementById('mainCannonNarrows3')); returnColor(document.getElementById('mainCannonNarrows4'))}}  id="mainCannonNarrows" points="164,239 205,239 205,262 164,262"/>
                <polygon onMouseOver={() => {setScreens('Main Cannon'); turnGreen(document.getElementById('mainCannonNarrows')); textGreen(document.getElementById('mainCannonNarrowsText')); turnGreen(document.getElementById('mainCannonNarrows2')); turnGreen(document.getElementById('mainCannonNarrows3')); turnGreen(document.getElementById('mainCannonNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('mainCannonNarrows')); returnTextColor(document.getElementById('mainCannonNarrowsText')); returnColor(document.getElementById('mainCannonNarrows2')); returnColor(document.getElementById('mainCannonNarrows3')); returnColor(document.getElementById('mainCannonNarrows4'))}}  id="mainCannonNarrows2" points="147,530 188,530 188,553 147,553"/>
                <polygon onMouseOver={() => {setScreens('Main Cannon'); turnGreen(document.getElementById('mainCannonNarrows')); textGreen(document.getElementById('mainCannonNarrowsText')); turnGreen(document.getElementById('mainCannonNarrows2')); turnGreen(document.getElementById('mainCannonNarrows3')); turnGreen(document.getElementById('mainCannonNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('mainCannonNarrows')); returnTextColor(document.getElementById('mainCannonNarrowsText')); returnColor(document.getElementById('mainCannonNarrows2')); returnColor(document.getElementById('mainCannonNarrows3')); returnColor(document.getElementById('mainCannonNarrows4'))}}  id="mainCannonNarrows3" points="583,240 545,240 545,263 583,263"/>
                <polygon onMouseOver={() => {setScreens('Main Cannon'); turnGreen(document.getElementById('mainCannonNarrows')); textGreen(document.getElementById('mainCannonNarrowsText')); turnGreen(document.getElementById('mainCannonNarrows2')); turnGreen(document.getElementById('mainCannonNarrows3')); turnGreen(document.getElementById('mainCannonNarrows4'))}} onMouseOut={() => {returnColor(document.getElementById('mainCannonNarrows')); returnTextColor(document.getElementById('mainCannonNarrowsText')); returnColor(document.getElementById('mainCannonNarrows2')); returnColor(document.getElementById('mainCannonNarrows3')); returnColor(document.getElementById('mainCannonNarrows4'))}}  id="mainCannonNarrows4" points="599,529 558,529 558,552 599,552"/>
                <polygon onMouseOver={() => {setScreens('Mauler'); turnGreen(document.getElementById('mauler50Narrows')); textGreen(document.getElementById('mauler50NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('mauler50Narrows')); returnTextColor(document.getElementById('mauler50NarrowsText'))}}  id="mauler50Narrows" points="354,134 392,134 392,185 354,185"/>
                <polygon onMouseOver={() => {setScreens('Mini Mohawk'); turnGreen(document.getElementById('miniMohawkNarrows')); textGreen(document.getElementById('miniMohawkNarrowsText')); turnGreen(document.getElementById('miniMohawkNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('miniMohawkNarrows')); returnTextColor(document.getElementById('miniMohawkNarrowsText')); returnColor(document.getElementById('miniMohawkNarrows2'))}}  id="miniMohawkNarrows" points="133,153 152,153 152,156 162,156 162,153 170,153 170,155 175,155 175,164 170,164 170,165 162,165 162,163 152,163 152,165 133,165"/>
                <polygon onMouseOver={() => {setScreens('Mini Mohawk'); turnGreen(document.getElementById('miniMohawkNarrows')); textGreen(document.getElementById('miniMohawkNarrowsText')); turnGreen(document.getElementById('miniMohawkNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('miniMohawkNarrows')); returnTextColor(document.getElementById('miniMohawkNarrowsText')); returnColor(document.getElementById('miniMohawkNarrows2'))}}  id="miniMohawkNarrows2" points="614,153 595,153 595,156 585,156 585,153 577,153 577,155 572,155 572,164 577,164 577,166 585,166 585,163 595,163 595,166 614,166"/>
                <polygon onMouseOver={() => {setScreens('Mohawk'); turnGreen(document.getElementById('mohawkNarrows')); textGreen(document.getElementById('mohawkNarrowsText')); turnGreen(document.getElementById('mohawkNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('mohawkNarrows')); returnTextColor(document.getElementById('mohawkNarrowsText')); returnColor(document.getElementById('mohawkNarrows2'))}}  id="mohawkNarrows" points="320,155 313,155 313,153 305,153 305,156 303,156 303,153 288,153 286,155 286,164 288,166 303,166 303,163 305,163 305,166 313,166 313,164 320,164"/>
                <polygon onMouseOver={() => {setScreens('Mohawk'); turnGreen(document.getElementById('mohawkNarrows')); textGreen(document.getElementById('mohawkNarrowsText')); turnGreen(document.getElementById('mohawkNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('mohawkNarrows')); returnTextColor(document.getElementById('mohawkNarrowsText')); returnColor(document.getElementById('mohawkNarrows2'))}}  id="mohawkNarrows2" points="427,155 434,155 434,153 441,153 441,156 444,156 444,153 459,153 461,155 461,164 459,166 444,166 444,163 441,163 441,166 434,166 434,164 427,164"/>
                <polygon onMouseOver={() => {setScreens('Power Up'); turnGreen(document.getElementById('powerUpNarrows')); textGreen(document.getElementById('powerUpNarrowsText')); turnGreen(document.getElementById('powerUpNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('powerUpNarrows')); returnTextColor(document.getElementById('powerUpNarrowsText')); returnColor(document.getElementById('powerUpNarrows2'))}}  id="powerUpNarrows" points="221,497 248,497 248,401 221,401 221,407 218,407 218,490 221,490"/>
                <polygon onMouseOver={() => {setScreens('Power Up'); turnGreen(document.getElementById('powerUpNarrows')); textGreen(document.getElementById('powerUpNarrowsText')); turnGreen(document.getElementById('powerUpNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('powerUpNarrows')); returnTextColor(document.getElementById('powerUpNarrowsText')); returnColor(document.getElementById('powerUpNarrows2'))}}  id="powerUpNarrows2" points="526,497 526,490 529,490 529,407 526,407 526,401 499,401 499,497"/>
                <polygon onMouseOver={() => {setScreens('R0'); turnGreen(document.getElementById('r0Narrows')); textGreen(document.getElementById('r0NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('r0Narrows')); returnTextColor(document.getElementById('r0NarrowsText'))}}  id="r0Narrows" points="526,120 511,120 511,116 499,116 499,129 503,133 526,133"/>
                <polygon onMouseOver={() => {setScreens('R1'); turnGreen(document.getElementById('r1Narrows')); textGreen(document.getElementById('r1NarrowsText')); turnGreen(document.getElementById('r1Narrows2'))}} onMouseOut={() => {returnColor(document.getElementById('r1Narrows')); returnTextColor(document.getElementById('r1NarrowsText')); returnColor(document.getElementById('r1Narrows2'))}}  id="r1Narrows" points="393,116 480,116 481,117 481,130 480,131 393,131"/>
                <polygon onMouseOver={() => {setScreens('R1'); turnGreen(document.getElementById('r1Narrows')); textGreen(document.getElementById('r1NarrowsText')); turnGreen(document.getElementById('r1Narrows2'))}} onMouseOut={() => {returnColor(document.getElementById('r1Narrows')); returnTextColor(document.getElementById('r1NarrowsText')); returnColor(document.getElementById('r1Narrows2'))}}  id="r1Narrows2" points="480,399 481,400 481,412 480,413 413,413 413,399"/>
                <polygon onMouseOver={() => {setScreens('R2'); turnGreen(document.getElementById('r2Narrows')); textGreen(document.getElementById('r2NarrowsText')); turnGreen(document.getElementById('r2Narrows2'))}} onMouseOut={() => {returnColor(document.getElementById('r2Narrows')); returnTextColor(document.getElementById('r2NarrowsText')); returnColor(document.getElementById('r2Narrows2'))}}  id="r2Narrows" points="266,117 267,116 352,116 353,117 353,130 352,131 267,131 266,130"/>
                <polygon onMouseOver={() => {setScreens('R2'); turnGreen(document.getElementById('r2Narrows')); textGreen(document.getElementById('r2NarrowsText')); turnGreen(document.getElementById('r2Narrows2'))}} onMouseOut={() => {returnColor(document.getElementById('r2Narrows')); returnTextColor(document.getElementById('r2NarrowsText')); returnColor(document.getElementById('r2Narrows2'))}}  id="r2Narrows2" points="266,399 266,412 336,412 336,399"/>
                <polygon onMouseOver={() => {setScreens('R3'); turnGreen(document.getElementById('r3Narrows')); textGreen(document.getElementById('r3NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('r3Narrows')); returnTextColor(document.getElementById('r3NarrowsText'))}}  id="r3Narrows" points="247,116 244,116 244,115 236,115 235,116 235,120 225,120 225,121 223,121 223,122 220,122 220,133 243,133 247,129"/>
                <polygon onMouseOver={() => {setScreens('R4'); turnGreen(document.getElementById('r4Narrows')); textGreen(document.getElementById('r4NarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('r4Narrows')); returnTextColor(document.getElementById('r4NarrowsText'))}}  id="r4Narrows" points="163,120 163,124 124,124 124,120"/>
                <polygon onMouseOver={() => {setScreens('Right Attic'); turnGreen(document.getElementById('rightAtticNarrows')); textGreen(document.getElementById('rightAtticNarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('rightAtticNarrows')); returnTextColor(document.getElementById('rightAtticNarrowsText'))}}  id="rightAtticNarrows" points="623,120 623,125 584,125 584,120"/>
                <polygon onMouseOver={() => {setScreens('Right Box'); turnGreen(document.getElementById('rightBoxNarrows')); textGreen(document.getElementById('rightBoxNarrowsText')); turnGreen(document.getElementById('rightBoxNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('rightBoxNarrows')); returnTextColor(document.getElementById('rightBoxNarrowsText')); returnColor(document.getElementById('rightBoxNarrows2'))}}  id="rightBoxNarrows" points="188,120 169,120 169,132 188,132"/>
                <polygon onMouseOver={() => {setScreens('Right Box'); turnGreen(document.getElementById('rightBoxNarrows')); textGreen(document.getElementById('rightBoxNarrowsText')); turnGreen(document.getElementById('rightBoxNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('rightBoxNarrows')); returnTextColor(document.getElementById('rightBoxNarrowsText')); returnColor(document.getElementById('rightBoxNarrows2'))}}  id="rightBoxNarrows2" points="577,120 558,120 558,132 577,132"/>
                <polygon onMouseOver={() => {setScreens('Right Shoulder'); turnGreen(document.getElementById('rightShoulderNarrows')); textGreen(document.getElementById('rightShoulderNarrowsText')); turnGreen(document.getElementById('rightShoulderNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('rightShoulderNarrows')); returnTextColor(document.getElementById('rightShoulderNarrowsText')); returnColor(document.getElementById('rightShoulderNarrows2'))}}  id="rightShoulderNarrows" points="274,418 286,418 286,429 274,429"/>
                <polygon onMouseOver={() => {setScreens('Right Shoulder'); turnGreen(document.getElementById('rightShoulderNarrows')); textGreen(document.getElementById('rightShoulderNarrowsText')); turnGreen(document.getElementById('rightShoulderNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('rightShoulderNarrows')); returnTextColor(document.getElementById('rightShoulderNarrowsText')); returnColor(document.getElementById('rightShoulderNarrows2'))}}  id="rightShoulderNarrows2" points="473,419 461,419 461,430 473,430"/>
                <polygon onMouseOver={() => {setScreens('Rockets'); turnGreen(document.getElementById('rocketsNarrows')); textGreen(document.getElementById('rocketsNarrowsText'))}} onMouseOut={() => {returnColor(document.getElementById('rocketsNarrows')); returnTextColor(document.getElementById('rocketsNarrowsText'))}}  id="rocketsNarrows" points="414,439 333,439 333,459 414,459"/>
                <polygon onMouseOver={() => {setScreens('Stage'); turnGreen(document.getElementById('stageNarrows')); textGreen(document.getElementById('stageNarrowsText')); turnGreen(document.getElementById('stageNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('stageNarrows')); returnTextColor(document.getElementById('stageNarrowsText')); returnColor(document.getElementById('stageNarrows2'))}}  id="stageNarrows" points="52,145 45,145 39,139 39,126 19,126 19,186 39,186 40,185 40,180 45,175 52,175"/>
                <polygon onMouseOver={() => {setScreens('Stage'); turnGreen(document.getElementById('stageNarrows')); textGreen(document.getElementById('stageNarrowsText')); turnGreen(document.getElementById('stageNarrows2'))}} onMouseOut={() => {returnColor(document.getElementById('stageNarrows')); returnTextColor(document.getElementById('stageNarrowsText')); returnColor(document.getElementById('stageNarrows2'))}}  id="stageNarrows2" points="727,126 708,126 708,139 702,144 695,144 695,175 702,175 708,181 708,186 727,186"/>
            </svg>
            <Screenshot 
                Map={'Narrows'}
                Screenshot={screens}
            />
        </div>
    );
}

export default Narrows;