import React, {useState} from 'react';
import Screenshot from '../ScreenShots';

function Guardian({turnGreen,returnColor,textGreen,returnTextColor}) {
    const [screens,setScreens] = useState('');

        return(
            <div className="guardianFullGrid">
                <h1 className="mapTitleGuardian">Guardian</h1>
                <div className="calloutsList" id="guardianCallouts">
                    <p onMouseOver={() => {turnGreen(document.getElementById('barrelsGuardian')); textGreen(document.getElementById('barrelsGuardianText')); setScreens('Barrels')}} onMouseOut={() => {returnColor(document.getElementById('barrelsGuardian')); returnTextColor(document.getElementById('barrelsGuardianText'))}} id="barrelsGuardianText">Barrels</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('blueEntranceGuardian')); textGreen(document.getElementById('blueEntranceGuardianText')); setScreens('Blue Entrance')}} onMouseOut={() => {returnColor(document.getElementById('blueEntranceGuardian')); returnTextColor(document.getElementById('blueEntranceGuardianText'))}} id="blueEntranceGuardianText">Blue Entrance</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('blueLightsGuardian')); textGreen(document.getElementById('blueLightsGuardianText')); setScreens('Blue Lights')}} onMouseOut={() => {returnColor(document.getElementById('blueLightsGuardian')); returnTextColor(document.getElementById('blueLightsGuardianText'))}} id="blueLightsGuardianText">Blue Lights</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('blueRampGuardian')); textGreen(document.getElementById('blueRampGuardianText')); turnGreen(document.getElementById('blueRampGuardian2')); setScreens('Blue Ramp')}} onMouseOut={() => {returnColor(document.getElementById('blueRampGuardian')); returnColor(document.getElementById('blueRampGuardian2')); returnTextColor(document.getElementById('blueRampGuardianText'))}} id="blueRampGuardianText">Blue Ramp</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('blueWindowGuardian')); textGreen(document.getElementById('blueWindowGuardianText')); setScreens('Blue Window')}} onMouseOut={() => {returnColor(document.getElementById('blueWindowGuardian')); returnTextColor(document.getElementById('blueWindowGuardianText'))}} id="blueWindowGuardianText">Blue Window</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('bottomGoldGuardian')); textGreen(document.getElementById('bottomGoldGuardianText')); setScreens('Bottom Gold')}} onMouseOut={() => {returnColor(document.getElementById('bottomGoldGuardian')); returnTextColor(document.getElementById('bottomGoldGuardianText'))}} id="bottomGoldGuardianText">Bottom Gold</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('bottomGreenGuardian')); textGreen(document.getElementById('bottomGreenGuardianText')); setScreens('Bottom Green')}} onMouseOut={() => {returnColor(document.getElementById('bottomGreenGuardian')); returnTextColor(document.getElementById('bottomGreenGuardianText'))}} id="bottomGreenGuardianText">Bottom Green</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('camoGuardian')); textGreen(document.getElementById('camoGuardianText')); setScreens('Camo')}} onMouseOut={() => {returnColor(document.getElementById('camoGuardian')); returnTextColor(document.getElementById('camoGuardianText'))}} id="camoGuardianText">Camo</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('elbowGuardian')); textGreen(document.getElementById('elbowGuardianText')); turnGreen(document.getElementById('elbowGuardian2')); setScreens('Elbow')}} onMouseOut={() => {returnColor(document.getElementById('elbowGuardian')); returnTextColor(document.getElementById('elbowGuardianText')); returnColor(document.getElementById('elbowGuardian2'))}} id="elbowGuardianText">Elbow</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('frontBlueGuardian')); textGreen(document.getElementById('frontBlueGuardianText')); setScreens('Front Blue')}} onMouseOut={() => {returnColor(document.getElementById('frontBlueGuardian')); returnTextColor(document.getElementById('frontBlueGuardianText'))}} id="frontBlueGuardianText">Front Blue</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('goldLightsGuardian')); textGreen(document.getElementById('goldLightsGuardianText')); setScreens('Gold Lights')}} onMouseOut={() => {returnColor(document.getElementById('goldLightsGuardian')); returnTextColor(document.getElementById('goldLightsGuardianText'))}} id="goldLightsGuardianText">Gold Lights</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('goldWindowGuardian')); textGreen(document.getElementById('goldWindowGuardianText')); setScreens('Gold Window')}} onMouseOut={() => {returnColor(document.getElementById('goldWindowGuardian')); returnTextColor(document.getElementById('goldWindowGuardianText'))}} id="goldWindowGuardianText">Gold Window</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('greenLightsGuardian')); textGreen(document.getElementById('greenLightsGuardianText')); setScreens('Green Lights')}} onMouseOut={() => {returnColor(document.getElementById('greenLightsGuardian')); returnTextColor(document.getElementById('greenLightsGuardianText'))}} id="greenLightsGuardianText">Green Lights</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('shortJumpGuardian')); textGreen(document.getElementById('shortJumpGuardianText')); setScreens('Short Jump')}} onMouseOut={() => {returnColor(document.getElementById('shortJumpGuardian')); returnTextColor(document.getElementById('shortJumpGuardianText'))}} id="shortJumpGuardianText">Short Jump</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('shotgunRoomGuardian')); textGreen(document.getElementById('shotgunRoomGuardianText')); setScreens('Shotgun Room')}} onMouseOut={() => {returnColor(document.getElementById('shotgunRoomGuardian')); returnTextColor(document.getElementById('shotgunRoomGuardianText'))}} id="shotgunRoomGuardianText">Shotgun Room</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('snipe1Guardian')); textGreen(document.getElementById('snipe1GuardianText')); setScreens('Snipe 1')}} onMouseOut={() => {returnColor(document.getElementById('snipe1Guardian')); returnTextColor(document.getElementById('snipe1GuardianText'))}} id="snipe1GuardianText">Snipe1</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('snipe2Guardian')); textGreen(document.getElementById('snipe2GuardianText')); setScreens('Snipe 2')}} onMouseOut={() => {returnColor(document.getElementById('snipe2Guardian')); returnTextColor(document.getElementById('snipe2GuardianText'))}} id="snipe2GuardianText">Snipe2</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('snipe3Guardian')); textGreen(document.getElementById('snipe3GuardianText')); setScreens('Snipe 3')}} onMouseOut={() => {returnColor(document.getElementById('snipe3Guardian')); returnTextColor(document.getElementById('snipe3GuardianText'))}} id="snipe3GuardianText">Snipe3</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('snipeLiftGuardian')); textGreen(document.getElementById('snipeLiftGuardianText')); setScreens('Snipe Lift')}} onMouseOut={() => {returnColor(document.getElementById('snipeLiftGuardian')); returnTextColor(document.getElementById('snipeLiftGuardianText'))}} id="snipeLiftGuardianText">Snipe Lift</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('snipeLightsGuardian')); textGreen(document.getElementById('snipeLightsGuardianText')); setScreens('Snipe Lights')}} onMouseOut={() => {returnColor(document.getElementById('snipeLightsGuardian')); returnTextColor(document.getElementById('snipeLightsGuardianText'))}} id="snipeLightsGuardianText">Snipe Lights</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('snipeRampGuardian')); textGreen(document.getElementById('snipeRampGuardianText')); turnGreen(document.getElementById('snipeRampGuardian2')); setScreens('Snipe Ramp')}} onMouseOut={() => {returnColor(document.getElementById('snipeRampGuardian')); returnTextColor(document.getElementById('snipeRampGuardianText')); returnColor(document.getElementById('snipeRampGuardian2'))}} id="snipeRampGuardianText">Snipe Ramp</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('stumpGuardian')); textGreen(document.getElementById('stumpGuardianText')); setScreens('Stump')}} onMouseOut={() => {returnColor(document.getElementById('stumpGuardian')); returnTextColor(document.getElementById('stumpGuardianText'))}} id="stumpGuardianText">Stump</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('topBlueGuardian')); textGreen(document.getElementById('topBlueGuardianText')); setScreens('Top Blue')}} onMouseOut={() => {returnColor(document.getElementById('topBlueGuardian')); returnTextColor(document.getElementById('topBlueGuardianText'))}} id="topBlueGuardianText">Top Blue</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('topGoldGuardian')); textGreen(document.getElementById('topGoldGuardianText')); setScreens('Top Gold')}} onMouseOut={() => {returnColor(document.getElementById('topGoldGuardian')); returnTextColor(document.getElementById('topGoldGuardianText'))}} id="topGoldGuardianText">Top Gold</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('topGreenGuardian')); textGreen(document.getElementById('topGreenGuardianText')); setScreens('Top Green')}} onMouseOut={() => {returnColor(document.getElementById('topGreenGuardian')); returnTextColor(document.getElementById('topGreenGuardianText'))}} id="topGreenGuardianText">Top Green</p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('topMidGuardian')); textGreen(document.getElementById('topMidGuardianText')); setScreens('Top Mid')}} onMouseOut={() => {returnColor(document.getElementById('topMidGuardian')); returnTextColor(document.getElementById('topMidGuardianText'))}} id="topMidGuardianText">Top Mid </p>
                    <p onMouseOver={() => {turnGreen(document.getElementById('underGlassGuardian')); textGreen(document.getElementById('underGlassGuardianText')); setScreens('Under Glass')}} onMouseOut={() => {returnColor(document.getElementById('underGlassGuardian')); returnTextColor(document.getElementById('underGlassGuardianText'))}} id="underGlassGuardianText">Under Glass</p>
                </div>
                <svg id="guardianMap" height="625" width="750">
                    <circle onMouseOver={() => {setScreens('Top Mid'); turnGreen(document.getElementById('topMidGuardian')); textGreen(document.getElementById('topMidGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('topMidGuardian')); returnTextColor(document.getElementById('topMidGuardianText'))}} id="topMidGuardian" cx="238.5" cy="162.5" r="58"/>
                    <polygon onMouseOver={() => {setScreens('Barrels'); turnGreen(document.getElementById('barrelsGuardian')); textGreen(document.getElementById('barrelsGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('barrelsGuardian')); returnTextColor(document.getElementById('barrelsGuardianText'))}}  id="barrelsGuardian" points="51,233 74,232 74,296 139,296 139,318 51,319"/>
                    <polygon onMouseOver={() => {setScreens('Blue Entrance'); turnGreen(document.getElementById('blueEntranceGuardian')); textGreen(document.getElementById('blueEntranceGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('blueEntranceGuardian')); returnTextColor(document.getElementById('blueEntranceGuardianText'))}}  id="blueEntranceGuardian" points="225,286 251,286 251,322 226,321"/>
                    <polygon onMouseOver={() => {setScreens('Blue Lights'); turnGreen(document.getElementById('blueLightsGuardian')); textGreen(document.getElementById('blueLightsGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('blueLightsGuardian')); returnTextColor(document.getElementById('blueLightsGuardianText'))}}  id="blueLightsGuardian" points="207,219 206,223 208,228 212,231 261,230 265,230 268,225 267,221 266,217 263,211 264,198 212,197 213,209"/>
                    <polygon onMouseOver={() => {setScreens('Blue Ramp'); turnGreen(document.getElementById('blueRampGuardian')); textGreen(document.getElementById('blueRampGuardianText')); turnGreen(document.getElementById('blueRampGuardian2'))}} onMouseOut={() => {returnColor(document.getElementById('blueRampGuardian')); returnColor(document.getElementById('blueRampGuardian2')); returnTextColor(document.getElementById('blueRampGuardianText'))}}  id="blueRampGuardian" points="255,331 256,343 242,356 156,356 156,328"/>
                    <polygon onMouseOver={() => {setScreens('Blue Ramp'); turnGreen(document.getElementById('blueRampGuardian')); textGreen(document.getElementById('blueRampGuardianText')); turnGreen(document.getElementById('blueRampGuardian2'))}} onMouseOut={() => {returnColor(document.getElementById('blueRampGuardian')); returnColor(document.getElementById('blueRampGuardian2')); returnTextColor(document.getElementById('blueRampGuardianText'))}}  id="blueRampGuardian2" points="444,540 522,540 522,554 509,566 444,566"/>
                    <polygon onMouseOver={() => {setScreens('Blue Window'); turnGreen(document.getElementById('blueWindowGuardian')); textGreen(document.getElementById('blueWindowGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('blueWindowGuardian')); returnTextColor(document.getElementById('blueWindowGuardianText'))}}  id="blueWindowGuardian" points="147,248 123,265 139,279 157,260"/>
                    <polygon onMouseOver={() => {setScreens('Bottom Gold'); turnGreen(document.getElementById('bottomGoldGuardian')); textGreen(document.getElementById('bottomGoldGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('bottomGoldGuardian')); returnTextColor(document.getElementById('bottomGoldGuardianText'))}}  id="bottomGoldGuardian" points="393,361 393,343 385,335 338,335 338,340 324,340 324,355 324,408 338,408 364,408 364,405 386,405 393,398"/>
                    <polygon onMouseOver={() => {setScreens('Bottom Green'); turnGreen(document.getElementById('bottomGreenGuardian')); textGreen(document.getElementById('bottomGreenGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('bottomGreenGuardian')); returnTextColor(document.getElementById('bottomGreenGuardianText'))}}  id="bottomGreenGuardian" points="510,300 510,273 497,257 490,241 493,228 488,224 483,224 478,226 472,231 469,230 464,226 471,218 476,213 470,208 474,203 474,197 474,190 481,183 481,164 489,156 504,149 518,146 534,147 545,147 559,152 568,159 578,167 587,176 595,188 601,198 603,205 596,215 591,220 590,240 590,243 587,249 582,254 575,258 567,265 563,267 563,271 563,281 545,300"/>
                    <polygon onMouseOver={() => {setScreens('Camo'); turnGreen(document.getElementById('camoGuardian')); textGreen(document.getElementById('camoGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('camoGuardian')); returnTextColor(document.getElementById('camoGuardianText'))}}  id="camoGuardian" points="155,116 147,115 147,110 142,110 140,99 131,87 121,80 113,77 107,76 71,76 71,63 68,63 66,59 54,59 48,62 37,62 30,67 27,76 27,93 34,103 38,104 38,100 45,101 76,101 92,101 101,106 110,115 118,126 123,133 147,133 155,133"/>
                    <polygon onMouseOver={() => {setScreens('Elbow'); turnGreen(document.getElementById('elbowGuardian')); textGreen(document.getElementById('elbowGuardianText')); turnGreen(document.getElementById('elbowGuardian2'))}} onMouseOut={() => {returnColor(document.getElementById('elbowGuardian')); returnTextColor(document.getElementById('elbowGuardianText')); returnColor(document.getElementById('elbowGuardian2'))}}  id="elbowGuardian" points="677,322 677,250 684,242 684,209 648,209 640,217 595,217 596,242 640,242 649,252 649,322"/>
                    <polygon onMouseOver={() => {setScreens('Elbow'); turnGreen(document.getElementById('elbowGuardian')); textGreen(document.getElementById('elbowGuardianText')); turnGreen(document.getElementById('elbowGuardian2'))}} onMouseOut={() => {returnColor(document.getElementById('elbowGuardian')); returnTextColor(document.getElementById('elbowGuardianText')); returnColor(document.getElementById('elbowGuardian2'))}}  id="elbowGuardian2" points="358,41 389,41 389,131 358,131"/>
                    <polygon onMouseOver={() => {setScreens('Front Blue'); turnGreen(document.getElementById('frontBlueGuardian')); textGreen(document.getElementById('frontBlueGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('frontBlueGuardian')); returnTextColor(document.getElementById('frontBlueGuardianText'))}}  id="frontBlueGuardian" points="226,216 250,216 250,285 226,285"/>
                    <polygon onMouseOver={() => {setScreens('Gold Lights'); turnGreen(document.getElementById('goldLightsGuardian')); textGreen(document.getElementById('goldLightsGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('goldLightsGuardian')); returnTextColor(document.getElementById('goldLightsGuardianText'))}}  id="goldLightsGuardian" points="198,136 186,136 180,133 175,131 173,132 170,135 171,139 171,144 171,151 171,173 171,180 170,185 169,188 171,191 174,193 178,193 181,191 190,186 199,186"/>
                    <polygon onMouseOver={() => {setScreens('Gold Window'); turnGreen(document.getElementById('goldWindowGuardian')); textGreen(document.getElementById('goldWindowGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('goldWindowGuardian')); returnTextColor(document.getElementById('goldWindowGuardianText'))}}  id="goldWindowGuardian" points="98,202 113,217 96,235 81,220"/>
                    <polygon onMouseOver={() => {setScreens('Green Lights'); turnGreen(document.getElementById('greenLightsGuardian')); textGreen(document.getElementById('greenLightsGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('greenLightsGuardian')); returnTextColor(document.getElementById('greenLightsGuardianText'))}}  id="greenLightsGuardian" points="214,116 211,112 208,105 206,101 207,98 210,95 264,95 267,97 268,101 264,110 263,116 263,129 214,129"/>
                    <polygon onMouseOver={() => {setScreens('Short Jump'); turnGreen(document.getElementById('shortJumpGuardian')); textGreen(document.getElementById('shortJumpGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('shortJumpGuardian')); returnTextColor(document.getElementById('shortJumpGuardianText'))}}  id="shortJumpGuardian" points="376,452 384,452 384,460 391,460 397,463 456,463 454,454 451,448 448,442 444,436 438,430 432,425 425,420 415,415 406,411 399,411 399,416 376,416"/>
                    <polygon onMouseOver={() => {setScreens('Shotgun Room'); turnGreen(document.getElementById('shotgunRoomGuardian')); textGreen(document.getElementById('shotgunRoomGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('shotgunRoomGuardian')); returnTextColor(document.getElementById('shotgunRoomGuardianText'))}}  id="shotgunRoomGuardian" points="335,505 450,505 450,533 410,533 334,534 334,531 317,531 317,507 333,507"/>
                    <polygon onMouseOver={() => {setScreens('Snipe 1'); turnGreen(document.getElementById('snipe1Guardian')); textGreen(document.getElementById('snipe1GuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('snipe1Guardian')); returnTextColor(document.getElementById('snipe1GuardianText'))}}  id="snipe1Guardian" points="633,356 641,356 641,350 690,350 690,352 690,393 640,393 640,388 633,388"/>
                    <polygon onMouseOver={() => {setScreens('Snipe 2'); turnGreen(document.getElementById('snipe2Guardian')); textGreen(document.getElementById('snipe2GuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('snipe2Guardian')); returnTextColor(document.getElementById('snipe2GuardianText'))}}  id="snipe2Guardian" points="404,137 404,190 366,190 364,184 359,179 355,175 355,137"/>
                    <polygon onMouseOver={() => {setScreens('Snipe 3'); turnGreen(document.getElementById('snipe3Guardian')); textGreen(document.getElementById('snipe3GuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('snipe3Guardian')); returnTextColor(document.getElementById('snipe3GuardianText'))}}  id="snipe3Guardian" points="405,212 377,212 375,218 366,224 356,224 348,217 347,207 350,201 356,195 351,189 345,180 317,180 316,207 321,207 322,216 325,226 333,238 341,247 357,251 405,252"/>
                    <polygon onMouseOver={() => {setScreens('Snipe Lift'); turnGreen(document.getElementById('snipeLiftGuardian')); textGreen(document.getElementById('snipeLiftGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('snipeLiftGuardian')); returnTextColor(document.getElementById('snipeLiftGuardianText'))}}  id="snipeLiftGuardian" points="523,509 547,509 555,509 567,509 573,515 573,530 571,538 571,591 524,591"/>
                    <polygon onMouseOver={() => {setScreens('Snipe Lights'); turnGreen(document.getElementById('snipeLightsGuardian')); textGreen(document.getElementById('snipeLightsGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('snipeLightsGuardian')); returnTextColor(document.getElementById('snipeLightsGuardianText'))}}  id="snipeLightsGuardian" points="304,146 297,145 301,141 304,137 302,133 299,131 291,131 270,131 271,193 285,192 296,192 301,192 303,188 303,185 299,182 296,180 298,178 304,178"/>
                    <polygon onMouseOver={() => {setScreens('Snipe Ramp'); turnGreen(document.getElementById('snipeRampGuardian')); textGreen(document.getElementById('snipeRampGuardianText')); turnGreen(document.getElementById('snipeRampGuardian2'))}} onMouseOut={() => {returnColor(document.getElementById('snipeRampGuardian')); returnTextColor(document.getElementById('snipeRampGuardianText')); returnColor(document.getElementById('snipeRampGuardian2'))}}  id="snipeRampGuardian" points="435,172 435,252 407,252 407,172"/>
                    <polygon onMouseOver={() => {setScreens('Snipe Ramp'); turnGreen(document.getElementById('snipeRampGuardian')); textGreen(document.getElementById('snipeRampGuardianText')); turnGreen(document.getElementById('snipeRampGuardian2'))}} onMouseOut={() => {returnColor(document.getElementById('snipeRampGuardian')); returnTextColor(document.getElementById('snipeRampGuardianText')); returnColor(document.getElementById('snipeRampGuardian2'))}}  id="snipeRampGuardian2" points="693,387 720,387 720,430 716,430 715,429 698,429 697,430 693,430"/>
                    <polygon onMouseOver={() => {setScreens('Stump'); turnGreen(document.getElementById('stumpGuardian')); textGreen(document.getElementById('stumpGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('stumpGuardian')); returnTextColor(document.getElementById('stumpGuardianText'))}}  id="stumpGuardian" points="574,228 579,229 582,230 587,235 588,240 587,246 587,249 583,252 582,254 576,256 575,258 570,260 567,265 563,267 557,267 552,265 550,259 550,253 553,248 558,246 563,244 564,239 564,233 568,230"/>
                    <polygon onMouseOver={() => {setScreens('Top Blue'); turnGreen(document.getElementById('topBlueGuardian')); textGreen(document.getElementById('topBlueGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('topBlueGuardian')); returnTextColor(document.getElementById('topBlueGuardianText'))}}  id="topBlueGuardian" points="205,293 205,274 189,258 164,258 159,262 155,262 140,278 139,296 139,318 140,319 205,319"/>
                    <polygon onMouseOver={() => {setScreens('Top Gold'); turnGreen(document.getElementById('topGoldGuardian')); textGreen(document.getElementById('topGoldGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('topGoldGuardian')); returnTextColor(document.getElementById('topGoldGuardianText'))}}  id="topGoldGuardian" points="46,118 94,118 115,140 115,142 111,142 111,149 136,149 136,176 111,176 111,183 115,183 115,185 97,202 81,220 79,221 75,222 74,230 51,230 51,196 55,192 55,178 53,175 57,170 57,156 53,151 55,147 55,134 48,128 48,124 46,124"/>
                    <polygon onMouseOver={() => {setScreens('Top Green'); turnGreen(document.getElementById('topGreenGuardian')); textGreen(document.getElementById('topGreenGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('topGreenGuardian')); returnTextColor(document.getElementById('topGreenGuardianText'))}}  id="topGreenGuardian" points="522,241 526,244 529,247 534,247 536,252 538,257 539,262 539,267 533,273 527,276 513,276 510,273 497,257 490,241 493,228 503,224 511,230 515,236"/>
                    <polygon onMouseOver={() => {setScreens('Under Glass'); turnGreen(document.getElementById('underGlassGuardian')); textGreen(document.getElementById('underGlassGuardianText'))}} onMouseOut={() => {returnColor(document.getElementById('underGlassGuardian')); returnTextColor(document.getElementById('underGlassGuardianText'))}}  id="underGlassGuardian" points="510,308 544,308 544,336 552,340 561,348 566,356 576,356 576,387 565,387 562,395 558,394 551,392 546,390 542,390 535,394 525,396 517,394 509,390 491,396 488,387 475,386 475,356 488,356 490,351 494,346 501,340 510,334"/>
                </svg>
                <Screenshot 
                    Map={'Guardian'}
                    Screenshot={screens}
                />
            </div>
        );
}

export default Guardian;