import React from 'react';
import amplifiedBlueprint from './BlueprintPics/amplifiedBPs/Amplified.png';
import amplifiedBlank from './BlueprintPics/amplifiedBPs/AmplifiedBlank.png';


class Amplified extends React.Component{
    turnGreen(div){
        div.style.fill="rgba(0, 255, 0, 0.5)";
    }
    returnColor(div){
        div.style.fill="rgba(0, 0, 0, 0)";
    }
    textGreen(textP){
        textP.style.color="rgba(0, 255, 0, 1)"
    }
    returnTextColor(textP){
        textP.style.color="white";
    }
    render(){
        return(
            <div className="amplifiedFullGrid">
                <h1 className="mapTitleAmplified">Amplified</h1>
                <div className="calloutsList" id="amplifiedCallouts">
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('topMidAmplified')); this.textGreen(document.getElementById('topMidAmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('topMidAmplified')); this.returnTextColor(document.getElementById('topMidAmplifiedText'))}} id="topMidAmplifiedText">Top Mid</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bottomMidAmplified')); this.textGreen(document.getElementById('bottomMidAmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('bottomMidAmplified')); this.returnTextColor(document.getElementById('bottomMidAmplifiedText'))}} id="bottomMidAmplifiedText">Bottom Mid</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('gold1Amplified')); this.textGreen(document.getElementById('gold1AmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('gold1Amplified')); this.returnTextColor(document.getElementById('gold1AmplifiedText'))}} id="gold1AmplifiedText">Gold 1</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('gold2Amplified')); this.textGreen(document.getElementById('gold2AmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('gold2Amplified')); this.returnTextColor(document.getElementById('gold2AmplifiedText'))}} id="gold2AmplifiedText">Gold 2</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('gold3Amplified')); this.textGreen(document.getElementById('gold3AmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('gold3Amplified')); this.returnTextColor(document.getElementById('gold3AmplifiedText'))}} id="gold3AmplifiedText">Gold 3</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('pink1Amplified')); this.textGreen(document.getElementById('pink1AmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('pink1Amplified')); this.returnTextColor(document.getElementById('pink1AmplifiedText'))}} id="pink1AmplifiedText">Pink 1</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('pink2Amplified')); this.textGreen(document.getElementById('pink2AmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('pink2Amplified')); this.returnTextColor(document.getElementById('pink2AmplifiedText'))}} id="pink2AmplifiedText">Pink 2</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('pink3Amplified')); this.textGreen(document.getElementById('pink3AmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('pink3Amplified')); this.returnTextColor(document.getElementById('pink3AmplifiedText'))}} id="pink3AmplifiedText">Pink 3</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('pinkPlat')); this.textGreen(document.getElementById('pinkPlatText'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkPlat')); this.returnTextColor(document.getElementById('pinkPlatText'))}} id="pinkPlatText">Pink Plat</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('red1Amp')); this.textGreen(document.getElementById('redBlue1AmpText')); this.turnGreen(document.getElementById('blue1Amp'))}} onMouseOut={() => {this.returnColor(document.getElementById('red1Amp')); this.returnTextColor(document.getElementById('redBlue1AmpText')); this.returnColor(document.getElementById('blue1Amp'))}} id="redBlue1AmpText">Red/Blue 1</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('red2Amp')); this.textGreen(document.getElementById('redBlue2AmpText')); this.turnGreen(document.getElementById('blue2Amp'))}} onMouseOut={() => {this.returnColor(document.getElementById('red2Amp')); this.returnTextColor(document.getElementById('redBlue2AmpText')); this.returnColor(document.getElementById('blue2Amp'))}} id="redBlue2AmpText">Red/Blue 2</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('couch')); this.textGreen(document.getElementById('couchText')); this.turnGreen(document.getElementById('couch2'))}} onMouseOut={() => {this.returnColor(document.getElementById('couch')); this.returnTextColor(document.getElementById('couchText')); this.returnColor(document.getElementById('couch2'))}} id="couchText">Couch</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('courtyard')); this.textGreen(document.getElementById('courtyardText')); this.turnGreen(document.getElementById('courtyard2'))}} onMouseOut={() => {this.returnColor(document.getElementById('courtyard')); this.returnTextColor(document.getElementById('courtyardText')); this.returnColor(document.getElementById('courtyard2'))}} id="courtyardText">Courtyard</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('fence')); this.textGreen(document.getElementById('fenceText')); this.turnGreen(document.getElementById('fence2'))}} onMouseOut={() => {this.returnColor(document.getElementById('fence')); this.returnTextColor(document.getElementById('fenceText')); this.returnColor(document.getElementById('fence2'))}} id="fenceText">Fence</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('goldBubble')); this.textGreen(document.getElementById('goldBubbleText')); this.turnGreen(document.getElementById('goldBubble2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldBubble')); this.returnTextColor(document.getElementById('goldBubbleText')); this.returnColor(document.getElementById('goldBubble2'))}} id="goldBubbleText">Gold Bubble</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('goldJumpUp')); this.textGreen(document.getElementById('goldJumpUpText')); this.turnGreen(document.getElementById('goldJumpUp2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldJumpUp')); this.returnTextColor(document.getElementById('goldJumpUpText')); this.returnColor(document.getElementById('goldJumpUp2'))}} id="goldJumpUpText">Gold Jump Up</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('goldPocket')); this.textGreen(document.getElementById('goldPocketText')); this.turnGreen(document.getElementById('goldPocket2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldPocket')); this.returnTextColor(document.getElementById('goldPocketText')); this.returnColor(document.getElementById('goldPocket2'))}} id="goldPocketText">Gold Pocket</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('goldSign')); this.textGreen(document.getElementById('goldSignText')); this.turnGreen(document.getElementById('goldSign2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldSign')); this.returnTextColor(document.getElementById('goldSignText')); this.returnColor(document.getElementById('goldSign2'))}} id="goldSignText">Gold Sign</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('goldTower')); this.textGreen(document.getElementById('goldTowerText')); this.turnGreen(document.getElementById('goldTower2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldTower')); this.returnTextColor(document.getElementById('goldTowerText')); this.returnColor(document.getElementById('goldTower2'))}} id="goldTowerText">Gold Tower</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('house')); this.textGreen(document.getElementById('houseText')); this.turnGreen(document.getElementById('house2'))}} onMouseOut={() => {this.returnColor(document.getElementById('house')); this.returnTextColor(document.getElementById('houseText')); this.returnColor(document.getElementById('house2'))}} id="houseText">House</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('pinkBubble')); this.textGreen(document.getElementById('pinkBubbleText')); this.turnGreen(document.getElementById('pinkBubble2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkBubble')); this.returnTextColor(document.getElementById('pinkBubbleText')); this.returnColor(document.getElementById('pinkBubble2'))}} id="pinkBubbleText">Pink Bubble</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('pinkJumpUp')); this.textGreen(document.getElementById('pinkJumpUpText')); this.turnGreen(document.getElementById('pinkJumpUp2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkJumpUp')); this.returnTextColor(document.getElementById('pinkJumpUpText')); this.returnColor(document.getElementById('pinkJumpUp2'))}} id="pinkJumpUpText">Pink Jump Up</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('pinkPocket')); this.textGreen(document.getElementById('pinkPocketText')); this.turnGreen(document.getElementById('pinkPocket2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkPocket')); this.returnTextColor(document.getElementById('pinkPocketText')); this.returnColor(document.getElementById('pinkPocket2'))}} id="pinkPocketText">Pink Pocket</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('pinkTower')); this.textGreen(document.getElementById('pinkTowerText')); this.turnGreen(document.getElementById('pinkTower2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkTower')); this.returnTextColor(document.getElementById('pinkTowerText')); this.returnColor(document.getElementById('pinkTower2'))}} id="pinkTowerText">Pink Tower</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('pinkShield')); this.textGreen(document.getElementById('pinkShieldText')); this.turnGreen(document.getElementById('pinkShield2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkShield')); this.returnTextColor(document.getElementById('pinkShieldText')); this.returnColor(document.getElementById('pinkShield2'))}} id="pinkShieldText">Pink Shield</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('pinkSign')); this.textGreen(document.getElementById('pinkSignText')); this.turnGreen(document.getElementById('pinkSign2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkSign')); this.returnTextColor(document.getElementById('pinkSignText')); this.returnColor(document.getElementById('pinkSign2'))}} id="pinkSignText">Pink Sign</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('plat')); this.textGreen(document.getElementById('platText')); this.turnGreen(document.getElementById('plat2'))}} onMouseOut={() => {this.returnColor(document.getElementById('plat')); this.returnTextColor(document.getElementById('platText')); this.returnColor(document.getElementById('plat2'))}} id="platText">Plat</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('street')); this.textGreen(document.getElementById('streetText')); this.turnGreen(document.getElementById('street2'))}} onMouseOut={() => {this.returnColor(document.getElementById('street')); this.returnTextColor(document.getElementById('streetText')); this.returnColor(document.getElementById('street2'))}} id="streetText">Street</p>
                </div>
                <svg id="amplifiedMap" width="750px" height="625px">
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('topMidAmplified')); this.textGreen(document.getElementById('topMidAmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('topMidAmplified')); this.returnTextColor(document.getElementById('topMidAmplifiedText'))}}  id="topMidAmplified" points="411,302 411,323 316,323 316,302"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bottomMidAmplified')); this.textGreen(document.getElementById('bottomMidAmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('bottomMidAmplified')); this.returnTextColor(document.getElementById('bottomMidAmplifiedText'))}}  id="bottomMidAmplified" points="315,299 412,299 412,325 315,325"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('gold1Amplified')); this.textGreen(document.getElementById('gold1AmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('gold1Amplified')); this.returnTextColor(document.getElementById('gold1AmplifiedText'))}} id="gold1Amplified" points="240,299 180,299 180,325 240,326"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('gold2Amplified')); this.textGreen(document.getElementById('gold2AmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('gold2Amplified')); this.returnTextColor(document.getElementById('gold2AmplifiedText'))}}  id="gold2Amplified" points="149,286 240,286 240,336 149,336"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('gold3Amplified')); this.textGreen(document.getElementById('gold3AmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('gold3Amplified')); this.returnTextColor(document.getElementById('gold3AmplifiedText'))}}  id="gold3Amplified" points="181,249 240,249 254,239 257,239 284,260 240,288 240,340 243,340 284,361 257,387 241,375 181,375"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pink1Amplified')); this.textGreen(document.getElementById('pink1AmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('pink1Amplified')); this.returnTextColor(document.getElementById('pink1AmplifiedText'))}}  id="pink1Amplified" points="508,299 479,299 479,330 508,330"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pink2Amplified')); this.textGreen(document.getElementById('pink2AmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('pink2Amplified')); this.returnTextColor(document.getElementById('pink2AmplifiedText'))}}  id="pink2Amplified" points="575,251 539,251 539,299 511,299 511,330 539,330 539,374 575,374"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pink3Amplified')); this.textGreen(document.getElementById('pink3AmplifiedText'))}} onMouseOut={() => {this.returnColor(document.getElementById('pink3Amplified')); this.returnTextColor(document.getElementById('pink3AmplifiedText'))}}  id="pink3Amplified" points="508,251 498,261 498,262 511,275 511,347 497,361 508,374 575,374 575,251"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkPlat')); this.textGreen(document.getElementById('pinkPlatText'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkPlat')); this.returnTextColor(document.getElementById('pinkPlatText'))}}  id="pinkPlat" points="436,302 451,290 477,311 451,336 436,323"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('red1Amp')); this.textGreen(document.getElementById('redBlue1AmpText')); this.turnGreen(document.getElementById('blue1Amp'))}} onMouseOut={() => {this.returnColor(document.getElementById('red1Amp')); this.returnTextColor(document.getElementById('redBlue1AmpText')); this.returnColor(document.getElementById('blue1Amp'))}}  id="red1Amp" points="258,69 258,87 480,87 480,69"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('red1Amp')); this.textGreen(document.getElementById('redBlue1AmpText')); this.turnGreen(document.getElementById('blue1Amp'))}} onMouseOut={() => {this.returnColor(document.getElementById('red1Amp')); this.returnTextColor(document.getElementById('redBlue1AmpText')); this.returnColor(document.getElementById('blue1Amp'))}}  id="blue1Amp" points="258,541 258,560 479,560 479,541"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('red2Amp')); this.textGreen(document.getElementById('redBlue2AmpText')); this.turnGreen(document.getElementById('blue2Amp'))}} onMouseOut={() => {this.returnColor(document.getElementById('red2Amp')); this.returnTextColor(document.getElementById('redBlue2AmpText')); this.returnColor(document.getElementById('blue2Amp'))}}  id="red2Amp" points="258,88 258,105 308,105 308,124 448,124 448,105 480,105 480,88"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('red2Amp')); this.textGreen(document.getElementById('redBlue2AmpText')); this.turnGreen(document.getElementById('blue2Amp'))}} onMouseOut={() => {this.returnColor(document.getElementById('red2Amp')); this.returnTextColor(document.getElementById('redBlue2AmpText')); this.returnColor(document.getElementById('blue2Amp'))}}  id="blue2Amp" points="258,523 307,523 307,501 442,501 442,523 479,523 479,540 258,540"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('couch')); this.textGreen(document.getElementById('couchText')); this.turnGreen(document.getElementById('couch2'))}} onMouseOut={() => {this.returnColor(document.getElementById('couch')); this.returnTextColor(document.getElementById('couchText')); this.returnColor(document.getElementById('couch2'))}}  id="couch" points="331,298 316,276 329,260 393,260 407,276 392,298"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('couch')); this.textGreen(document.getElementById('couchText')); this.turnGreen(document.getElementById('couch2'))}} onMouseOut={() => {this.returnColor(document.getElementById('couch')); this.returnTextColor(document.getElementById('couchText')); this.returnColor(document.getElementById('couch2'))}}  id="couch2" points="331,327 317,347 329,361 392,361 407,347 392,327"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('courtyard')); this.textGreen(document.getElementById('courtyardText')); this.turnGreen(document.getElementById('courtyard2'))}} onMouseOut={() => {this.returnColor(document.getElementById('courtyard')); this.returnTextColor(document.getElementById('courtyardText')); this.returnColor(document.getElementById('courtyard2'))}}  id="courtyard" points="273,140 273,248 286,259 480,259 480,139 449,139 449,128 302,128 302,140"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('courtyard')); this.textGreen(document.getElementById('courtyardText')); this.turnGreen(document.getElementById('courtyard2'))}} onMouseOut={() => {this.returnColor(document.getElementById('courtyard')); this.returnTextColor(document.getElementById('courtyardText')); this.returnColor(document.getElementById('courtyard2'))}}  id="courtyard2" points="272,376 272,484 303,484 303,498 448,498 448,482 480,482 480,362 387,362"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('fence')); this.textGreen(document.getElementById('fenceText')); this.turnGreen(document.getElementById('fence2'))}} onMouseOut={() => {this.returnColor(document.getElementById('fence')); this.returnTextColor(document.getElementById('fenceText')); this.returnColor(document.getElementById('fence2'))}}  id="fence" points="181,142 149,142 149,163 181,163"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('fence')); this.textGreen(document.getElementById('fenceText')); this.turnGreen(document.getElementById('fence2'))}} onMouseOut={() => {this.returnColor(document.getElementById('fence')); this.returnTextColor(document.getElementById('fenceText')); this.returnColor(document.getElementById('fence2'))}}  id="fence2" points="180,460 149,460 149,481 180,481"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('goldBubble')); this.textGreen(document.getElementById('goldBubbleText')); this.turnGreen(document.getElementById('goldBubble2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldBubble')); this.returnTextColor(document.getElementById('goldBubbleText')); this.returnColor(document.getElementById('goldBubble2'))}}  id="goldBubble" points="208,50 182,50 182,101 208,101"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('goldBubble')); this.textGreen(document.getElementById('goldBubbleText')); this.turnGreen(document.getElementById('goldBubble2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldBubble')); this.returnTextColor(document.getElementById('goldBubbleText')); this.returnColor(document.getElementById('goldBubble2'))}}  id="goldBubble2" points="210,525 182,525 182,573 210,573"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('goldJumpUp')); this.textGreen(document.getElementById('goldJumpUpText')); this.turnGreen(document.getElementById('goldJumpUp2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldJumpUp')); this.returnTextColor(document.getElementById('goldJumpUpText')); this.returnColor(document.getElementById('goldJumpUp2'))}}  id="goldJumpUp" points="271,126 299,126 299,137 271,137"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('goldJumpUp')); this.textGreen(document.getElementById('goldJumpUpText')); this.turnGreen(document.getElementById('goldJumpUp2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldJumpUp')); this.returnTextColor(document.getElementById('goldJumpUpText')); this.returnColor(document.getElementById('goldJumpUp2'))}}  id="goldJumpUp2" points="272,487 300,487 300,500 272,500"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('goldPocket')); this.textGreen(document.getElementById('goldPocketText')); this.turnGreen(document.getElementById('goldPocket2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldPocket')); this.returnTextColor(document.getElementById('goldPocketText')); this.returnColor(document.getElementById('goldPocket2'))}}  id="goldPocket" points="258,106 307,106 307,114 258,114"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('goldPocket')); this.textGreen(document.getElementById('goldPocketText')); this.turnGreen(document.getElementById('goldPocket2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldPocket')); this.returnTextColor(document.getElementById('goldPocketText')); this.returnColor(document.getElementById('goldPocket2'))}}  id="goldPocket2" points="258,512 306,512 306,522 258,522"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('goldSign')); this.textGreen(document.getElementById('goldSignText')); this.turnGreen(document.getElementById('goldSign2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldSign')); this.returnTextColor(document.getElementById('goldSignText')); this.returnColor(document.getElementById('goldSign2'))}}  id="goldSign" points="268,174 272,174 272,178 244,201 240,201 240,197"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('goldSign')); this.textGreen(document.getElementById('goldSignText')); this.turnGreen(document.getElementById('goldSign2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldSign')); this.returnTextColor(document.getElementById('goldSignText')); this.returnColor(document.getElementById('goldSign2'))}}  id="goldSign2" points="245,424 241,424 241,429 267,450 271,450 271,446"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('goldTower')); this.textGreen(document.getElementById('goldTowerText')); this.turnGreen(document.getElementById('goldTower2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldTower')); this.returnTextColor(document.getElementById('goldTowerText')); this.returnColor(document.getElementById('goldTower2'))}}  id="goldTower" points="307,115 271,115 271,125 307,125"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('goldTower')); this.textGreen(document.getElementById('goldTowerText')); this.turnGreen(document.getElementById('goldTower2'))}} onMouseOut={() => {this.returnColor(document.getElementById('goldTower')); this.returnTextColor(document.getElementById('goldTowerText')); this.returnColor(document.getElementById('goldTower2'))}}  id="goldTower2" points="272,501 306,501 306,511 272,511"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('house')); this.textGreen(document.getElementById('houseText')); this.turnGreen(document.getElementById('house2'))}} onMouseOut={() => {this.returnColor(document.getElementById('house')); this.returnTextColor(document.getElementById('houseText')); this.returnColor(document.getElementById('house2'))}}  id="house" points="481,176 510,176 510,200 481,200"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('house')); this.textGreen(document.getElementById('houseText')); this.turnGreen(document.getElementById('house2'))}} onMouseOut={() => {this.returnColor(document.getElementById('house')); this.returnTextColor(document.getElementById('houseText')); this.returnColor(document.getElementById('house2'))}}  id="house2" points="481,425 510,425 510,449 481,449"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkBubble')); this.textGreen(document.getElementById('pinkBubbleText')); this.turnGreen(document.getElementById('pinkBubble2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkBubble')); this.returnTextColor(document.getElementById('pinkBubbleText')); this.returnColor(document.getElementById('pinkBubble2'))}}  id="pinkBubble" points="482,23 539,23 539,50 482,50"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkBubble')); this.textGreen(document.getElementById('pinkBubbleText')); this.turnGreen(document.getElementById('pinkBubble2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkBubble')); this.returnTextColor(document.getElementById('pinkBubbleText')); this.returnColor(document.getElementById('pinkBubble2'))}}  id="pinkBubble2" points="481,575 540,575 540,596 481,596"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkJumpUp')); this.textGreen(document.getElementById('pinkJumpUpText')); this.turnGreen(document.getElementById('pinkJumpUp2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkJumpUp')); this.returnTextColor(document.getElementById('pinkJumpUpText')); this.returnColor(document.getElementById('pinkJumpUp2'))}}  id="pinkJumpUp" points="452,131 480,131 480,136 452,136"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkJumpUp')); this.textGreen(document.getElementById('pinkJumpUpText')); this.turnGreen(document.getElementById('pinkJumpUp2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkJumpUp')); this.returnTextColor(document.getElementById('pinkJumpUpText')); this.returnColor(document.getElementById('pinkJumpUp2'))}}  id="pinkJumpUp2" points="451,485 479,485 479,491 451,491"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkPocket')); this.textGreen(document.getElementById('pinkPocketText')); this.turnGreen(document.getElementById('pinkPocket2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkPocket')); this.returnTextColor(document.getElementById('pinkPocketText')); this.returnColor(document.getElementById('pinkPocket2'))}}  id="pinkPocket" points="449,106 480,106 480,118 449,118"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkPocket')); this.textGreen(document.getElementById('pinkPocketText')); this.turnGreen(document.getElementById('pinkPocket2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkPocket')); this.returnTextColor(document.getElementById('pinkPocketText')); this.returnColor(document.getElementById('pinkPocket2'))}}  id="pinkPocket2" points="443,503 479,503 479,522 443,522"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkTower')); this.textGreen(document.getElementById('pinkTowerText')); this.turnGreen(document.getElementById('pinkTower2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkTower')); this.returnTextColor(document.getElementById('pinkTowerText')); this.returnColor(document.getElementById('pinkTower2'))}}  id="pinkTower" points="449,119 480,119 480,130 452,130 452,125 449,125"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkTower')); this.textGreen(document.getElementById('pinkTowerText')); this.turnGreen(document.getElementById('pinkTower2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkTower')); this.returnTextColor(document.getElementById('pinkTowerText')); this.returnColor(document.getElementById('pinkTower2'))}}  id="pinkTower2" points="451,492 479,492 479,502 443,502 443,501 451,501"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkShield')); this.textGreen(document.getElementById('pinkShieldText')); this.turnGreen(document.getElementById('pinkShield2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkShield')); this.returnTextColor(document.getElementById('pinkShieldText')); this.returnColor(document.getElementById('pinkShield2'))}}  id="pinkShield" points="534,137 561,137 561,165 534,165"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkShield')); this.textGreen(document.getElementById('pinkShieldText')); this.turnGreen(document.getElementById('pinkShield2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkShield')); this.returnTextColor(document.getElementById('pinkShieldText')); this.returnColor(document.getElementById('pinkShield2'))}}  id="pinkShield2" points="535,464 569,464 569,490 535,490"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkSign')); this.textGreen(document.getElementById('pinkSignText')); this.turnGreen(document.getElementById('pinkSign2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkSign')); this.returnTextColor(document.getElementById('pinkSignText')); this.returnColor(document.getElementById('pinkSign2'))}}  id="pinkSign" points="500,76 495,76 495,80 509,101 513,101 513,96"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pinkSign')); this.textGreen(document.getElementById('pinkSignText')); this.turnGreen(document.getElementById('pinkSign2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pinkSign')); this.returnTextColor(document.getElementById('pinkSignText')); this.returnColor(document.getElementById('pinkSign2'))}}  id="pinkSign2" points="525,538 525,534 521,534 496,545 496,549 500,549"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('plat')); this.textGreen(document.getElementById('platText')); this.turnGreen(document.getElementById('plat2'))}} onMouseOut={() => {this.returnColor(document.getElementById('plat')); this.returnTextColor(document.getElementById('platText')); this.returnColor(document.getElementById('plat2'))}}  id="plat" points="330,23 391,23 391,51 375,59 360,51 359,51 345,59 330,51"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('plat')); this.textGreen(document.getElementById('platText')); this.turnGreen(document.getElementById('plat2'))}} onMouseOut={() => {this.returnColor(document.getElementById('plat')); this.returnTextColor(document.getElementById('platText')); this.returnColor(document.getElementById('plat2'))}}  id="plat2" points="330,596 330,574 346,568 360,574 376,567 391,574 391,596"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('street')); this.textGreen(document.getElementById('streetText')); this.turnGreen(document.getElementById('street2'))}} onMouseOut={() => {this.returnColor(document.getElementById('street')); this.returnTextColor(document.getElementById('streetText')); this.returnColor(document.getElementById('street2'))}}  id="street" points="539,168 576,168 576,249 539,249"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('street')); this.textGreen(document.getElementById('streetText')); this.turnGreen(document.getElementById('street2'))}} onMouseOut={() => {this.returnColor(document.getElementById('street')); this.returnTextColor(document.getElementById('streetText')); this.returnColor(document.getElementById('street2'))}}  id="street2" points="541,376 576,376 576,460 541,460"/>   
                </svg>
                <div className="inGamePic">
                    <h2 id="amplifiedInGamePicText" class="inGamePicText"></h2>
                    <img id="amplifiedScreenShot"></img>
                </div>
            </div>
        );
    }
}

export default Amplified;