import React from 'react';

class Onslaught extends React.Component{
    turnGreen(div){
        div.style.fill="rgba(0, 255, 0, 0.5)";
    }
    returnColor(div){
        div.style.fill="rgba(0, 0, 0, 0)";
    }
    textGreen(textP){
        textP.style.color="rgba(0, 255, 0, 1)"
    }
    returnTextColor(textP){
        textP.style.color="white";
    }
    render(){
        return(
            <div className="onslaughtFullGrid">
                <h1 className="mapTitleOnslaught">Onslaught</h1>
                <div className="calloutsList" id="onslaughtCallouts">
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aCorner')); this.textGreen(document.getElementById('aCornerText')); this.turnGreen(document.getElementById('aCorner2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aCorner')); this.returnTextColor(document.getElementById('aCornerText')); this.returnColor(document.getElementById('aCorner2'))}} id="aCornerText">A Corner</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aCuts')); this.textGreen(document.getElementById('aCutsText')); this.turnGreen(document.getElementById('aCuts2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aCuts')); this.returnTextColor(document.getElementById('aCutsText')); this.returnColor(document.getElementById('aCuts2'))}} id="aCutsText">A Cuts</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aDumpster')); this.textGreen(document.getElementById('aDumpsterText')); this.turnGreen(document.getElementById('aDumpster2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aDumpster')); this.returnTextColor(document.getElementById('aDumpsterText')); this.returnColor(document.getElementById('aDumpster2'))}} id="aDumpsterText">A Dumpster</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aHouse')); this.textGreen(document.getElementById('aHouseText')); this.turnGreen(document.getElementById('aHouse2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aHouse')); this.returnTextColor(document.getElementById('aHouseText')); this.returnColor(document.getElementById('aHouse2'))}} id="aHouseText">A House</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aJumpUp')); this.textGreen(document.getElementById('aJumpUpText')); this.turnGreen(document.getElementById('aJumpUp2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aJumpUp')); this.returnTextColor(document.getElementById('aJumpUpText')); this.returnColor(document.getElementById('aJumpUp2'))}} id="aJumpUpText">A Jump Up</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aMaze')); this.textGreen(document.getElementById('aMazeText'))}} onMouseOut={() => {this.returnColor(document.getElementById('aMaze')); this.returnTextColor(document.getElementById('aMazeText'))}} id="aMazeText">A Maze</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aNest')); this.textGreen(document.getElementById('aNestText'))}} onMouseOut={() => {this.returnColor(document.getElementById('aNest')); this.returnTextColor(document.getElementById('aNestText'))}} id="aNestText">A Nest</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aPocket')); this.textGreen(document.getElementById('aPocketText')); this.turnGreen(document.getElementById('aPocket2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aPocket')); this.returnTextColor(document.getElementById('aPocketText')); this.returnColor(document.getElementById('aPocket2'))}} id="aPocketText">A Pocket</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aSneaky')); this.textGreen(document.getElementById('aSneakyText')); this.turnGreen(document.getElementById('aSneaky2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aSneaky')); this.returnTextColor(document.getElementById('aSneakyText')); this.returnColor(document.getElementById('aSneaky2'))}} id="aSneakyText">A Sneaky</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aStairs')); this.textGreen(document.getElementById('aStairsText')); this.turnGreen(document.getElementById('aStairs2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aStairs')); this.returnTextColor(document.getElementById('aStairsText')); this.returnColor(document.getElementById('aStairs2'))}} id="aStairsText">A Stairs</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aStandup')); this.textGreen(document.getElementById('aStandupText')); this.turnGreen(document.getElementById('aStandup2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aStandup')); this.returnTextColor(document.getElementById('aStandupText')); this.returnColor(document.getElementById('aStandup2'))}} id="aStandupText">A Standup</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aStreet')); this.textGreen(document.getElementById('aStreetText')); this.turnGreen(document.getElementById('aStreet2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aStreet')); this.returnTextColor(document.getElementById('aStreetText')); this.returnColor(document.getElementById('aStreet2'))}} id="aStreetText">A Street</p>       
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aTeepee')); this.textGreen(document.getElementById('aTeepeeText'))}} onMouseOut={() => {this.returnColor(document.getElementById('aTeepee')); this.returnTextColor(document.getElementById('aTeepeeText'))}} id="aTeepeeText">A Teepee</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('aTunnel')); this.textGreen(document.getElementById('aTunnelText'))}} onMouseOut={() => {this.returnColor(document.getElementById('aTunnel')); this.returnTextColor(document.getElementById('aTunnelText'))}} id="aTunnelText">A Tunnel</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('topAOnslaught')); this.textGreen(document.getElementById('topAOnslaughtText'))}} onMouseOut={() => {this.returnColor(document.getElementById('topAOnslaught')); this.returnTextColor(document.getElementById('topAOnslaughtText'))}} id="topAOnslaughtText">Top A</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bCorner')); this.textGreen(document.getElementById('bCornerText')); this.turnGreen(document.getElementById('bCorner2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bCorner')); this.returnTextColor(document.getElementById('bCornerText')); this.returnColor(document.getElementById('bCorner2'))}} id="bCornerText">B Corner</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bCuts')); this.textGreen(document.getElementById('bCutsText')); this.turnGreen(document.getElementById('bCuts2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bCuts')); this.returnTextColor(document.getElementById('bCutsText')); this.returnColor(document.getElementById('bCuts2'))}} id="bCutsText">B Cuts</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bDumpster')); this.textGreen(document.getElementById('bDumpsterText')); this.turnGreen(document.getElementById('bDumpster2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bDumpster')); this.returnTextColor(document.getElementById('bDumpsterText')); this.returnColor(document.getElementById('bDumpster2'))}} id="bDumpsterText">B Dumpster</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bHouse')); this.textGreen(document.getElementById('bHouseText')); this.turnGreen(document.getElementById('bHouse2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bHouse')); this.returnTextColor(document.getElementById('bHouseText')); this.returnColor(document.getElementById('bHouse2'))}} id="bHouseText">B House</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bJumpUp')); this.textGreen(document.getElementById('bJumpUpText')); this.turnGreen(document.getElementById('bJumpUp2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bJumpUp')); this.returnTextColor(document.getElementById('bJumpUpText')); this.returnColor(document.getElementById('bJumpUp2'))}} id="bJumpUpText">B Jump Up</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bMaze')); this.textGreen(document.getElementById('bMazeText'))}} onMouseOut={() => {this.returnColor(document.getElementById('bMaze')); this.returnTextColor(document.getElementById('bMazeText'))}} id="bMazeText">B Maze</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bNest')); this.textGreen(document.getElementById('bNestText')); this.turnGreen(document.getElementById('bNest'))}} onMouseOut={() => {this.returnColor(document.getElementById('bNest')); this.returnTextColor(document.getElementById('bNestText')); this.returnColor(document.getElementById('bNest'))}} id="bNestText">B Nest</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bPocket')); this.textGreen(document.getElementById('bPocketText')); this.turnGreen(document.getElementById('bPocket2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bPocket')); this.returnTextColor(document.getElementById('bPocketText')); this.returnColor(document.getElementById('bPocket2'))}} id="bPocketText">B Pocket</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bSneaky')); this.textGreen(document.getElementById('bSneakyText'))}} onMouseOut={() => {this.returnColor(document.getElementById('bSneaky')); this.returnTextColor(document.getElementById('bSneakyText'))}} id="bSneakyText">B Sneaky</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bStairs')); this.textGreen(document.getElementById('bStairsText')); this.turnGreen(document.getElementById('bStairs2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bStairs')); this.returnTextColor(document.getElementById('bStairsText')); this.returnColor(document.getElementById('bStairs2'))}} id="bStairsText">B Stairs</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bStandup')); this.textGreen(document.getElementById('bStandupText')); this.turnGreen(document.getElementById('bStandup2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bStandup')); this.returnTextColor(document.getElementById('bStandupText')); this.returnColor(document.getElementById('bStandup2'))}} id="bStandupText">B Standup</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bStreet')); this.textGreen(document.getElementById('bStreetText')); this.turnGreen(document.getElementById('bStreet2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bStreet')); this.returnTextColor(document.getElementById('bStreetText')); this.returnColor(document.getElementById('bStreet2'))}} id="bStreetText">B Street</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bTeepee')); this.textGreen(document.getElementById('bTeepeeText'))}} onMouseOut={() => {this.returnColor(document.getElementById('bTeepee')); this.returnTextColor(document.getElementById('bTeepeeText'))}} id="bTeepeeText">B Teepee</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('bTunnel')); this.textGreen(document.getElementById('bTunnelText'))}} onMouseOut={() => {this.returnColor(document.getElementById('bTunnel')); this.returnTextColor(document.getElementById('bTunnelText'))}} id="bTunnelText">B Tunnel</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('topBOnslaught')); this.textGreen(document.getElementById('topBOnslaughtText'))}} onMouseOut={() => {this.returnColor(document.getElementById('topBOnslaught')); this.returnTextColor(document.getElementById('topBOnslaughtText'))}} id="topBOnslaughtText">Top B</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('basement')); this.textGreen(document.getElementById('basementText')); this.turnGreen(document.getElementById('basement2'))}} onMouseOut={() => {this.returnColor(document.getElementById('basement')); this.returnTextColor(document.getElementById('basementText')); this.returnColor(document.getElementById('basement2'))}} id="basementText">Basement</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('courtyard')); this.textGreen(document.getElementById('courtyardText')); this.turnGreen(document.getElementById('courtyard2'))}} onMouseOut={() => {this.returnColor(document.getElementById('courtyard')); this.returnTextColor(document.getElementById('courtyardText')); this.returnColor(document.getElementById('courtyard2'))}} id="courtyardText">Courtyard</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('flag')); this.textGreen(document.getElementById('flagText')); this.turnGreen(document.getElementById('flag2'))}} onMouseOut={() => {this.returnColor(document.getElementById('flag')); this.returnTextColor(document.getElementById('flagText')); this.returnColor(document.getElementById('flag2'))}} id="flagText">Flag</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('garageDoor')); this.textGreen(document.getElementById('garageDoorText')); this.turnGreen(document.getElementById('garageDoor2'))}} onMouseOut={() => {this.returnColor(document.getElementById('garageDoor')); this.returnTextColor(document.getElementById('garageDoorText')); this.returnColor(document.getElementById('garageDoor2'))}} id="garageDoorText">Garage Door</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('shield')); this.textGreen(document.getElementById('shieldText')); this.turnGreen(document.getElementById('shield2'))}} onMouseOut={() => {this.returnColor(document.getElementById('shield')); this.returnTextColor(document.getElementById('shieldText')); this.returnColor(document.getElementById('shield2'))}} id="shieldText">Shield</p>
                    <p>Bottom Mid</p>
                </div>
                <svg id="onslaughtMap" width="750px" height="625px">
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aCorner')); this.textGreen(document.getElementById('aCornerText')); this.turnGreen(document.getElementById('aCorner2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aCorner')); this.returnTextColor(document.getElementById('aCornerText')); this.returnColor(document.getElementById('aCorner2'))}}  id="aCorner" points="200,49 200,23 149,23 149,49"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aCorner')); this.textGreen(document.getElementById('aCornerText')); this.turnGreen(document.getElementById('aCorner2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aCorner')); this.returnTextColor(document.getElementById('aCornerText')); this.returnColor(document.getElementById('aCorner2'))}}  id="aCorner2" points="200,575 149,575 149,597 200,597"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aCuts')); this.textGreen(document.getElementById('aCutsText')); this.turnGreen(document.getElementById('aCuts2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aCuts')); this.returnTextColor(document.getElementById('aCutsText')); this.returnColor(document.getElementById('aCuts2'))}}  id="aCuts" points="287,248 315,248 315,283 287,283"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aCuts')); this.textGreen(document.getElementById('aCutsText')); this.turnGreen(document.getElementById('aCuts2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aCuts')); this.returnTextColor(document.getElementById('aCutsText')); this.returnColor(document.getElementById('aCuts2'))}}  id="aCuts2" points="288,343 315,343 315,375 288,375"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aDumpster')); this.textGreen(document.getElementById('aDumpsterText')); this.turnGreen(document.getElementById('aDumpster2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aDumpster')); this.returnTextColor(document.getElementById('aDumpsterText')); this.returnColor(document.getElementById('aDumpster2'))}}  id="aDumpster" points="238,98 244,103 212,130 206,124"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aDumpster')); this.textGreen(document.getElementById('aDumpsterText')); this.turnGreen(document.getElementById('aDumpster2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aDumpster')); this.returnTextColor(document.getElementById('aDumpsterText')); this.returnColor(document.getElementById('aDumpster2'))}}  id="aDumpster2" points="212,497 243,523 239,528 208,501"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aHouse')); this.textGreen(document.getElementById('aHouseText')); this.turnGreen(document.getElementById('aHouse2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aHouse')); this.returnTextColor(document.getElementById('aHouseText')); this.returnColor(document.getElementById('aHouse2'))}}  id="aHouse" points="241,50 241,23 285,23 285,50"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aHouse')); this.textGreen(document.getElementById('aHouseText')); this.turnGreen(document.getElementById('aHouse2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aHouse')); this.returnTextColor(document.getElementById('aHouseText')); this.returnColor(document.getElementById('aHouse2'))}}  id="aHouse2" points="240,574 285,574 285,598 240,598"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aJumpUp')); this.textGreen(document.getElementById('aJumpUpText')); this.turnGreen(document.getElementById('aJumpUp2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aJumpUp')); this.returnTextColor(document.getElementById('aJumpUpText')); this.returnColor(document.getElementById('aJumpUp2'))}}  id="aJumpUp" points="314,126 335,126 335,131 314,131"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aJumpUp')); this.textGreen(document.getElementById('aJumpUpText')); this.turnGreen(document.getElementById('aJumpUp2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aJumpUp')); this.returnTextColor(document.getElementById('aJumpUpText')); this.returnColor(document.getElementById('aJumpUp2'))}}  id="aJumpUp2" points="335,494 335,498 314,498 314,494"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aMaze')); this.textGreen(document.getElementById('aMazeText'))}} onMouseOut={() => {this.returnColor(document.getElementById('aMaze')); this.returnTextColor(document.getElementById('aMazeText'))}}  id="aMaze" points="286,290 336,290 336,336 286,336"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aNest')); this.textGreen(document.getElementById('aNestText'))}} onMouseOut={() => {this.returnColor(document.getElementById('aNest')); this.returnTextColor(document.getElementById('aNestText'))}}  id="aNest" points="286,290 314,290 314,336 286,336"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aPocket')); this.textGreen(document.getElementById('aPocketText')); this.turnGreen(document.getElementById('aPocket2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aPocket')); this.returnTextColor(document.getElementById('aPocketText')); this.returnColor(document.getElementById('aPocket2'))}}  id="aPocket" points="302,75 316,75 316,99 302,99"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aPocket')); this.textGreen(document.getElementById('aPocketText')); this.turnGreen(document.getElementById('aPocket2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aPocket')); this.returnTextColor(document.getElementById('aPocketText')); this.returnColor(document.getElementById('aPocket2'))}}  id="aPocket2" points="316,526 302,526 302,549 316,549"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aSneaky')); this.textGreen(document.getElementById('aSneakyText')); this.turnGreen(document.getElementById('aSneaky2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aSneaky')); this.returnTextColor(document.getElementById('aSneakyText')); this.returnColor(document.getElementById('aSneaky2'))}}  id="aSneaky" points="317,102 344,102 344,123 317,123"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aSneaky')); this.textGreen(document.getElementById('aSneakyText')); this.turnGreen(document.getElementById('aSneaky2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aSneaky')); this.returnTextColor(document.getElementById('aSneakyText')); this.returnColor(document.getElementById('aSneaky2'))}}  id="aSneaky2" points="317,501 344,501 344,524 317,524"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aStairs')); this.textGreen(document.getElementById('aStairsText')); this.turnGreen(document.getElementById('aStairs2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aStairs')); this.returnTextColor(document.getElementById('aStairsText')); this.returnColor(document.getElementById('aStairs2'))}}  id="aStairs" points="241,77 241,51 285,51 285,77"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aStairs')); this.textGreen(document.getElementById('aStairsText')); this.turnGreen(document.getElementById('aStairs2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aStairs')); this.returnTextColor(document.getElementById('aStairsText')); this.returnColor(document.getElementById('aStairs2'))}}  id="aStairs2" points="285,549 239,549 239,573 285,573"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aStandup')); this.textGreen(document.getElementById('aStandupText')); this.turnGreen(document.getElementById('aStandup2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aStandup')); this.returnTextColor(document.getElementById('aStandupText')); this.returnColor(document.getElementById('aStandup2'))}}  id="aStandup" points="148,119 148,81 180,81 180,119"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aStandup')); this.textGreen(document.getElementById('aStandupText')); this.turnGreen(document.getElementById('aStandup2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aStandup')); this.returnTextColor(document.getElementById('aStandupText')); this.returnColor(document.getElementById('aStandup2'))}}  id="aStandup2" points="149,508 179,508 179,546 149,546"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aStreet')); this.textGreen(document.getElementById('aStreetText')); this.turnGreen(document.getElementById('aStreet2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aStreet')); this.returnTextColor(document.getElementById('aStreetText')); this.returnColor(document.getElementById('aStreet2'))}}  id="aStreet" points="180,272 180,125 148,125 148,272"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aStreet')); this.textGreen(document.getElementById('aStreetText')); this.turnGreen(document.getElementById('aStreet2'))}} onMouseOut={() => {this.returnColor(document.getElementById('aStreet')); this.returnTextColor(document.getElementById('aStreetText')); this.returnColor(document.getElementById('aStreet2'))}}  id="aStreet2" points="180,349 148,349 148,497 180,497"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aTeepee')); this.textGreen(document.getElementById('aTeepeeText'))}} onMouseOut={() => {this.returnColor(document.getElementById('aTeepee')); this.returnTextColor(document.getElementById('aTeepeeText'))}}  id="aTeepee" points="254,274 285,274 285,349 254,349"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('aTunnel')); this.textGreen(document.getElementById('aTunnelText'))}} onMouseOut={() => {this.returnColor(document.getElementById('aTunnel')); this.returnTextColor(document.getElementById('aTunnelText'))}}  id="aTunnel" points="148,274 180,274 180,347 148,347"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('topAOnslaught')); this.textGreen(document.getElementById('topAOnslaughtText'))}} onMouseOut={() => {this.returnColor(document.getElementById('topAOnslaught')); this.returnTextColor(document.getElementById('topAOnslaughtText'))}}  id="topAOnslaught" points="241,273 148,273 148,348 241,348"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bCorner')); this.textGreen(document.getElementById('bCornerText')); this.turnGreen(document.getElementById('bCorner2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bCorner')); this.returnTextColor(document.getElementById('bCornerText')); this.returnColor(document.getElementById('bCorner2'))}}  id="bCorner" points="521,50 521,23 575,23 575,50"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bCorner')); this.textGreen(document.getElementById('bCornerText')); this.turnGreen(document.getElementById('bCorner2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bCorner')); this.returnTextColor(document.getElementById('bCornerText')); this.returnColor(document.getElementById('bCorner2'))}}  id="bCorner2" points="519,573 575,573 575,597 519,597"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bCuts')); this.textGreen(document.getElementById('bCutsText')); this.turnGreen(document.getElementById('bCuts2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bCuts')); this.returnTextColor(document.getElementById('bCutsText')); this.returnColor(document.getElementById('bCuts2'))}}  id="bCuts" points="431,248 402,248 402,282 431,282"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bCuts')); this.textGreen(document.getElementById('bCutsText')); this.turnGreen(document.getElementById('bCuts2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bCuts')); this.returnTextColor(document.getElementById('bCutsText')); this.returnColor(document.getElementById('bCuts2'))}}  id="bCuts2" points="431,343 403,343 403,378 431,378"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bDumpster')); this.textGreen(document.getElementById('bDumpsterText')); this.turnGreen(document.getElementById('bDumpster2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bDumpster')); this.returnTextColor(document.getElementById('bDumpsterText')); this.returnColor(document.getElementById('bDumpster2'))}}  id="bDumpster" points="482,97 514,124 508,130 476,102"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bDumpster')); this.textGreen(document.getElementById('bDumpsterText')); this.turnGreen(document.getElementById('bDumpster2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bDumpster')); this.returnTextColor(document.getElementById('bDumpsterText')); this.returnColor(document.getElementById('bDumpster2'))}}  id="bDumpster2" points="510,497 477,524 481,528 514,501"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bHouse')); this.textGreen(document.getElementById('bHouseText')); this.turnGreen(document.getElementById('bHouse2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bHouse')); this.returnTextColor(document.getElementById('bHouseText')); this.returnColor(document.getElementById('bHouse2'))}}  id="bHouse" points="482,23 437,23 437,50 482,50"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bHouse')); this.textGreen(document.getElementById('bHouseText')); this.turnGreen(document.getElementById('bHouse2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bHouse')); this.returnTextColor(document.getElementById('bHouseText')); this.returnColor(document.getElementById('bHouse2'))}}  id="bHouse2" points="481,573 433,573 433,597 481,597"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bJumpUp')); this.textGreen(document.getElementById('bJumpUpText')); this.turnGreen(document.getElementById('bJumpUp2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bJumpUp')); this.returnTextColor(document.getElementById('bJumpUpText')); this.returnColor(document.getElementById('bJumpUp2'))}}  id="bJumpUp" points="386,126 409,126 409,131 386,131"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bJumpUp')); this.textGreen(document.getElementById('bJumpUpText')); this.turnGreen(document.getElementById('bJumpUp2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bJumpUp')); this.returnTextColor(document.getElementById('bJumpUpText')); this.returnColor(document.getElementById('bJumpUp2'))}}  id="bJumpUp2" points="387,494 408,494 408,498 387,498"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bMaze')); this.textGreen(document.getElementById('bMazeText'))}} onMouseOut={() => {this.returnColor(document.getElementById('bMaze')); this.returnTextColor(document.getElementById('bMazeText'))}}  id="bMaze" points="380,290 434,290 434,336 380,336"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bNest')); this.textGreen(document.getElementById('bNestText')); this.turnGreen(document.getElementById('bNest'))}} onMouseOut={() => {this.returnColor(document.getElementById('bNest')); this.returnTextColor(document.getElementById('bNestText')); this.returnColor(document.getElementById('bNest'))}}  id="bNest" points="434,290 403,290 404,336 434,336"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bPocket')); this.textGreen(document.getElementById('bPocketText')); this.turnGreen(document.getElementById('bPocket2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bPocket')); this.returnTextColor(document.getElementById('bPocketText')); this.returnColor(document.getElementById('bPocket2'))}}  id="bPocket" points="419,76 407,76 407,98 419,98"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bPocket')); this.textGreen(document.getElementById('bPocketText')); this.turnGreen(document.getElementById('bPocket2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bPocket')); this.returnTextColor(document.getElementById('bPocketText')); this.returnColor(document.getElementById('bPocket2'))}}  id="bPocket2" points="406,526 419,526 419,548 406,548"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bSneaky')); this.textGreen(document.getElementById('bSneakyText'))}} onMouseOut={() => {this.returnColor(document.getElementById('bSneaky')); this.returnTextColor(document.getElementById('bSneakyText'))}}  id="bSneaky" points="405,501 377,501 377,524 405,524"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bStairs')); this.textGreen(document.getElementById('bStairsText')); this.turnGreen(document.getElementById('bStairs2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bStairs')); this.returnTextColor(document.getElementById('bStairsText')); this.returnColor(document.getElementById('bStairs2'))}}  id="bStairs" points="482,51 437,51 437,77 482,77"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bStairs')); this.textGreen(document.getElementById('bStairsText')); this.turnGreen(document.getElementById('bStairs2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bStairs')); this.returnTextColor(document.getElementById('bStairsText')); this.returnColor(document.getElementById('bStairs2'))}}  id="bStairs2" points="481,548 433,548 433,572 481,572"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bStandup')); this.textGreen(document.getElementById('bStandupText')); this.turnGreen(document.getElementById('bStandup2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bStandup')); this.returnTextColor(document.getElementById('bStandupText')); this.returnColor(document.getElementById('bStandup2'))}}  id="bStandup" points="576,131 576,92 541,92 541,131"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bStandup')); this.textGreen(document.getElementById('bStandupText')); this.turnGreen(document.getElementById('bStandup2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bStandup')); this.returnTextColor(document.getElementById('bStandupText')); this.returnColor(document.getElementById('bStandup2'))}}  id="bStandup2" points="541,494 576,494 576,529 541,529"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bStreet')); this.textGreen(document.getElementById('bStreetText')); this.turnGreen(document.getElementById('bStreet2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bStreet')); this.returnTextColor(document.getElementById('bStreetText')); this.returnColor(document.getElementById('bStreet2'))}}  id="bStreet" points="541,274 576,274 576,132 541,132"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bStreet')); this.textGreen(document.getElementById('bStreetText')); this.turnGreen(document.getElementById('bStreet2'))}} onMouseOut={() => {this.returnColor(document.getElementById('bStreet')); this.returnTextColor(document.getElementById('bStreetText')); this.returnColor(document.getElementById('bStreet2'))}}  id="bStreet2" points="541,350 575,350 575,493 541,493"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bTeepee')); this.textGreen(document.getElementById('bTeepeeText'))}} onMouseOut={() => {this.returnColor(document.getElementById('bTeepee')); this.returnTextColor(document.getElementById('bTeepeeText'))}}  id="bTeepee" points="439,273 466,273 466,348 439,348"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('bTunnel')); this.textGreen(document.getElementById('bTunnelText'))}} onMouseOut={() => {this.returnColor(document.getElementById('bTunnel')); this.returnTextColor(document.getElementById('bTunnelText'))}}  id="bTunnel" points="575,276 541,276 541,348 575,348"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('topBOnslaught')); this.textGreen(document.getElementById('topBOnslaughtText'))}} onMouseOut={() => {this.returnColor(document.getElementById('topBOnslaught')); this.returnTextColor(document.getElementById('topBOnslaughtText'))}}  id="topBOnslaught" points="575,275 481,275 481,349 575,349"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('basement')); this.textGreen(document.getElementById('basementText')); this.turnGreen(document.getElementById('basement2'))}} onMouseOut={() => {this.returnColor(document.getElementById('basement')); this.returnTextColor(document.getElementById('basementText')); this.returnColor(document.getElementById('basement2'))}}  id="basement" points="285,77 285,101 436,101 436,77"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('basement')); this.textGreen(document.getElementById('basementText')); this.turnGreen(document.getElementById('basement2'))}} onMouseOut={() => {this.returnColor(document.getElementById('basement')); this.returnTextColor(document.getElementById('basementText')); this.returnColor(document.getElementById('basement2'))}}  id="basement2" points="285,548 285,525 433,525 433,548"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('courtyard')); this.textGreen(document.getElementById('courtyardText')); this.turnGreen(document.getElementById('courtyard2'))}} onMouseOut={() => {this.returnColor(document.getElementById('courtyard')); this.returnTextColor(document.getElementById('courtyardText')); this.returnColor(document.getElementById('courtyard2'))}}  id="courtyard" points="283,142 435,142 435,242 283,242"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('courtyard')); this.textGreen(document.getElementById('courtyardText')); this.turnGreen(document.getElementById('courtyard2'))}} onMouseOut={() => {this.returnColor(document.getElementById('courtyard')); this.returnTextColor(document.getElementById('courtyardText')); this.returnColor(document.getElementById('courtyard2'))}}  id="courtyard2" points="284,479 284,385 440,385 440,479"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('flag')); this.textGreen(document.getElementById('flagText')); this.turnGreen(document.getElementById('flag2'))}} onMouseOut={() => {this.returnColor(document.getElementById('flag')); this.returnTextColor(document.getElementById('flagText')); this.returnColor(document.getElementById('flag2'))}}  id="flag" points="345,51 378,51 378,77 345,77"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('flag')); this.textGreen(document.getElementById('flagText')); this.turnGreen(document.getElementById('flag2'))}} onMouseOut={() => {this.returnColor(document.getElementById('flag')); this.returnTextColor(document.getElementById('flagText')); this.returnColor(document.getElementById('flag2'))}}  id="flag2" points="374,548 346,548 346,574 374,574"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('garageDoor')); this.textGreen(document.getElementById('garageDoorText')); this.turnGreen(document.getElementById('garageDoor2'))}} onMouseOut={() => {this.returnColor(document.getElementById('garageDoor')); this.returnTextColor(document.getElementById('garageDoorText')); this.returnColor(document.getElementById('garageDoor2'))}}  id="garageDoor" points="583,120 595,120 595,189 583,189"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('garageDoor')); this.textGreen(document.getElementById('garageDoorText')); this.turnGreen(document.getElementById('garageDoor2'))}} onMouseOut={() => {this.returnColor(document.getElementById('garageDoor')); this.returnTextColor(document.getElementById('garageDoorText')); this.returnColor(document.getElementById('garageDoor2'))}}  id="garageDoor2" points="583,442 595,442 595,512 583,512"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('shield')); this.textGreen(document.getElementById('shieldText')); this.turnGreen(document.getElementById('shield2'))}} onMouseOut={() => {this.returnColor(document.getElementById('shield')); this.returnTextColor(document.getElementById('shieldText')); this.returnColor(document.getElementById('shield2'))}}  id="shield" points="368,22 351,22 351,39 368,39"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('shield')); this.textGreen(document.getElementById('shieldText')); this.turnGreen(document.getElementById('shield2'))}} onMouseOut={() => {this.returnColor(document.getElementById('shield')); this.returnTextColor(document.getElementById('shieldText')); this.returnColor(document.getElementById('shield2'))}}  id="shield2" points="377,582 343,582 343,597 377,597"/>


                    

                </svg>
                <div className="inGamePic">
                    <h2 id="onslaughtInGamePicText" class="inGamePicText"></h2>
                    <img id="onslaughtScreenShot"></img>
                </div>
            </div>
        );
    }
}

export default Onslaught;

/*
A Corner ""
A Dumpster
A House
A Jump Up
A Pocket
A Sneaky
A Stairs
A Standup
A Street
A Cuts
B Corner
B Dumpster
B House
B Jump Up
B Pocket
B Sneaky
B Stairs
B Standup
B Street
B Cuts
Basement
Courtyard
Flag
Garage Door
Shield
Window


Top A "241,273 241,348 148,348 148,273"
A Tunnel "148,274 180,274 180,347 148,347"
A Teepee "254,274 285,274 285,349 254,349"
A Maze "286,290 334,290 334,336 286,336"
A Nest = same as A Maze
Bottom Mid "337,305 379,305 379,318 337,318"
B Maze "434,290 383,290 383,336 434,336"
B Nest = same as B Maze
B Teepee "439,273 466,273 466,348 439,348"
Top B "575,275 481,275 481,349 575,349"
B Tunnel "541,276 575,276 575,348 541,348"
*/

