import React from 'react';
import thePitBlank from './BlueprintPics/thePitBPs/ThePitBlank.png';
import firstBR from './BlueprintPics/thePitBPs/1stBR.png';
import secondBR from './BlueprintPics/thePitBPs/2ndBR.png';
import Assault from './BlueprintPics/thePitBPs/Assault.png';
import backRamp from './BlueprintPics/thePitBPs/backRamp.png';
import courtyard from './BlueprintPics/thePitBPs/courtyard.png';
import customOS from './BlueprintPics/thePitBPs/customOS.png';
import cuts from './BlueprintPics/thePitBPs/cuts.png';
import flag from './BlueprintPics/thePitBPs/flag.png';
import greenBox from './BlueprintPics/thePitBPs/greenBox.png';
import greenHall from './BlueprintPics/thePitBPs/greenHall.png';
import jumpUp from './BlueprintPics/thePitBPs/jumpUp.png';
import longHallCamo from './BlueprintPics/thePitBPs/longHallCamo.png';
import mauler from './BlueprintPics/thePitBPs/mauler.png';
import midBridge from './BlueprintPics/thePitBPs/midBridge.png';
import needler from './BlueprintPics/thePitBPs/needler.png';
import needlerPit from './BlueprintPics/thePitBPs/needlerPit.png';
import needlerRamp from './BlueprintPics/thePitBPs/needlerRamp.png';
import pit from './BlueprintPics/thePitBPs/pit.png';
import pitRamp from './BlueprintPics/thePitBPs/pitRamp.png';
import platform from './BlueprintPics/thePitBPs/platform.png';
import rockets from './BlueprintPics/thePitBPs/rockets.png';
import runway from './BlueprintPics/thePitBPs/runway.png';
import s1 from './BlueprintPics/thePitBPs/s1.png';
import s2 from './BlueprintPics/thePitBPs/s2.png';
import snipeBridge from './BlueprintPics/thePitBPs/snipeBridge.png';
import snipePocket from './BlueprintPics/thePitBPs/snipePocket.png';
import street from './BlueprintPics/thePitBPs/street.png';
import sword from './BlueprintPics/thePitBPs/sword.png';
import swordRamp from './BlueprintPics/thePitBPs/swordRamp.png';
import swordWindow from './BlueprintPics/thePitBPs/swordWindow.png';
import training from './BlueprintPics/thePitBPs/training.png';
import trainingPocket from './BlueprintPics/thePitBPs/trainingPocket.png';
import trainingRamp from './BlueprintPics/thePitBPs/trainingRamp.png';
import walshy from './BlueprintPics/thePitBPs/walshy.png';

class ThePit extends React.Component{
    turnGreen(div){
        div.style.fill="rgba(0, 255, 0, 0.5)";
    }
    returnColor(div){
        div.style.fill="rgba(0, 0, 0, 0)";
    }
    textGreen(textP){
        textP.style.color="rgba(0, 255, 0, 1)"
    }
    returnTextColor(textP){
        textP.style.color="white";
    }
    render(){
        return(
            <div className="thePitFullGrid">
                <h1 className="mapTitleThePit">The Pit</h1>
                <div className="calloutsList" id="pitCallouts">
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('firstBrPit')); this.textGreen(document.getElementById('firstBrPitText')); this.turnGreen(document.getElementById('firstBrPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('firstBrPit')); this.returnTextColor(document.getElementById('firstBrPitText')); this.returnColor(document.getElementById('firstBrPit2'))}} id="firstBrPitText">1st BR</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('secondBrPit')); this.textGreen(document.getElementById('secondBrPitText')); this.turnGreen(document.getElementById('secondBrPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('secondBrPit')); this.returnTextColor(document.getElementById('secondBrPitText')); this.returnColor(document.getElementById('secondBrPit2'))}} id="secondBrPitText">2nd BR</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('assaultPit')); this.textGreen(document.getElementById('assaultPitText')); this.turnGreen(document.getElementById('assaultPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('assaultPit')); this.returnTextColor(document.getElementById('assaultPitText')); this.returnColor(document.getElementById('assaultPit2'))}} id="assaultPitText">Assault</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('backRampPit')); this.textGreen(document.getElementById('backRampPitText')); this.turnGreen(document.getElementById('backRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('backRampPit')); this.returnTextColor(document.getElementById('backRampPitText')); this.returnColor(document.getElementById('backRampPit2'))}} id="backRampPitText">Back Ramp</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('courtyardPit')); this.textGreen(document.getElementById('courtyardPitText')); this.turnGreen(document.getElementById('courtyardPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('courtyardPit')); this.returnTextColor(document.getElementById('courtyardPitText')); this.returnColor(document.getElementById('courtyardPit2'))}} id="courtyardPitText">Courtyard</p>

                    <p onMouseOver={() => {this.turnGreen(document.getElementById('customOsPit')); this.textGreen(document.getElementById('customOsPitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('customOsPit')); this.returnTextColor(document.getElementById('customOsPitText'))}} id="customOsPitText">Custom/OS</p>
                
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('cutsPit')); this.textGreen(document.getElementById('cutsPitText')); this.turnGreen(document.getElementById('cutsPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('cutsPit')); this.returnTextColor(document.getElementById('cutsPitText')); this.returnColor(document.getElementById('cutsPit2'))}} id="cutsPitText">Cuts</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('flagPit')); this.textGreen(document.getElementById('flagPitText')); this.turnGreen(document.getElementById('flagPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('flagPit')); this.returnTextColor(document.getElementById('flagPitText')); this.returnColor(document.getElementById('flagPit2'))}} id="flagPitText">Flag</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('greenBoxPit')); this.textGreen(document.getElementById('greenBoxPitText')); this.turnGreen(document.getElementById('greenBoxPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('greenBoxPit')); this.returnTextColor(document.getElementById('greenBoxPitText')); this.returnColor(document.getElementById('greenBoxPit2'))}} id="greenBoxPitText">Green Box</p>

                    <p onMouseOver={() => {this.turnGreen(document.getElementById('greenHallPit')); this.textGreen(document.getElementById('greenHallPitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('greenHallPit')); this.returnTextColor(document.getElementById('greenHallPitText'))}} id="greenHallPitText">Green Hall</p>

                    <p onMouseOver={() => {this.turnGreen(document.getElementById('jumpUpPit')); this.textGreen(document.getElementById('jumpUpPitText')); this.turnGreen(document.getElementById('jumpUpPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('jumpUpPit')); this.returnTextColor(document.getElementById('jumpUpPitText')); this.returnColor(document.getElementById('jumpUpPit2'))}} id="jumpUpPitText">Jump Up</p>

                    <p onMouseOver={() => {this.turnGreen(document.getElementById('longHallCamoPit')); this.textGreen(document.getElementById('longHallCamoPitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('longHallCamoPit')); this.returnTextColor(document.getElementById('longHallCamoPitText'))}} id="longHallCamoPitText">Long Hall/Camo</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('midBridgePit')); this.textGreen(document.getElementById('midBridgePitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('midBridgePit')); this.returnTextColor(document.getElementById('midBridgePitText'))}} id="midBridgePitText">Mid Bridge</p>

                    <p onMouseOver={() => {this.turnGreen(document.getElementById('maulerPit')); this.textGreen(document.getElementById('maulerPitText')); this.turnGreen(document.getElementById('maulerPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('maulerPit')); this.returnTextColor(document.getElementById('maulerPitText')); this.returnColor(document.getElementById('maulerPit2'))}} id="maulerPitText">Mauler</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('needlerPit')); this.textGreen(document.getElementById('needlerPitText')); this.turnGreen(document.getElementById('needlerPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('needlerPit')); this.returnTextColor(document.getElementById('needlerPitText')); this.returnColor(document.getElementById('needlerPit2'))}} id="needlerPitText">Needler</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('needlerPitPit')); this.textGreen(document.getElementById('needlerPitPitText')); this.turnGreen(document.getElementById('needlerPitPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('needlerPitPit')); this.returnTextColor(document.getElementById('needlerPitPitText')); this.returnColor(document.getElementById('needlerPitPit2'))}} id="needlerPitPitText">Needler Pit</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('needlerRampPit')); this.textGreen(document.getElementById('needlerRampPitText')); this.turnGreen(document.getElementById('needlerRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('needlerRampPit')); this.returnTextColor(document.getElementById('needlerRampPitText')); this.returnColor(document.getElementById('needlerRampPit2'))}} id="needlerRampPitText">Needler Ramp</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('pitPit')); this.textGreen(document.getElementById('pitPitText')); this.turnGreen(document.getElementById('pitPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pitPit')); this.returnTextColor(document.getElementById('pitPitText')); this.returnColor(document.getElementById('pitPit2'))}} id="pitPitText">Pit</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('pitRampPit')); this.textGreen(document.getElementById('pitRampPitText')); this.turnGreen(document.getElementById('pitRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pitRampPit')); this.returnTextColor(document.getElementById('pitRampPitText')); this.returnColor(document.getElementById('pitRampPit2'))}} id="pitRampPitText">Pit Ramp</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('platformPit')); this.textGreen(document.getElementById('platformPitText')); this.turnGreen(document.getElementById('platformPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('platformPit')); this.returnTextColor(document.getElementById('platformPitText')); this.returnColor(document.getElementById('platformPit2'))}} id="platformPitText">Platform</p>

                    <p onMouseOver={() => {this.turnGreen(document.getElementById('rocketsPit')); this.textGreen(document.getElementById('rocketsPitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('rocketsPit')); this.returnTextColor(document.getElementById('rocketsPitText'))}} id="rocketsPitText">Rockets</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('runwayPit')); this.textGreen(document.getElementById('runwayPitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('runwayPit')); this.returnTextColor(document.getElementById('runwayPitText'))}} id="runwayPitText">Runway</p>

                    <p onMouseOver={() => {this.turnGreen(document.getElementById('snipeBridgePit')); this.textGreen(document.getElementById('snipeBridgePitText')); this.turnGreen(document.getElementById('snipeBridgePit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('snipeBridgePit')); this.returnTextColor(document.getElementById('snipeBridgePitText')); this.returnColor(document.getElementById('snipeBridgePit2'))}} id="snipeBridgePitText">Snipe Bridge</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('snipePocketPit')); this.textGreen(document.getElementById('snipePocketPitText')); this.turnGreen(document.getElementById('snipePocketPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('snipePocketPit')); this.returnTextColor(document.getElementById('snipePocketPitText')); this.returnColor(document.getElementById('snipePocketPit2'))}} id="snipePocketPitText">Snipe Pocket</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('streetPit')); this.textGreen(document.getElementById('streetPitText')); this.turnGreen(document.getElementById('streetPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('streetPit')); this.returnTextColor(document.getElementById('streetPitText')); this.returnColor(document.getElementById('streetPit2'))}} id="streetPitText">Street</p>

                    <p onMouseOver={() => {this.turnGreen(document.getElementById('swordPit')); this.textGreen(document.getElementById('swordPitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('swordPit')); this.returnTextColor(document.getElementById('swordPitText'))}} id="swordPitText">Sword</p>

                    <p onMouseOver={() => {this.turnGreen(document.getElementById('swordRampPit')); this.textGreen(document.getElementById('swordRampPitText')); this.turnGreen(document.getElementById('swordRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('swordRampPit')); this.returnTextColor(document.getElementById('swordRampPitText')); this.returnColor(document.getElementById('swordRampPit2'))}} id="swordRampPitText">Sword Ramp</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('swordWindowPit')); this.textGreen(document.getElementById('swordWindowPitText')); this.turnGreen(document.getElementById('swordWindowPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('swordWindowPit')); this.returnTextColor(document.getElementById('swordWindowPitText')); this.returnColor(document.getElementById('swordWindowPit2'))}} id="swordWindowPitText">Sword Window</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('s1Pit')); this.textGreen(document.getElementById('s1PitText')); this.turnGreen(document.getElementById('s1Pit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('s1Pit')); this.returnTextColor(document.getElementById('s1PitText')); this.returnColor(document.getElementById('s1Pit2'))}} id="s1PitText">S1</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('s2Pit')); this.textGreen(document.getElementById('s2PitText')); this.turnGreen(document.getElementById('s2Pit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('s2Pit')); this.returnTextColor(document.getElementById('s2PitText')); this.returnColor(document.getElementById('s2Pit2'))}} id="s2PitText">S2</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('trainingPit')); this.textGreen(document.getElementById('trainingPitText')); this.turnGreen(document.getElementById('trainingPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('trainingPit')); this.returnTextColor(document.getElementById('trainingPitText')); this.returnColor(document.getElementById('trainingPit2'))}} id="trainingPitText">Training Pit</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('trainingRampPit')); this.textGreen(document.getElementById('trainingRampPitText')); this.turnGreen(document.getElementById('trainingRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('trainingRampPit')); this.returnTextColor(document.getElementById('trainingRampPitText')); this.returnColor(document.getElementById('trainingRampPit2'))}} id="trainingRampPitText">Training Ramp</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('trainingPocketPit')); this.textGreen(document.getElementById('trainingPocketPitText')); this.turnGreen(document.getElementById('trainingPocketPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('trainingPocketPit')); this.returnTextColor(document.getElementById('trainingPocketPitText')); this.returnColor(document.getElementById('trainingPocketPit2'))}} id="trainingPocketPitText">Training Pocket</p>
                    <p onMouseOver={() => {this.turnGreen(document.getElementById('walshyPit')); this.textGreen(document.getElementById('walshyPitText')); this.turnGreen(document.getElementById('walshyPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('walshyPit')); this.returnTextColor(document.getElementById('walshyPitText')); this.returnColor(document.getElementById('walshyPit2'))}} id="walshyPitText">Walshy</p>
                </div>
                <svg id="thePitMap" width="750px" height="625px">
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('firstBrPit')); this.textGreen(document.getElementById('firstBrPitText')); this.turnGreen(document.getElementById('firstBrPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('firstBrPit')); this.returnTextColor(document.getElementById('firstBrPitText')); this.returnColor(document.getElementById('firstBrPit2'))}}  id="firstBrPit" points="128,489 193,489 193,507 166,507 166,510 128, 510"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('firstBrPit')); this.textGreen(document.getElementById('firstBrPitText')); this.turnGreen(document.getElementById('firstBrPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('firstBrPit')); this.returnTextColor(document.getElementById('firstBrPitText')); this.returnColor(document.getElementById('firstBrPit2'))}}  id="firstBrPit2" points="562,489 626,489 626,510 589,510 589,507 562,507"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('secondBrPit')); this.textGreen(document.getElementById('secondBrPitText')); this.turnGreen(document.getElementById('secondBrPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('secondBrPit')); this.returnTextColor(document.getElementById('secondBrPitText')); this.returnColor(document.getElementById('secondBrPit2'))}}  id="secondBrPit" points="288,469 323,469 323,526 311,535 300,535 300,497 288,485"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('secondBrPit')); this.textGreen(document.getElementById('secondBrPitText')); this.turnGreen(document.getElementById('secondBrPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('secondBrPit')); this.returnTextColor(document.getElementById('secondBrPitText')); this.returnColor(document.getElementById('secondBrPit2'))}}  id="secondBrPit2" points="432,469 467,469 467,485 456,497 456,535 444,535 432,526"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('assaultPit')); this.textGreen(document.getElementById('assaultPitText')); this.turnGreen(document.getElementById('assaultPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('assaultPit')); this.returnTextColor(document.getElementById('assaultPitText')); this.returnColor(document.getElementById('assaultPit2'))}}  id="assaultPit" points="170,333 212,333 212,373 170,373"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('assaultPit')); this.textGreen(document.getElementById('assaultPitText')); this.turnGreen(document.getElementById('assaultPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('assaultPit')); this.returnTextColor(document.getElementById('assaultPitText')); this.returnColor(document.getElementById('assaultPit2'))}}  id="assaultPit2" points="587,333 544,333 544,373 587,373"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('backRampPit')); this.textGreen(document.getElementById('backRampPitText')); this.turnGreen(document.getElementById('backRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('backRampPit')); this.returnTextColor(document.getElementById('backRampPitText')); this.returnColor(document.getElementById('backRampPit2'))}}  id="backRampPit" points="166,253 154,253 154,338 166,338"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('backRampPit')); this.textGreen(document.getElementById('backRampPitText')); this.turnGreen(document.getElementById('backRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('backRampPit')); this.returnTextColor(document.getElementById('backRampPitText')); this.returnColor(document.getElementById('backRampPit2'))}}  id="backRampPit2" points="601,253 589,253 589,335 601,335"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('courtyardPit')); this.textGreen(document.getElementById('courtyardPitText')); this.turnGreen(document.getElementById('courtyardPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('courtyardPit')); this.returnTextColor(document.getElementById('courtyardPitText')); this.returnColor(document.getElementById('courtyardPit2'))}}  id="courtyardPit" points="153,199 230,199 230,247 153,247"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('courtyardPit')); this.textGreen(document.getElementById('courtyardPitText')); this.turnGreen(document.getElementById('courtyardPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('courtyardPit')); this.returnTextColor(document.getElementById('courtyardPitText')); this.returnColor(document.getElementById('courtyardPit2'))}}  id="courtyardPit2" points="602,199 525,199 525,247 602,247"/>

                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('customOsPit')); this.textGreen(document.getElementById('customOsPitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('customOsPit')); this.returnTextColor(document.getElementById('customOsPitText'))}}  id="customOsPit" points="369,249 386,249 386,255 393,255 393,285 362,285 362,255 369,255"/>

                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('cutsPit')); this.textGreen(document.getElementById('cutsPitText')); this.turnGreen(document.getElementById('cutsPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('cutsPit')); this.returnTextColor(document.getElementById('cutsPitText')); this.returnColor(document.getElementById('cutsPit2'))}}  id="cutsPit" points="188,405 188,374 170,374 170,376 153,376 128,409 147,409 147,405"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('cutsPit')); this.textGreen(document.getElementById('cutsPitText')); this.turnGreen(document.getElementById('cutsPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('cutsPit')); this.returnTextColor(document.getElementById('cutsPitText')); this.returnColor(document.getElementById('cutsPit2'))}}  id="cutsPit2" points="567,374 586,374 586,378 603,378 628,409 608,409 608,405 567,405"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('flagPit')); this.textGreen(document.getElementById('flagPitText')); this.turnGreen(document.getElementById('flagPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('flagPit')); this.returnTextColor(document.getElementById('flagPitText')); this.returnColor(document.getElementById('flagPit2'))}}  id="flagPit" points="145,410 145,420 179,420 179,432 189,432 189,461 179,461 179,474 126,474 126,476 110,476 110,412 125,412 127,410"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('flagPit')); this.textGreen(document.getElementById('flagPitText')); this.turnGreen(document.getElementById('flagPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('flagPit')); this.returnTextColor(document.getElementById('flagPitText')); this.returnColor(document.getElementById('flagPit2'))}}  id="flagPit2" points="610,410 628,410 630,412 645,412 645,476 630,476 630,474 577,474 577,461 567,461 567,432 575,432 575,420 610,420"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('greenBoxPit')); this.textGreen(document.getElementById('greenBoxPitText')); this.turnGreen(document.getElementById('greenBoxPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('greenBoxPit')); this.returnTextColor(document.getElementById('greenBoxPitText')); this.returnColor(document.getElementById('greenBoxPit2'))}}  id="greenBoxPit" points="323,422 285,422 285,464 323,464"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('greenBoxPit')); this.textGreen(document.getElementById('greenBoxPitText')); this.turnGreen(document.getElementById('greenBoxPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('greenBoxPit')); this.returnTextColor(document.getElementById('greenBoxPitText')); this.returnColor(document.getElementById('greenBoxPit2'))}}  id="greenBoxPit2" points="470,422 432,422 432,464 470,464"/>

                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('greenHallPit')); this.textGreen(document.getElementById('greenHallPitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('greenHallPit')); this.returnTextColor(document.getElementById('greenHallPitText'))}}  id="greenHallPit" points="324,433 431,433 431,452 324,452"/>

                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('jumpUpPit')); this.textGreen(document.getElementById('jumpUpPitText')); this.turnGreen(document.getElementById('jumpUpPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('jumpUpPit')); this.returnTextColor(document.getElementById('jumpUpPitText')); this.returnColor(document.getElementById('jumpUpPit2'))}}  id="jumpUpPit" points="234,394 221,394 221,406 234,419"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('jumpUpPit')); this.textGreen(document.getElementById('jumpUpPitText')); this.turnGreen(document.getElementById('jumpUpPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('jumpUpPit')); this.returnTextColor(document.getElementById('jumpUpPitText')); this.returnColor(document.getElementById('jumpUpPit2'))}}  id="jumpUpPit2" points="535,395 525,395 525,416 535,406"/>

                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('longHallCamoPit')); this.textGreen(document.getElementById('longHallCamoPitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('longHallCamoPit')); this.returnTextColor(document.getElementById('longHallCamoPitText'))}}  id="longHallCamoPit" points="415,544 415,556 340,556 340,544"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('midBridgePit')); this.textGreen(document.getElementById('midBridgePitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('midBridgePit')); this.returnTextColor(document.getElementById('midBridgePitText'))}}  id="midBridgePit" points="401,141 354,141 354,188 401,188"/>

                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('maulerPit')); this.textGreen(document.getElementById('maulerPitText')); this.turnGreen(document.getElementById('maulerPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('maulerPit')); this.returnTextColor(document.getElementById('maulerPitText')); this.returnColor(document.getElementById('maulerPit2'))}}  id="maulerPit" points="183,570 166,570 141,544 125,544 125,512 113,512 113,557 137,582 183,582"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('maulerPit')); this.textGreen(document.getElementById('maulerPitText')); this.turnGreen(document.getElementById('maulerPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('maulerPit')); this.returnTextColor(document.getElementById('maulerPitText')); this.returnColor(document.getElementById('maulerPit2'))}}  id="maulerPit2" points="643,512 630,512 630,543 614,543 589,569 572,569 572,582 619,582 643,556"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('needlerPit')); this.textGreen(document.getElementById('needlerPitText')); this.turnGreen(document.getElementById('needlerPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('needlerPit')); this.returnTextColor(document.getElementById('needlerPitText')); this.returnColor(document.getElementById('needlerPit2'))}}  id="needlerPit" points="251,539 241,539 215,565 184,565 184,582 251,582"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('needlerPit')); this.textGreen(document.getElementById('needlerPitText')); this.turnGreen(document.getElementById('needlerPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('needlerPit')); this.returnTextColor(document.getElementById('needlerPitText')); this.returnColor(document.getElementById('needlerPit2'))}}  id="needlerPit2" points="571,565 541,565 514,539 504,539 504,582 571,582"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('needlerPitPit')); this.textGreen(document.getElementById('needlerPitPitText')); this.turnGreen(document.getElementById('needlerPitPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('needlerPitPit')); this.returnTextColor(document.getElementById('needlerPitPitText')); this.returnColor(document.getElementById('needlerPitPit2'))}}  id="needlerPitPit" points="246,511 194,511 194,530 172,530 184,542 184,562 213,562 240,536 246,536"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('needlerPitPit')); this.textGreen(document.getElementById('needlerPitPitText')); this.turnGreen(document.getElementById('needlerPitPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('needlerPitPit')); this.returnTextColor(document.getElementById('needlerPitPitText')); this.returnColor(document.getElementById('needlerPitPit2'))}}  id="needlerPitPit2" points="509,511 561,511 561,530 583,530 571,541 571,562 542,562 516,536 509,536"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('needlerRampPit')); this.textGreen(document.getElementById('needlerRampPitText')); this.turnGreen(document.getElementById('needlerRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('needlerRampPit')); this.returnTextColor(document.getElementById('needlerRampPitText')); this.returnColor(document.getElementById('needlerRampPit2'))}}  id="needlerRampPit" points="299,524 299,535 248,535 248,524"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('needlerRampPit')); this.textGreen(document.getElementById('needlerRampPitText')); this.turnGreen(document.getElementById('needlerRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('needlerRampPit')); this.returnTextColor(document.getElementById('needlerRampPitText')); this.returnColor(document.getElementById('needlerRampPit2'))}}  id="needlerRampPit2" points="508,524 508,535 457,535 457,524"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pitPit')); this.textGreen(document.getElementById('pitPitText')); this.turnGreen(document.getElementById('pitPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pitPit')); this.returnTextColor(document.getElementById('pitPitText')); this.returnColor(document.getElementById('pitPit2'))}}  id="pitPit" points="278,311 225,311 225,319 211,333 211,373 221,373 221,393 235,393 235,420 239,424 279,424 279,416 297,416 297,386 278,386"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pitPit')); this.textGreen(document.getElementById('pitPitText')); this.turnGreen(document.getElementById('pitPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pitPit')); this.returnTextColor(document.getElementById('pitPitText')); this.returnColor(document.getElementById('pitPit2'))}}  id="pitPit2" points="477,312 530,312 530,318 543,332 543,373 535,373 535,394 524,394 524,416 509,431 476,431 476,417 459,417 459,386 477,386"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pitRampPit')); this.textGreen(document.getElementById('pitRampPitText')); this.turnGreen(document.getElementById('pitRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pitRampPit')); this.returnTextColor(document.getElementById('pitRampPitText')); this.returnColor(document.getElementById('pitRampPit2'))}}  id="pitRampPit" points="297,347 279,347 279,385 297,385"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('pitRampPit')); this.textGreen(document.getElementById('pitRampPitText')); this.turnGreen(document.getElementById('pitRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('pitRampPit')); this.returnTextColor(document.getElementById('pitRampPitText')); this.returnColor(document.getElementById('pitRampPit2'))}}  id="pitRampPit2" points="476,347 459,347 459,385 476,385"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('platformPit')); this.textGreen(document.getElementById('platformPitText')); this.turnGreen(document.getElementById('platformPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('platformPit')); this.returnTextColor(document.getElementById('platformPitText')); this.returnColor(document.getElementById('platformPit2'))}}  id="platformPit" points="193,377 217,377 217,408 243,433 243,485 220,507 194,507 194,463 193,463 193,430 194,430 194,408 193,408"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('platformPit')); this.textGreen(document.getElementById('platformPitText')); this.turnGreen(document.getElementById('platformPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('platformPit')); this.returnTextColor(document.getElementById('platformPitText')); this.returnColor(document.getElementById('platformPit2'))}}  id="platformPit2" points="562,377 538,377 538,408 512,434 512,484 535,507 561,507 561,464 562,464"/>

                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('rocketsPit')); this.textGreen(document.getElementById('rocketsPitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('rocketsPit')); this.returnTextColor(document.getElementById('rocketsPitText'))}}  id="rocketsPit" points="387,453 387,462 368,462 368,453"/>

                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('runwayPit')); this.textGreen(document.getElementById('runwayPitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('runwayPit')); this.returnTextColor(document.getElementById('runwayPitText'))}}  id="runwayPit" points="297,199 458,199 458,218 297,218"/>

                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('snipeBridgePit')); this.textGreen(document.getElementById('snipeBridgePitText')); this.turnGreen(document.getElementById('snipeBridgePit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('snipeBridgePit')); this.returnTextColor(document.getElementById('snipeBridgePitText')); this.returnColor(document.getElementById('snipeBridgePit2'))}}  id="snipeBridgePit" points="121,331 109,331 109,362 121,362"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('snipeBridgePit')); this.textGreen(document.getElementById('snipeBridgePitText')); this.turnGreen(document.getElementById('snipeBridgePit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('snipeBridgePit')); this.returnTextColor(document.getElementById('snipeBridgePitText')); this.returnColor(document.getElementById('snipeBridgePit2'))}}  id="snipeBridgePit2" points="646,331 634,331 634,360 646,360"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('snipePocketPit')); this.textGreen(document.getElementById('snipePocketPitText')); this.turnGreen(document.getElementById('snipePocketPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('snipePocketPit')); this.returnTextColor(document.getElementById('snipePocketPitText')); this.returnColor(document.getElementById('snipePocketPit2'))}}  id="snipePocketPit" points="110,287 97,287 97,302 110,302"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('snipePocketPit')); this.textGreen(document.getElementById('snipePocketPitText')); this.turnGreen(document.getElementById('snipePocketPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('snipePocketPit')); this.returnTextColor(document.getElementById('snipePocketPitText')); this.returnColor(document.getElementById('snipePocketPit2'))}}  id="snipePocketPit2" points="646,287 658,287 658,301 646,301"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('streetPit')); this.textGreen(document.getElementById('streetPitText')); this.turnGreen(document.getElementById('streetPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('streetPit')); this.returnTextColor(document.getElementById('streetPitText')); this.returnColor(document.getElementById('streetPit2'))}}  id="streetPit" points="326,285 312,271 312,244 296,244 296,238 231,238 231,248 226,248 226,309 326,309"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('streetPit')); this.textGreen(document.getElementById('streetPitText')); this.turnGreen(document.getElementById('streetPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('streetPit')); this.returnTextColor(document.getElementById('streetPitText')); this.returnColor(document.getElementById('streetPit2'))}}  id="streetPit2" points="444,245 524,245 524,248 530,248 530,311 430,311 430,285 444,270"/>
                    
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('swordPit')); this.textGreen(document.getElementById('swordPitText'))}} onMouseOut={() => {this.returnColor(document.getElementById('swordPit')); this.returnTextColor(document.getElementById('swordPitText'))}}  id="swordPit" points="388,46 367,46 367,57 346,57 346,74 363,87 392,87 409,75 409,57 388,57"/>

                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('swordRampPit')); this.textGreen(document.getElementById('swordRampPitText')); this.turnGreen(document.getElementById('swordRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('swordRampPit')); this.returnTextColor(document.getElementById('swordRampPitText')); this.returnColor(document.getElementById('swordRampPit2'))}}  id="swordRampPit" points="247,82 300,82 300,92 247,92"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('swordRampPit')); this.textGreen(document.getElementById('swordRampPitText')); this.turnGreen(document.getElementById('swordRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('swordRampPit')); this.returnTextColor(document.getElementById('swordRampPitText')); this.returnColor(document.getElementById('swordRampPit2'))}}  id="swordRampPit2" points="455,82 507,82 507,92 455,92"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('swordWindowPit')); this.textGreen(document.getElementById('swordWindowPitText')); this.turnGreen(document.getElementById('swordWindowPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('swordWindowPit')); this.returnTextColor(document.getElementById('swordWindowPitText')); this.returnColor(document.getElementById('swordWindowPit2'))}}  id="swordWindowPit" points="334,96 334,110 343,119 357,119 357,136 326,136 318,129 318,96"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('swordWindowPit')); this.textGreen(document.getElementById('swordWindowPitText')); this.turnGreen(document.getElementById('swordWindowPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('swordWindowPit')); this.returnTextColor(document.getElementById('swordWindowPitText')); this.returnColor(document.getElementById('swordWindowPit2'))}}  id="swordWindowPit2" points="421,96 437,96 437,129 429,136 398,136 398,118 412,118 421,110"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('s1Pit')); this.textGreen(document.getElementById('s1PitText')); this.turnGreen(document.getElementById('s1Pit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('s1Pit')); this.returnTextColor(document.getElementById('s1PitText')); this.returnColor(document.getElementById('s1Pit2'))}}  id="s1Pit" points="183,275 212,275 212,280 216,280 216,283 222,283 222,292 217,292 215,294 213,294 213,307 183,307"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('s1Pit')); this.textGreen(document.getElementById('s1PitText')); this.turnGreen(document.getElementById('s1Pit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('s1Pit')); this.returnTextColor(document.getElementById('s1PitText')); this.returnColor(document.getElementById('s1Pit2'))}}  id="s1Pit2" points="573,275 543,275 543,280 539,280 539,283 533,283 533,292 538,292 540,294 543,294 543,307 573,307"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('s2Pit')); this.textGreen(document.getElementById('s2PitText')); this.turnGreen(document.getElementById('s2Pit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('s2Pit')); this.returnTextColor(document.getElementById('s2PitText')); this.returnColor(document.getElementById('s2Pit2'))}}  id="s2Pit" points="119,249 133,249 133,317 121,328 84,328 84,271 119,271"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('s2Pit')); this.textGreen(document.getElementById('s2PitText')); this.turnGreen(document.getElementById('s2Pit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('s2Pit')); this.returnTextColor(document.getElementById('s2PitText')); this.returnColor(document.getElementById('s2Pit2'))}}  id="s2Pit2" points="636,249 636,270 671,270 671,328 633,328 622,317 622,249"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('trainingPit')); this.textGreen(document.getElementById('trainingPitText')); this.turnGreen(document.getElementById('trainingPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('trainingPit')); this.returnTextColor(document.getElementById('trainingPitText')); this.returnColor(document.getElementById('trainingPit2'))}}  id="trainingPit" points="296,333 365,333 365,384 300,384 300,364 313,364 313,346 296,346"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('trainingPit')); this.textGreen(document.getElementById('trainingPitText')); this.turnGreen(document.getElementById('trainingPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('trainingPit')); this.returnTextColor(document.getElementById('trainingPitText')); this.returnColor(document.getElementById('trainingPit2'))}}  id="trainingPit2" points="458,333 458,346 442,346 442,363 455,363 455,384 390,384 390,333"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('trainingRampPit')); this.textGreen(document.getElementById('trainingRampPitText')); this.turnGreen(document.getElementById('trainingRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('trainingRampPit')); this.returnTextColor(document.getElementById('trainingRampPitText')); this.returnColor(document.getElementById('trainingRampPit2'))}}  id="trainingRampPit" points="356,315 282,315 282,329 356,329"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('trainingRampPit')); this.textGreen(document.getElementById('trainingRampPitText')); this.turnGreen(document.getElementById('trainingRampPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('trainingRampPit')); this.returnTextColor(document.getElementById('trainingRampPitText')); this.returnColor(document.getElementById('trainingRampPit2'))}}  id="trainingRampPit2" points="401,315 473,315 473,328 401,328"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('trainingPocketPit')); this.textGreen(document.getElementById('trainingPocketPitText')); this.turnGreen(document.getElementById('trainingPocketPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('trainingPocketPit')); this.returnTextColor(document.getElementById('trainingPocketPitText')); this.returnColor(document.getElementById('trainingPocketPit2'))}}  id="trainingPocketPit" points="312,351 300,351 300,363 312,363"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('trainingPocketPit')); this.textGreen(document.getElementById('trainingPocketPitText')); this.turnGreen(document.getElementById('trainingPocketPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('trainingPocketPit')); this.returnTextColor(document.getElementById('trainingPocketPitText')); this.returnColor(document.getElementById('trainingPocketPit2'))}}  id="trainingPocketPit2" points="455,350 443,350 443,362 455,362"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('walshyPit')); this.textGreen(document.getElementById('walshyPitText')); this.turnGreen(document.getElementById('walshyPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('walshyPit')); this.returnTextColor(document.getElementById('walshyPitText')); this.returnColor(document.getElementById('walshyPit2'))}}  id="walshyPit" points="271,511 287,511 287,490 296,500 296,519 271,519"/>
                    <polygon onMouseOver={() => {this.turnGreen(document.getElementById('walshyPit')); this.textGreen(document.getElementById('walshyPitText')); this.turnGreen(document.getElementById('walshyPit2'))}} onMouseOut={() => {this.returnColor(document.getElementById('walshyPit')); this.returnTextColor(document.getElementById('walshyPitText')); this.returnColor(document.getElementById('walshyPit2'))}}  id="walshyPit2" points="482,510 468,510 468,490 459,500 459,519 482,519"/>
                </svg>
                <div className="inGamePic">
                    <h2 id="thePitInGamePicText" class="inGamePicText"></h2>
                    <img id="thePitScreenShot"></img>
                </div>
            </div>
        );
    }
}

export default ThePit;

/*
1st BR "128,489 193,489 193,507 166,507 166,510 128, 510"
    "562,489 626,489 626,510 589,510 589,507 562,507"
2nd BR "288,469 323,469 323,526 311,535 300,535 300,497 288,485"
    "432,469 467,469 467,485 456,497 456,535 444,535 432,526"
Assault "170,333 212,333 212,373 170,373"
    "587,333 544,333 544,373 587,373"
Back Ramp "166,253 154,253 154,338 166,338"
    "601,253 589,253 589,335 601,335"
Courtyard "153,199 230,199 230,247 153,247"
    "602,199 525,199 525,247 602,247"
Custom/OS "369,249 386,249 386,255 393,255 393,285 362,285 362,255 369,255"
Cuts "188,405 188,374 170,374 170,376 153,376 128,409 147,409 147,405"
    "567,374 586,374 586,378 603,378 628,409 608,409 608,405 567,405"
Flag "145,410 145,420 179,420 179,432 189,432 189,461 179,461 179,474 126,474 126,476 110,476 110,412 125,412 127,410"
    "610,410 628,410 630,412 645,412 645,476 630,476 630,474 577,474 577,461 567,461 567,432 575,432 575,420 610,420"
Green Box "323,422 285,422 285,464 323,464"
    "470,422 432,422 432,464 470,464"
Green Hall "324,433 431,433 431,452 324,452"
Jump Up "234,394 221,394 221,406 234,419"
    "535,395 525,395 525,416 535,406"
Long Hall/Camo "415,544 415,556 340,556 340,544"
Mid Bridge "401,141 354,141 354,188 401,188"
Mauler "183,570 166,570 141,544 125,544 125,512 113,512 113,557 137,582 183,582"
    "643,512 630,512 630,543 614,543 589,569 572,569 572,582 619,582 643,556"
Needler "251,539 241,539 215,565 184,565 184,582 251,582"
    "571,565 541,565 514,539 504,539 504,582 571,582"
Needler Pit "246,511 194,511 194,530 172,530 184,542 184,562 213,562 240,536 246,536"
    "509,511 561,511 561,530 583,530 571,541 571,562 542,562 516,536 509,536"
Needler Ramp "299,524 299,535 248,535 248,524"
    "508,524 508,535 457,535 457,524"
Pit "278,311 225,311 225,319 211,333 211,373 221,373 221,393 235,393 235,420 239,424 279,424 279,416 297,416 297,386 278,386"
    "477,312 530,312 530,318 543,332 543,373 535,373 535,394 524,394 524,416 509,431 476,431 476,417 459,417 459,386 477,386"
Pit Ramp "297,347 279,347 279,385 297,385"
    "476,347 459,347 459,385 476,385"
Platform "193,377 217,377 217,408 243,433 243,485 220,507 194,507 194,463 193,463 193,430 194,430 194,408 193,408"
    "562,377 538,377 538,408 512,434 512,484 535,507 561,507 561,464 562,464"
Rockets "387,453 387,462 368,462 368,453"
Runway "297,199 458,199 458,218 297,218"
Snipe Bridge "121,331 109,331 109,362 121,362"
    "646,331 634,331 634,360 646,360"
Snipe Pocket "110,287 97,287 97,302 110,302"
    "646,287 658,287 658,301 646,301"
Street "326,285 312,271 312,244 296,244 296,238 231,238 231,248 226,248 226,309 326,309"
    "444,245 524,245 524,248 530,248 530,311 430,311 430,285 444,270"
Sword "388,46 367,46 367,57 346,57 346,74 363,87 392,87 409,75 409,57 388,57"
Sword Ramp "247,82 300,82 300,92 247,92"
    "455,82 507,82 507,92 455,92"
Sword Window "334,96 334,110 343,119 357,119 357,136 326,136 318,129 318,96"
    "421,96 437,96 437,129 429,136 398,136 398,118 412,118 421,110"
S1 "183,275 212,275 212,280 216,280 216,283 222,283 222,292 217,292 215,294 213,294 213,307 183,307"
    "573,275 543,275 543,280 539,280 539,283 533,283 533,292 538,292 540,294 543,294 543,307 573,307"
S2 "119,249 133,249 133,317 121,328 84,328 84,271 119,271"
    "636,249 636,270 671,270 671,328 633,328 622,317 622,249"
Training "296,333 365,333 365,384 300,384 300,364 313,364 313,346 296,346"
    "458,333 458,346 442,346 442,363 455,363 455,384 390,384 390,333"
Training Ramp "356,315 282,315 282,329 356,329"
    "401,315 473,315 473,328 401,328"
Training Pocket "312,351 300,351 300,363 312,363"
    "455,350 443,350 443,362 455,362"
Walshy "271,511 287,511 287,490 296,500 296,519 271,519"
    "482,510 468,510 468,490 459,500 459,519 482,519"
*/