import React, {useState} from 'react';
import Screenshot from '../ScreenShots';

function Onslaught() {
    const [screens,setScreens] = useState('');

    const turnGreen = (div) => {
        div.style.fill="rgba(0, 255, 0, 0.5)";
    }
    const returnColor = (div) => {
        div.style.fill="rgba(0, 0, 0, 0)";
    }
    const textGreen = (textP) => {
        textP.style.color="rgba(0, 255, 0, 1)"
    }
    const returnTextColor = (textP) => {
        textP.style.color="white";
    }
    return(
        <div className="onslaughtFullGrid">
            <h1 className="mapTitleOnslaught">Onslaught</h1>
            <div className="calloutsList" id="onslaughtCallouts">
                <p onMouseOver={() => {setScreens('A Corner'); turnGreen(document.getElementById('aCorner')); textGreen(document.getElementById('aCornerText')); turnGreen(document.getElementById('aCorner2'))}} onMouseOut={() => {returnColor(document.getElementById('aCorner')); returnTextColor(document.getElementById('aCornerText')); returnColor(document.getElementById('aCorner2'))}} id="aCornerText">A Corner</p>
                <p onMouseOver={() => {setScreens('A Cuts'); turnGreen(document.getElementById('aCuts')); textGreen(document.getElementById('aCutsText')); turnGreen(document.getElementById('aCuts2'))}} onMouseOut={() => {returnColor(document.getElementById('aCuts')); returnTextColor(document.getElementById('aCutsText')); returnColor(document.getElementById('aCuts2'))}} id="aCutsText">A Cuts</p>
                <p onMouseOver={() => {setScreens('A Dumpster'); turnGreen(document.getElementById('aDumpster')); textGreen(document.getElementById('aDumpsterText')); turnGreen(document.getElementById('aDumpster2'))}} onMouseOut={() => {returnColor(document.getElementById('aDumpster')); returnTextColor(document.getElementById('aDumpsterText')); returnColor(document.getElementById('aDumpster2'))}} id="aDumpsterText">A Dumpster</p>
                <p onMouseOver={() => {setScreens('A House'); turnGreen(document.getElementById('aHouse')); textGreen(document.getElementById('aHouseText')); turnGreen(document.getElementById('aHouse2'))}} onMouseOut={() => {returnColor(document.getElementById('aHouse')); returnTextColor(document.getElementById('aHouseText')); returnColor(document.getElementById('aHouse2'))}} id="aHouseText">A House</p>
                <p onMouseOver={() => {setScreens('A Jump Up'); turnGreen(document.getElementById('aJumpUp')); textGreen(document.getElementById('aJumpUpText')); turnGreen(document.getElementById('aJumpUp2'))}} onMouseOut={() => {returnColor(document.getElementById('aJumpUp')); returnTextColor(document.getElementById('aJumpUpText')); returnColor(document.getElementById('aJumpUp2'))}} id="aJumpUpText">A Jump Up</p>
                <p onMouseOver={() => {setScreens('A Maze'); turnGreen(document.getElementById('aMaze')); textGreen(document.getElementById('aMazeText'))}} onMouseOut={() => {returnColor(document.getElementById('aMaze')); returnTextColor(document.getElementById('aMazeText'))}} id="aMazeText">A Maze</p>
                <p onMouseOver={() => {setScreens('A Nest'); turnGreen(document.getElementById('aNest')); textGreen(document.getElementById('aNestText'))}} onMouseOut={() => {returnColor(document.getElementById('aNest')); returnTextColor(document.getElementById('aNestText'))}} id="aNestText">A Nest</p>
                <p onMouseOver={() => {setScreens('A Pocket'); turnGreen(document.getElementById('aPocket')); textGreen(document.getElementById('aPocketText')); turnGreen(document.getElementById('aPocket2'))}} onMouseOut={() => {returnColor(document.getElementById('aPocket')); returnTextColor(document.getElementById('aPocketText')); returnColor(document.getElementById('aPocket2'))}} id="aPocketText">A Pocket</p>
                <p onMouseOver={() => {setScreens('A Sneaky'); turnGreen(document.getElementById('aSneaky')); textGreen(document.getElementById('aSneakyText')); turnGreen(document.getElementById('aSneaky2'))}} onMouseOut={() => {returnColor(document.getElementById('aSneaky')); returnTextColor(document.getElementById('aSneakyText')); returnColor(document.getElementById('aSneaky2'))}} id="aSneakyText">A Sneaky</p>
                <p onMouseOver={() => {setScreens('A Stairs'); turnGreen(document.getElementById('aStairs')); textGreen(document.getElementById('aStairsText')); turnGreen(document.getElementById('aStairs2'))}} onMouseOut={() => {returnColor(document.getElementById('aStairs')); returnTextColor(document.getElementById('aStairsText')); returnColor(document.getElementById('aStairs2'))}} id="aStairsText">A Stairs</p>
                <p onMouseOver={() => {setScreens('A Standup'); turnGreen(document.getElementById('aStandup')); textGreen(document.getElementById('aStandupText')); turnGreen(document.getElementById('aStandup2'))}} onMouseOut={() => {returnColor(document.getElementById('aStandup')); returnTextColor(document.getElementById('aStandupText')); returnColor(document.getElementById('aStandup2'))}} id="aStandupText">A Standup</p>
                <p onMouseOver={() => {setScreens('A Street'); turnGreen(document.getElementById('aStreet')); textGreen(document.getElementById('aStreetText')); turnGreen(document.getElementById('aStreet2'))}} onMouseOut={() => {returnColor(document.getElementById('aStreet')); returnTextColor(document.getElementById('aStreetText')); returnColor(document.getElementById('aStreet2'))}} id="aStreetText">A Street</p>       
                <p onMouseOver={() => {setScreens('A Teepee'); turnGreen(document.getElementById('aTeepee')); textGreen(document.getElementById('aTeepeeText'))}} onMouseOut={() => {returnColor(document.getElementById('aTeepee')); returnTextColor(document.getElementById('aTeepeeText'))}} id="aTeepeeText">A Teepee</p>
                <p onMouseOver={() => {setScreens('A Tunnel'); turnGreen(document.getElementById('aTunnel')); textGreen(document.getElementById('aTunnelText'))}} onMouseOut={() => {returnColor(document.getElementById('aTunnel')); returnTextColor(document.getElementById('aTunnelText'))}} id="aTunnelText">A Tunnel</p>
                <p onMouseOver={() => {setScreens('Top A'); turnGreen(document.getElementById('topAOnslaught')); textGreen(document.getElementById('topAOnslaughtText'))}} onMouseOut={() => {returnColor(document.getElementById('topAOnslaught')); returnTextColor(document.getElementById('topAOnslaughtText'))}} id="topAOnslaughtText">Top A</p>
                <p onMouseOver={() => {setScreens('B Corner'); turnGreen(document.getElementById('bCorner')); textGreen(document.getElementById('bCornerText')); turnGreen(document.getElementById('bCorner2'))}} onMouseOut={() => {returnColor(document.getElementById('bCorner')); returnTextColor(document.getElementById('bCornerText')); returnColor(document.getElementById('bCorner2'))}} id="bCornerText">B Corner</p>
                <p onMouseOver={() => {setScreens('B Cuts'); turnGreen(document.getElementById('bCuts')); textGreen(document.getElementById('bCutsText')); turnGreen(document.getElementById('bCuts2'))}} onMouseOut={() => {returnColor(document.getElementById('bCuts')); returnTextColor(document.getElementById('bCutsText')); returnColor(document.getElementById('bCuts2'))}} id="bCutsText">B Cuts</p>
                <p onMouseOver={() => {setScreens('B Dumpster'); turnGreen(document.getElementById('bDumpster')); textGreen(document.getElementById('bDumpsterText')); turnGreen(document.getElementById('bDumpster2'))}} onMouseOut={() => {returnColor(document.getElementById('bDumpster')); returnTextColor(document.getElementById('bDumpsterText')); returnColor(document.getElementById('bDumpster2'))}} id="bDumpsterText">B Dumpster</p>
                <p onMouseOver={() => {setScreens('B House'); turnGreen(document.getElementById('bHouse')); textGreen(document.getElementById('bHouseText')); turnGreen(document.getElementById('bHouse2'))}} onMouseOut={() => {returnColor(document.getElementById('bHouse')); returnTextColor(document.getElementById('bHouseText')); returnColor(document.getElementById('bHouse2'))}} id="bHouseText">B House</p>
                <p onMouseOver={() => {setScreens('B Jump Up'); turnGreen(document.getElementById('bJumpUp')); textGreen(document.getElementById('bJumpUpText')); turnGreen(document.getElementById('bJumpUp2'))}} onMouseOut={() => {returnColor(document.getElementById('bJumpUp')); returnTextColor(document.getElementById('bJumpUpText')); returnColor(document.getElementById('bJumpUp2'))}} id="bJumpUpText">B Jump Up</p>
                <p onMouseOver={() => {setScreens('B Maze'); turnGreen(document.getElementById('bMaze')); textGreen(document.getElementById('bMazeText'))}} onMouseOut={() => {returnColor(document.getElementById('bMaze')); returnTextColor(document.getElementById('bMazeText'))}} id="bMazeText">B Maze</p>
                <p onMouseOver={() => {setScreens('B Nest'); turnGreen(document.getElementById('bNest')); textGreen(document.getElementById('bNestText')); turnGreen(document.getElementById('bNest'))}} onMouseOut={() => {returnColor(document.getElementById('bNest')); returnTextColor(document.getElementById('bNestText')); returnColor(document.getElementById('bNest'))}} id="bNestText">B Nest</p>
                <p onMouseOver={() => {setScreens('B Pocket'); turnGreen(document.getElementById('bPocket')); textGreen(document.getElementById('bPocketText')); turnGreen(document.getElementById('bPocket2'))}} onMouseOut={() => {returnColor(document.getElementById('bPocket')); returnTextColor(document.getElementById('bPocketText')); returnColor(document.getElementById('bPocket2'))}} id="bPocketText">B Pocket</p>
                <p onMouseOver={() => {setScreens('B Sneaky'); turnGreen(document.getElementById('bSneaky')); textGreen(document.getElementById('bSneakyText'))}} onMouseOut={() => {returnColor(document.getElementById('bSneaky')); returnTextColor(document.getElementById('bSneakyText'))}} id="bSneakyText">B Sneaky</p>
                <p onMouseOver={() => {setScreens('B Stairs'); turnGreen(document.getElementById('bStairs')); textGreen(document.getElementById('bStairsText')); turnGreen(document.getElementById('bStairs2'))}} onMouseOut={() => {returnColor(document.getElementById('bStairs')); returnTextColor(document.getElementById('bStairsText')); returnColor(document.getElementById('bStairs2'))}} id="bStairsText">B Stairs</p>
                <p onMouseOver={() => {setScreens('B Standup'); turnGreen(document.getElementById('bStandup')); textGreen(document.getElementById('bStandupText')); turnGreen(document.getElementById('bStandup2'))}} onMouseOut={() => {returnColor(document.getElementById('bStandup')); returnTextColor(document.getElementById('bStandupText')); returnColor(document.getElementById('bStandup2'))}} id="bStandupText">B Standup</p>
                <p onMouseOver={() => {setScreens('B Street'); turnGreen(document.getElementById('bStreet')); textGreen(document.getElementById('bStreetText')); turnGreen(document.getElementById('bStreet2'))}} onMouseOut={() => {returnColor(document.getElementById('bStreet')); returnTextColor(document.getElementById('bStreetText')); returnColor(document.getElementById('bStreet2'))}} id="bStreetText">B Street</p>
                <p onMouseOver={() => {setScreens('B Teepee'); turnGreen(document.getElementById('bTeepee')); textGreen(document.getElementById('bTeepeeText'))}} onMouseOut={() => {returnColor(document.getElementById('bTeepee')); returnTextColor(document.getElementById('bTeepeeText'))}} id="bTeepeeText">B Teepee</p>
                <p onMouseOver={() => {setScreens('B Tunnel'); turnGreen(document.getElementById('bTunnel')); textGreen(document.getElementById('bTunnelText'))}} onMouseOut={() => {returnColor(document.getElementById('bTunnel')); returnTextColor(document.getElementById('bTunnelText'))}} id="bTunnelText">B Tunnel</p>
                <p onMouseOver={() => {setScreens('Top B'); turnGreen(document.getElementById('topBOnslaught')); textGreen(document.getElementById('topBOnslaughtText'))}} onMouseOut={() => {returnColor(document.getElementById('topBOnslaught')); returnTextColor(document.getElementById('topBOnslaughtText'))}} id="topBOnslaughtText">Top B</p>
                <p onMouseOver={() => {setScreens('Basement'); turnGreen(document.getElementById('basement')); textGreen(document.getElementById('basementText')); turnGreen(document.getElementById('basement2'))}} onMouseOut={() => {returnColor(document.getElementById('basement')); returnTextColor(document.getElementById('basementText')); returnColor(document.getElementById('basement2'))}} id="basementText">Basement</p>
                <p onMouseOver={() => {setScreens('Courtyard'); turnGreen(document.getElementById('courtyard')); textGreen(document.getElementById('courtyardText')); turnGreen(document.getElementById('courtyard2'))}} onMouseOut={() => {returnColor(document.getElementById('courtyard')); returnTextColor(document.getElementById('courtyardText')); returnColor(document.getElementById('courtyard2'))}} id="courtyardText">Courtyard</p>
                <p onMouseOver={() => {setScreens('Flag'); turnGreen(document.getElementById('flag')); textGreen(document.getElementById('flagText')); turnGreen(document.getElementById('flag2'))}} onMouseOut={() => {returnColor(document.getElementById('flag')); returnTextColor(document.getElementById('flagText')); returnColor(document.getElementById('flag2'))}} id="flagText">Flag</p>
                <p onMouseOver={() => {setScreens('GarageDoor'); turnGreen(document.getElementById('garageDoor')); textGreen(document.getElementById('garageDoorText')); turnGreen(document.getElementById('garageDoor2'))}} onMouseOut={() => {returnColor(document.getElementById('garageDoor')); returnTextColor(document.getElementById('garageDoorText')); returnColor(document.getElementById('garageDoor2'))}} id="garageDoorText">Garage Door</p>
                <p onMouseOver={() => {setScreens('Shield'); turnGreen(document.getElementById('shield')); textGreen(document.getElementById('shieldText')); turnGreen(document.getElementById('shield2'))}} onMouseOut={() => {returnColor(document.getElementById('shield')); returnTextColor(document.getElementById('shieldText')); returnColor(document.getElementById('shield2'))}} id="shieldText">Shield</p>
                <p>Bottom Mid</p>
            </div>
            <svg id="onslaughtMap" width="750px" height="625px">
                <polygon onMouseOver={() => {setScreens('A Corner'); turnGreen(document.getElementById('aCorner')); textGreen(document.getElementById('aCornerText')); turnGreen(document.getElementById('aCorner2'))}} onMouseOut={() => {returnColor(document.getElementById('aCorner')); returnTextColor(document.getElementById('aCornerText')); returnColor(document.getElementById('aCorner2'))}}  id="aCorner" points="200,49 200,23 149,23 149,49"/>
                <polygon onMouseOver={() => {setScreens('A Corner'); turnGreen(document.getElementById('aCorner')); textGreen(document.getElementById('aCornerText')); turnGreen(document.getElementById('aCorner2'))}} onMouseOut={() => {returnColor(document.getElementById('aCorner')); returnTextColor(document.getElementById('aCornerText')); returnColor(document.getElementById('aCorner2'))}}  id="aCorner2" points="200,575 149,575 149,597 200,597"/>
                <polygon onMouseOver={() => {setScreens('A Cuts'); turnGreen(document.getElementById('aCuts')); textGreen(document.getElementById('aCutsText')); turnGreen(document.getElementById('aCuts2'))}} onMouseOut={() => {returnColor(document.getElementById('aCuts')); returnTextColor(document.getElementById('aCutsText')); returnColor(document.getElementById('aCuts2'))}}  id="aCuts" points="287,248 315,248 315,283 287,283"/>
                <polygon onMouseOver={() => {setScreens('A Cuts'); turnGreen(document.getElementById('aCuts')); textGreen(document.getElementById('aCutsText')); turnGreen(document.getElementById('aCuts2'))}} onMouseOut={() => {returnColor(document.getElementById('aCuts')); returnTextColor(document.getElementById('aCutsText')); returnColor(document.getElementById('aCuts2'))}}  id="aCuts2" points="288,343 315,343 315,375 288,375"/>
                <polygon onMouseOver={() => {setScreens('A Dumpster'); turnGreen(document.getElementById('aDumpster')); textGreen(document.getElementById('aDumpsterText')); turnGreen(document.getElementById('aDumpster2'))}} onMouseOut={() => {returnColor(document.getElementById('aDumpster')); returnTextColor(document.getElementById('aDumpsterText')); returnColor(document.getElementById('aDumpster2'))}}  id="aDumpster" points="238,98 244,103 212,130 206,124"/>
                <polygon onMouseOver={() => {setScreens('A Dumpster'); turnGreen(document.getElementById('aDumpster')); textGreen(document.getElementById('aDumpsterText')); turnGreen(document.getElementById('aDumpster2'))}} onMouseOut={() => {returnColor(document.getElementById('aDumpster')); returnTextColor(document.getElementById('aDumpsterText')); returnColor(document.getElementById('aDumpster2'))}}  id="aDumpster2" points="212,497 243,523 239,528 208,501"/>
                <polygon onMouseOver={() => {setScreens('A House'); turnGreen(document.getElementById('aHouse')); textGreen(document.getElementById('aHouseText')); turnGreen(document.getElementById('aHouse2'))}} onMouseOut={() => {returnColor(document.getElementById('aHouse')); returnTextColor(document.getElementById('aHouseText')); returnColor(document.getElementById('aHouse2'))}}  id="aHouse" points="241,50 241,23 285,23 285,50"/>
                <polygon onMouseOver={() => {setScreens('A House'); turnGreen(document.getElementById('aHouse')); textGreen(document.getElementById('aHouseText')); turnGreen(document.getElementById('aHouse2'))}} onMouseOut={() => {returnColor(document.getElementById('aHouse')); returnTextColor(document.getElementById('aHouseText')); returnColor(document.getElementById('aHouse2'))}}  id="aHouse2" points="240,574 285,574 285,598 240,598"/>
                <polygon onMouseOver={() => {setScreens('A Jump Up'); turnGreen(document.getElementById('aJumpUp')); textGreen(document.getElementById('aJumpUpText')); turnGreen(document.getElementById('aJumpUp2'))}} onMouseOut={() => {returnColor(document.getElementById('aJumpUp')); returnTextColor(document.getElementById('aJumpUpText')); returnColor(document.getElementById('aJumpUp2'))}}  id="aJumpUp" points="314,126 335,126 335,131 314,131"/>
                <polygon onMouseOver={() => {setScreens('A Jump Up'); turnGreen(document.getElementById('aJumpUp')); textGreen(document.getElementById('aJumpUpText')); turnGreen(document.getElementById('aJumpUp2'))}} onMouseOut={() => {returnColor(document.getElementById('aJumpUp')); returnTextColor(document.getElementById('aJumpUpText')); returnColor(document.getElementById('aJumpUp2'))}}  id="aJumpUp2" points="335,494 335,498 314,498 314,494"/>
                <polygon onMouseOver={() => {setScreens('A Maze'); turnGreen(document.getElementById('aMaze')); textGreen(document.getElementById('aMazeText'))}} onMouseOut={() => {returnColor(document.getElementById('aMaze')); returnTextColor(document.getElementById('aMazeText'))}}  id="aMaze" points="286,290 336,290 336,336 286,336"/>
                <polygon onMouseOver={() => {setScreens('A Nest'); turnGreen(document.getElementById('aNest')); textGreen(document.getElementById('aNestText'))}} onMouseOut={() => {returnColor(document.getElementById('aNest')); returnTextColor(document.getElementById('aNestText'))}}  id="aNest" points="286,290 314,290 314,336 286,336"/>
                <polygon onMouseOver={() => {setScreens('A Pocket'); turnGreen(document.getElementById('aPocket')); textGreen(document.getElementById('aPocketText')); turnGreen(document.getElementById('aPocket2'))}} onMouseOut={() => {returnColor(document.getElementById('aPocket')); returnTextColor(document.getElementById('aPocketText')); returnColor(document.getElementById('aPocket2'))}}  id="aPocket" points="302,75 316,75 316,99 302,99"/>
                <polygon onMouseOver={() => {setScreens('A Pocket'); turnGreen(document.getElementById('aPocket')); textGreen(document.getElementById('aPocketText')); turnGreen(document.getElementById('aPocket2'))}} onMouseOut={() => {returnColor(document.getElementById('aPocket')); returnTextColor(document.getElementById('aPocketText')); returnColor(document.getElementById('aPocket2'))}}  id="aPocket2" points="316,526 302,526 302,549 316,549"/>
                <polygon onMouseOver={() => {setScreens('A Sneaky'); turnGreen(document.getElementById('aSneaky')); textGreen(document.getElementById('aSneakyText')); turnGreen(document.getElementById('aSneaky2'))}} onMouseOut={() => {returnColor(document.getElementById('aSneaky')); returnTextColor(document.getElementById('aSneakyText')); returnColor(document.getElementById('aSneaky2'))}}  id="aSneaky" points="317,102 344,102 344,123 317,123"/>
                <polygon onMouseOver={() => {setScreens('A Sneaky'); turnGreen(document.getElementById('aSneaky')); textGreen(document.getElementById('aSneakyText')); turnGreen(document.getElementById('aSneaky2'))}} onMouseOut={() => {returnColor(document.getElementById('aSneaky')); returnTextColor(document.getElementById('aSneakyText')); returnColor(document.getElementById('aSneaky2'))}}  id="aSneaky2" points="317,501 344,501 344,524 317,524"/>
                <polygon onMouseOver={() => {setScreens('A Stairs'); turnGreen(document.getElementById('aStairs')); textGreen(document.getElementById('aStairsText')); turnGreen(document.getElementById('aStairs2'))}} onMouseOut={() => {returnColor(document.getElementById('aStairs')); returnTextColor(document.getElementById('aStairsText')); returnColor(document.getElementById('aStairs2'))}}  id="aStairs" points="241,77 241,51 285,51 285,77"/>
                <polygon onMouseOver={() => {setScreens('A Stairs'); turnGreen(document.getElementById('aStairs')); textGreen(document.getElementById('aStairsText')); turnGreen(document.getElementById('aStairs2'))}} onMouseOut={() => {returnColor(document.getElementById('aStairs')); returnTextColor(document.getElementById('aStairsText')); returnColor(document.getElementById('aStairs2'))}}  id="aStairs2" points="285,549 239,549 239,573 285,573"/>
                <polygon onMouseOver={() => {setScreens('A Standup'); turnGreen(document.getElementById('aStandup')); textGreen(document.getElementById('aStandupText')); turnGreen(document.getElementById('aStandup2'))}} onMouseOut={() => {returnColor(document.getElementById('aStandup')); returnTextColor(document.getElementById('aStandupText')); returnColor(document.getElementById('aStandup2'))}}  id="aStandup" points="148,119 148,81 180,81 180,119"/>
                <polygon onMouseOver={() => {setScreens('A Standup'); turnGreen(document.getElementById('aStandup')); textGreen(document.getElementById('aStandupText')); turnGreen(document.getElementById('aStandup2'))}} onMouseOut={() => {returnColor(document.getElementById('aStandup')); returnTextColor(document.getElementById('aStandupText')); returnColor(document.getElementById('aStandup2'))}}  id="aStandup2" points="149,508 179,508 179,546 149,546"/>
                <polygon onMouseOver={() => {setScreens('A Street'); turnGreen(document.getElementById('aStreet')); textGreen(document.getElementById('aStreetText')); turnGreen(document.getElementById('aStreet2'))}} onMouseOut={() => {returnColor(document.getElementById('aStreet')); returnTextColor(document.getElementById('aStreetText')); returnColor(document.getElementById('aStreet2'))}}  id="aStreet" points="180,272 180,125 148,125 148,272"/>
                <polygon onMouseOver={() => {setScreens('A Street'); turnGreen(document.getElementById('aStreet')); textGreen(document.getElementById('aStreetText')); turnGreen(document.getElementById('aStreet2'))}} onMouseOut={() => {returnColor(document.getElementById('aStreet')); returnTextColor(document.getElementById('aStreetText')); returnColor(document.getElementById('aStreet2'))}}  id="aStreet2" points="180,349 148,349 148,497 180,497"/>
                <polygon onMouseOver={() => {setScreens('A Teepee'); turnGreen(document.getElementById('aTeepee')); textGreen(document.getElementById('aTeepeeText'))}} onMouseOut={() => {returnColor(document.getElementById('aTeepee')); returnTextColor(document.getElementById('aTeepeeText'))}}  id="aTeepee" points="254,274 285,274 285,349 254,349"/>
                <polygon onMouseOver={() => {setScreens('A Tunnel'); turnGreen(document.getElementById('aTunnel')); textGreen(document.getElementById('aTunnelText'))}} onMouseOut={() => {returnColor(document.getElementById('aTunnel')); returnTextColor(document.getElementById('aTunnelText'))}}  id="aTunnel" points="148,274 180,274 180,347 148,347"/>
                <polygon onMouseOver={() => {setScreens('Top A'); turnGreen(document.getElementById('topAOnslaught')); textGreen(document.getElementById('topAOnslaughtText'))}} onMouseOut={() => {returnColor(document.getElementById('topAOnslaught')); returnTextColor(document.getElementById('topAOnslaughtText'))}}  id="topAOnslaught" points="241,273 148,273 148,348 241,348"/>
                <polygon onMouseOver={() => {setScreens('B Corner'); turnGreen(document.getElementById('bCorner')); textGreen(document.getElementById('bCornerText')); turnGreen(document.getElementById('bCorner2'))}} onMouseOut={() => {returnColor(document.getElementById('bCorner')); returnTextColor(document.getElementById('bCornerText')); returnColor(document.getElementById('bCorner2'))}}  id="bCorner" points="521,50 521,23 575,23 575,50"/>
                <polygon onMouseOver={() => {setScreens('B Corner'); turnGreen(document.getElementById('bCorner')); textGreen(document.getElementById('bCornerText')); turnGreen(document.getElementById('bCorner2'))}} onMouseOut={() => {returnColor(document.getElementById('bCorner')); returnTextColor(document.getElementById('bCornerText')); returnColor(document.getElementById('bCorner2'))}}  id="bCorner2" points="519,573 575,573 575,597 519,597"/>
                <polygon onMouseOver={() => {setScreens('B Cuts'); turnGreen(document.getElementById('bCuts')); textGreen(document.getElementById('bCutsText')); turnGreen(document.getElementById('bCuts2'))}} onMouseOut={() => {returnColor(document.getElementById('bCuts')); returnTextColor(document.getElementById('bCutsText')); returnColor(document.getElementById('bCuts2'))}}  id="bCuts" points="431,248 402,248 402,282 431,282"/>
                <polygon onMouseOver={() => {setScreens('B Cuts'); turnGreen(document.getElementById('bCuts')); textGreen(document.getElementById('bCutsText')); turnGreen(document.getElementById('bCuts2'))}} onMouseOut={() => {returnColor(document.getElementById('bCuts')); returnTextColor(document.getElementById('bCutsText')); returnColor(document.getElementById('bCuts2'))}}  id="bCuts2" points="431,343 403,343 403,378 431,378"/>
                <polygon onMouseOver={() => {setScreens('B Dumpster'); turnGreen(document.getElementById('bDumpster')); textGreen(document.getElementById('bDumpsterText')); turnGreen(document.getElementById('bDumpster2'))}} onMouseOut={() => {returnColor(document.getElementById('bDumpster')); returnTextColor(document.getElementById('bDumpsterText')); returnColor(document.getElementById('bDumpster2'))}}  id="bDumpster" points="482,97 514,124 508,130 476,102"/>
                <polygon onMouseOver={() => {setScreens('B Dumpster'); turnGreen(document.getElementById('bDumpster')); textGreen(document.getElementById('bDumpsterText')); turnGreen(document.getElementById('bDumpster2'))}} onMouseOut={() => {returnColor(document.getElementById('bDumpster')); returnTextColor(document.getElementById('bDumpsterText')); returnColor(document.getElementById('bDumpster2'))}}  id="bDumpster2" points="510,497 477,524 481,528 514,501"/>
                <polygon onMouseOver={() => {setScreens('B House'); turnGreen(document.getElementById('bHouse')); textGreen(document.getElementById('bHouseText')); turnGreen(document.getElementById('bHouse2'))}} onMouseOut={() => {returnColor(document.getElementById('bHouse')); returnTextColor(document.getElementById('bHouseText')); returnColor(document.getElementById('bHouse2'))}}  id="bHouse" points="482,23 437,23 437,50 482,50"/>
                <polygon onMouseOver={() => {setScreens('B House'); turnGreen(document.getElementById('bHouse')); textGreen(document.getElementById('bHouseText')); turnGreen(document.getElementById('bHouse2'))}} onMouseOut={() => {returnColor(document.getElementById('bHouse')); returnTextColor(document.getElementById('bHouseText')); returnColor(document.getElementById('bHouse2'))}}  id="bHouse2" points="481,573 433,573 433,597 481,597"/>
                <polygon onMouseOver={() => {setScreens('B Jump Up'); turnGreen(document.getElementById('bJumpUp')); textGreen(document.getElementById('bJumpUpText')); turnGreen(document.getElementById('bJumpUp2'))}} onMouseOut={() => {returnColor(document.getElementById('bJumpUp')); returnTextColor(document.getElementById('bJumpUpText')); returnColor(document.getElementById('bJumpUp2'))}}  id="bJumpUp" points="386,126 409,126 409,131 386,131"/>
                <polygon onMouseOver={() => {setScreens('B Jump Up'); turnGreen(document.getElementById('bJumpUp')); textGreen(document.getElementById('bJumpUpText')); turnGreen(document.getElementById('bJumpUp2'))}} onMouseOut={() => {returnColor(document.getElementById('bJumpUp')); returnTextColor(document.getElementById('bJumpUpText')); returnColor(document.getElementById('bJumpUp2'))}}  id="bJumpUp2" points="387,494 408,494 408,498 387,498"/>
                <polygon onMouseOver={() => {setScreens('B Maze'); turnGreen(document.getElementById('bMaze')); textGreen(document.getElementById('bMazeText'))}} onMouseOut={() => {returnColor(document.getElementById('bMaze')); returnTextColor(document.getElementById('bMazeText'))}}  id="bMaze" points="380,290 434,290 434,336 380,336"/>
                <polygon onMouseOver={() => {setScreens('B Nest'); turnGreen(document.getElementById('bNest')); textGreen(document.getElementById('bNestText')); turnGreen(document.getElementById('bNest'))}} onMouseOut={() => {returnColor(document.getElementById('bNest')); returnTextColor(document.getElementById('bNestText')); returnColor(document.getElementById('bNest'))}}  id="bNest" points="434,290 403,290 404,336 434,336"/>
                <polygon onMouseOver={() => {setScreens('B Pocket'); turnGreen(document.getElementById('bPocket')); textGreen(document.getElementById('bPocketText')); turnGreen(document.getElementById('bPocket2'))}} onMouseOut={() => {returnColor(document.getElementById('bPocket')); returnTextColor(document.getElementById('bPocketText')); returnColor(document.getElementById('bPocket2'))}}  id="bPocket" points="419,76 407,76 407,98 419,98"/>
                <polygon onMouseOver={() => {setScreens('B Pocket'); turnGreen(document.getElementById('bPocket')); textGreen(document.getElementById('bPocketText')); turnGreen(document.getElementById('bPocket2'))}} onMouseOut={() => {returnColor(document.getElementById('bPocket')); returnTextColor(document.getElementById('bPocketText')); returnColor(document.getElementById('bPocket2'))}}  id="bPocket2" points="406,526 419,526 419,548 406,548"/>
                <polygon onMouseOver={() => {setScreens('B Sneaky'); turnGreen(document.getElementById('bSneaky')); textGreen(document.getElementById('bSneakyText'))}} onMouseOut={() => {returnColor(document.getElementById('bSneaky')); returnTextColor(document.getElementById('bSneakyText'))}}  id="bSneaky" points="405,501 377,501 377,524 405,524"/>
                <polygon onMouseOver={() => {setScreens('B Stairs'); turnGreen(document.getElementById('bStairs')); textGreen(document.getElementById('bStairsText')); turnGreen(document.getElementById('bStairs2'))}} onMouseOut={() => {returnColor(document.getElementById('bStairs')); returnTextColor(document.getElementById('bStairsText')); returnColor(document.getElementById('bStairs2'))}}  id="bStairs" points="482,51 437,51 437,77 482,77"/>
                <polygon onMouseOver={() => {setScreens('B Stairs'); turnGreen(document.getElementById('bStairs')); textGreen(document.getElementById('bStairsText')); turnGreen(document.getElementById('bStairs2'))}} onMouseOut={() => {returnColor(document.getElementById('bStairs')); returnTextColor(document.getElementById('bStairsText')); returnColor(document.getElementById('bStairs2'))}}  id="bStairs2" points="481,548 433,548 433,572 481,572"/>
                <polygon onMouseOver={() => {setScreens('B Standup'); turnGreen(document.getElementById('bStandup')); textGreen(document.getElementById('bStandupText')); turnGreen(document.getElementById('bStandup2'))}} onMouseOut={() => {returnColor(document.getElementById('bStandup')); returnTextColor(document.getElementById('bStandupText')); returnColor(document.getElementById('bStandup2'))}}  id="bStandup" points="576,131 576,92 541,92 541,131"/>
                <polygon onMouseOver={() => {setScreens('B Standup'); turnGreen(document.getElementById('bStandup')); textGreen(document.getElementById('bStandupText')); turnGreen(document.getElementById('bStandup2'))}} onMouseOut={() => {returnColor(document.getElementById('bStandup')); returnTextColor(document.getElementById('bStandupText')); returnColor(document.getElementById('bStandup2'))}}  id="bStandup2" points="541,494 576,494 576,529 541,529"/>
                <polygon onMouseOver={() => {setScreens('B Street'); turnGreen(document.getElementById('bStreet')); textGreen(document.getElementById('bStreetText')); turnGreen(document.getElementById('bStreet2'))}} onMouseOut={() => {returnColor(document.getElementById('bStreet')); returnTextColor(document.getElementById('bStreetText')); returnColor(document.getElementById('bStreet2'))}}  id="bStreet" points="541,274 576,274 576,132 541,132"/>
                <polygon onMouseOver={() => {setScreens('B Street'); turnGreen(document.getElementById('bStreet')); textGreen(document.getElementById('bStreetText')); turnGreen(document.getElementById('bStreet2'))}} onMouseOut={() => {returnColor(document.getElementById('bStreet')); returnTextColor(document.getElementById('bStreetText')); returnColor(document.getElementById('bStreet2'))}}  id="bStreet2" points="541,350 575,350 575,493 541,493"/>
                <polygon onMouseOver={() => {setScreens('B Teepee'); turnGreen(document.getElementById('bTeepee')); textGreen(document.getElementById('bTeepeeText'))}} onMouseOut={() => {returnColor(document.getElementById('bTeepee')); returnTextColor(document.getElementById('bTeepeeText'))}}  id="bTeepee" points="439,273 466,273 466,348 439,348"/>
                <polygon onMouseOver={() => {setScreens('B Tunnel'); turnGreen(document.getElementById('bTunnel')); textGreen(document.getElementById('bTunnelText'))}} onMouseOut={() => {returnColor(document.getElementById('bTunnel')); returnTextColor(document.getElementById('bTunnelText'))}}  id="bTunnel" points="575,276 541,276 541,348 575,348"/>
                <polygon onMouseOver={() => {setScreens('Top B'); turnGreen(document.getElementById('topBOnslaught')); textGreen(document.getElementById('topBOnslaughtText'))}} onMouseOut={() => {returnColor(document.getElementById('topBOnslaught')); returnTextColor(document.getElementById('topBOnslaughtText'))}}  id="topBOnslaught" points="575,275 481,275 481,349 575,349"/>
                <polygon onMouseOver={() => {setScreens('Basement'); turnGreen(document.getElementById('basement')); textGreen(document.getElementById('basementText')); turnGreen(document.getElementById('basement2'))}} onMouseOut={() => {returnColor(document.getElementById('basement')); returnTextColor(document.getElementById('basementText')); returnColor(document.getElementById('basement2'))}}  id="basement" points="285,77 285,101 436,101 436,77"/>
                <polygon onMouseOver={() => {setScreens('Basement'); turnGreen(document.getElementById('basement')); textGreen(document.getElementById('basementText')); turnGreen(document.getElementById('basement2'))}} onMouseOut={() => {returnColor(document.getElementById('basement')); returnTextColor(document.getElementById('basementText')); returnColor(document.getElementById('basement2'))}}  id="basement2" points="285,548 285,525 433,525 433,548"/>
                <polygon onMouseOver={() => {setScreens('Courtyard'); turnGreen(document.getElementById('courtyard')); textGreen(document.getElementById('courtyardText')); turnGreen(document.getElementById('courtyard2'))}} onMouseOut={() => {returnColor(document.getElementById('courtyard')); returnTextColor(document.getElementById('courtyardText')); returnColor(document.getElementById('courtyard2'))}}  id="courtyard" points="283,142 435,142 435,242 283,242"/>
                <polygon onMouseOver={() => {setScreens('Courtyard'); turnGreen(document.getElementById('courtyard')); textGreen(document.getElementById('courtyardText')); turnGreen(document.getElementById('courtyard2'))}} onMouseOut={() => {returnColor(document.getElementById('courtyard')); returnTextColor(document.getElementById('courtyardText')); returnColor(document.getElementById('courtyard2'))}}  id="courtyard2" points="284,479 284,385 440,385 440,479"/>
                <polygon onMouseOver={() => {setScreens('Flag'); turnGreen(document.getElementById('flag')); textGreen(document.getElementById('flagText')); turnGreen(document.getElementById('flag2'))}} onMouseOut={() => {returnColor(document.getElementById('flag')); returnTextColor(document.getElementById('flagText')); returnColor(document.getElementById('flag2'))}}  id="flag" points="345,51 378,51 378,77 345,77"/>
                <polygon onMouseOver={() => {setScreens('Flag'); turnGreen(document.getElementById('flag')); textGreen(document.getElementById('flagText')); turnGreen(document.getElementById('flag2'))}} onMouseOut={() => {returnColor(document.getElementById('flag')); returnTextColor(document.getElementById('flagText')); returnColor(document.getElementById('flag2'))}}  id="flag2" points="374,548 346,548 346,574 374,574"/>
                <polygon onMouseOver={() => {setScreens('Garage Door'); turnGreen(document.getElementById('garageDoor')); textGreen(document.getElementById('garageDoorText')); turnGreen(document.getElementById('garageDoor2'))}} onMouseOut={() => {returnColor(document.getElementById('garageDoor')); returnTextColor(document.getElementById('garageDoorText')); returnColor(document.getElementById('garageDoor2'))}}  id="garageDoor" points="583,120 595,120 595,189 583,189"/>
                <polygon onMouseOver={() => {setScreens('Garage Door'); turnGreen(document.getElementById('garageDoor')); textGreen(document.getElementById('garageDoorText')); turnGreen(document.getElementById('garageDoor2'))}} onMouseOut={() => {returnColor(document.getElementById('garageDoor')); returnTextColor(document.getElementById('garageDoorText')); returnColor(document.getElementById('garageDoor2'))}}  id="garageDoor2" points="583,442 595,442 595,512 583,512"/>
                <polygon onMouseOver={() => {setScreens('Shield'); turnGreen(document.getElementById('shield')); textGreen(document.getElementById('shieldText')); turnGreen(document.getElementById('shield2'))}} onMouseOut={() => {returnColor(document.getElementById('shield')); returnTextColor(document.getElementById('shieldText')); returnColor(document.getElementById('shield2'))}}  id="shield" points="368,22 351,22 351,39 368,39"/>
                <polygon onMouseOver={() => {setScreens('Shield'); turnGreen(document.getElementById('shield')); textGreen(document.getElementById('shieldText')); turnGreen(document.getElementById('shield2'))}} onMouseOut={() => {returnColor(document.getElementById('shield')); returnTextColor(document.getElementById('shieldText')); returnColor(document.getElementById('shield2'))}}  id="shield2" points="377,582 343,582 343,597 377,597"/>


                

            </svg>
            <Screenshot 
                Map={'Onslaught'}
                Screenshot={screens}
            />
        </div>
    );
}

export default Onslaught;

/*
A Corner ""
A Dumpster
A House
A Jump Up
A Pocket
A Sneaky
A Stairs
A Standup
A Street
A Cuts
B Corner
B Dumpster
B House
B Jump Up
B Pocket
B Sneaky
B Stairs
B Standup
B Street
B Cuts
Basement
Courtyard
Flag
Garage Door
Shield
Window


Top A "241,273 241,348 148,348 148,273"
A Tunnel "148,274 180,274 180,347 148,347"
A Teepee "254,274 285,274 285,349 254,349"
A Maze "286,290 334,290 334,336 286,336"
A Nest = same as A Maze
Bottom Mid "337,305 379,305 379,318 337,318"
B Maze "434,290 383,290 383,336 434,336"
B Nest = same as B Maze
B Teepee "439,273 466,273 466,348 439,348"
Top B "575,275 481,275 481,349 575,349"
B Tunnel "541,276 575,276 575,348 541,348"
*/

